# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `octoprint` gem.
# Please instead update this file by running `bin/tapioca gem octoprint`.


# Welcome to the Octoprint Gem!
#
# This gem is still under development.
#
# @attr client [Octoprint::Client] The configured API client
#
# source://octoprint//lib/octoprint.rb#20
module Octoprint
  class << self
    # The API client used for the requests
    #
    # source://octoprint//lib/octoprint.rb#39
    sig { returns(T.nilable(::Octoprint::Client)) }
    def client; end

    # Sets the API client used for the requests
    #
    # @param client [Client]
    #
    # source://octoprint//lib/octoprint.rb#45
    def client=(client); end

    # Configure the API client with the server's address and key
    #
    # source://octoprint//lib/octoprint.rb#30
    sig { params(host: ::String, api_key: ::String).void }
    def configure(host:, api_key:); end
  end
end

# source://octoprint//lib/octoprint.rb#52
module Octoprint::Access; end

# Represents a group in the OctoPrint access control system
#
# @example
#   group = Octoprint::Access::Group.new(
#   key: "operators",
#   name: "Operators",
#   description: "Can operate the printer",
#   permissions: ["CONTROL", "MONITOR"],
#   subgroups: [],
#   needs_role: [],
#   default: false,
#   removable: true,
#   changeable: true,
#   toggleable: false
#   )
#
# source://octoprint//lib/octoprint/access/group.rb#21
class Octoprint::Access::Group
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/access/group.rb#78
  def initialize(**kwargs); end

  # @return [Boolean] Whether this group can be changed
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def changeable; end

  # @return [Boolean] Whether this group is dangerous
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def dangerous; end

  # @return [Boolean] Whether this is a default group
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def default; end

  # @return [String] Description of the group
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def description; end

  # @return [Hash] Additional attributes from the API
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def extra; end

  # @return [String] The group key/identifier
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def key; end

  # @return [String] The human-readable name
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def name; end

  # @return [Hash] Needs information with groups and roles
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def needs; end

  # @return [Array<String>] Roles needed for this group
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def needs_role; end

  # @return [Array<String>] Permissions assigned to this group
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def permissions; end

  # @return [Boolean] Whether this group can be removed
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def removable; end

  # @return [Array<String>] Subgroups included in this group
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def subgroups; end

  # @return [Boolean] Whether this group can be toggled
  #
  # source://octoprint//lib/octoprint/access/group.rb#78
  def toggleable; end
end

# Provides access to the OctoPrint groups API
#
# @see https://docs.octoprint.org/en/master/api/access.html#groups
#
# source://octoprint//lib/octoprint/access/groups.rb#9
class Octoprint::Access::Groups < ::Octoprint::BaseResource
  class << self
    # Add a new group
    #
    # Requires the SETTINGS permission and a recent credentials check.
    #
    # @example Create a new group
    #   group = Octoprint::Access::Groups.add(
    #   key: "operators",
    #   name: "Operators",
    #   description: "Can operate the printer",
    #   permissions: ["CONTROL", "MONITOR"],
    #   subgroups: [],
    #   default: false
    #   )
    #
    # source://octoprint//lib/octoprint/access/groups.rb#63
    sig do
      params(
        key: ::String,
        name: ::String,
        description: ::String,
        permissions: T::Array[::String],
        subgroups: T::Array[::String],
        default: T::Boolean
      ).returns(T::Array[::Octoprint::Access::Group])
    end
    def add(key:, name:, description:, permissions:, subgroups:, default:); end

    # Delete a group
    #
    # Requires the SETTINGS permission and a recent credentials check.
    #
    # @example Delete a group
    #   Octoprint::Access::Groups.delete(key: "operators")
    #
    # source://octoprint//lib/octoprint/access/groups.rb#146
    sig do
      params(
        key: T.nilable(::String),
        path: ::String,
        params: T::Hash[::Symbol, T.untyped],
        headers: T::Hash[::Symbol, T.untyped],
        options: T::Hash[::Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def delete(key: T.unsafe(nil), path: T.unsafe(nil), params: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil)); end

    # Delete a resource at the given path
    #
    # source://octoprint//lib/octoprint/access/groups.rb#160
    sig { params(path: ::String).void }
    def delete_resource(path); end

    # Retrieve a specific group
    #
    # Requires the SETTINGS permission.
    #
    # @example Get a specific group
    #   group = Octoprint::Access::Groups.get(key: "operators")
    #
    # source://octoprint//lib/octoprint/access/groups.rb#92
    sig { params(key: ::String).returns(::Octoprint::Access::Group) }
    def get(key:); end

    # Retrieve a list of groups
    #
    # Requires the SETTINGS permission.
    #
    # @example Get all groups
    #   groups = Octoprint::Access::Groups.list
    #   groups.each do |group|
    #   puts "#{group.key}: #{group.name}"
    #   end
    #
    # source://octoprint//lib/octoprint/access/groups.rb#26
    sig { returns(T::Array[::Octoprint::Access::Group]) }
    def list; end

    # Update an existing group
    #
    # Requires the SETTINGS permission and a recent credentials check.
    #
    # @example Update a group
    #   group = Octoprint::Access::Groups.update(
    #   key: "operators",
    #   params: {
    #   description: "Updated description",
    #   permissions: ["CONTROL", "MONITOR", "FILES_LIST"]
    #   }
    #   )
    #
    # source://octoprint//lib/octoprint/access/groups.rb#114
    sig { params(key: ::String, params: T::Hash[::Symbol, T.untyped]).returns(T::Array[::Octoprint::Access::Group]) }
    def update(key:, params:); end
  end
end

# Represents a permission in the OctoPrint access control system
#
# @example
#   permission = Octoprint::Access::Permission.new(
#   key: "SETTINGS",
#   name: "Settings",
#   dangerous: false,
#   default_groups: ["admins", "operators"],
#   description: "Allows access to settings",
#   needs: ["CONNECTION"]
#   )
#
# source://octoprint//lib/octoprint/access/permission.rb#17
class Octoprint::Access::Permission
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/access/permission.rb#58
  def initialize(**kwargs); end

  # @return [Boolean] Whether this permission is dangerous
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def dangerous; end

  # @return [Array<String>] Groups that have this permission by default
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def default_groups; end

  # @return [String, nil] Description of the permission
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def description; end

  # @return [Hash] Additional attributes from the API
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def extra; end

  # @return [String] The permission key
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def key; end

  # @return [String] The human-readable name
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def name; end

  # @return [Array<String>] Permissions this one depends on
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def needs; end

  # @return [Array<String>] Roles this permission needs
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def needs_role; end

  # @return [String, nil] Plugin that provides this permission
  #
  # source://octoprint//lib/octoprint/access/permission.rb#58
  def plugin; end
end

# Provides access to the OctoPrint permissions API
#
# @see https://docs.octoprint.org/en/master/api/access.html#retrieve-a-list-of-permissions
#
# source://octoprint//lib/octoprint/access/permissions.rb#9
class Octoprint::Access::Permissions < ::Octoprint::BaseResource
  class << self
    # Retrieve a list of permissions
    #
    # @example Get all permissions
    #   permissions = Octoprint::Access::Permissions.list
    #   permissions.each do |permission|
    #   puts "#{permission.key}: #{permission.name}"
    #   end
    #
    # source://octoprint//lib/octoprint/access/permissions.rb#24
    sig { returns(T::Array[::Octoprint::Access::Permission]) }
    def list; end
  end
end

# Represents a user in the OctoPrint access control system
#
# @example
#   user = Octoprint::Access::User.new(
#   name: "john_doe",
#   active: true,
#   admin: false,
#   api_key: "ABC123",
#   settings: {},
#   groups: ["operators"],
#   permissions: ["CONTROL", "MONITOR"],
#   needs_role: []
#   )
#
# source://octoprint//lib/octoprint/access/user.rb#19
class Octoprint::Access::User
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/access/user.rb#72
  def initialize(**kwargs); end

  # @return [Boolean] Whether the user is active
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def active; end

  # @return [Boolean] Whether the user is an admin (deprecated, use groups)
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def admin; end

  # @return [String, nil] The user's API key (only in list requests)
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def api_key; end

  # @return [Hash] Additional attributes from the API
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def extra; end

  # @return [Array<String>] Groups the user belongs to
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def groups; end

  # @return [String] The user's login name
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def name; end

  # @return [Hash] Needs information with groups and roles
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def needs; end

  # @return [Array<String>] Roles needed by the user
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def needs_role; end

  # @return [Array<String>] Effective permissions for the user
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def permissions; end

  # @return [Array<String>] User roles
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def roles; end

  # @return [Hash] The user's settings
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def settings; end

  # @return [Boolean, nil] Whether this is a user (vs admin)
  #
  # source://octoprint//lib/octoprint/access/user.rb#72
  def user; end

  class << self
    # Convenient class method to get current user (delegates to Users.current)
    #
    # @example Get current user
    #   user = Octoprint::Access::User.current
    #   puts "Current user: #{user.name}"
    #
    # source://octoprint//lib/octoprint/access/user.rb#91
    sig { returns(::Octoprint::Access::User) }
    def current; end
  end
end

# Provides access to the OctoPrint users API
#
# @see https://docs.octoprint.org/en/master/api/access.html#users
#
# source://octoprint//lib/octoprint/access/users.rb#9
class Octoprint::Access::Users < ::Octoprint::BaseResource
  class << self
    # Add a new user
    #
    # Requires the SETTINGS permission and a recent credentials check.
    #
    # @example Create a new user
    #   user = Octoprint::Access::Users.add(
    #   name: "john_doe",
    #   password: "secure_password",
    #   active: true,
    #   admin: false
    #   )
    #
    # source://octoprint//lib/octoprint/access/users.rb#61
    sig do
      params(
        name: ::String,
        password: ::String,
        active: T::Boolean,
        admin: T::Boolean,
        groups: T.nilable(T::Array[::String]),
        permissions: T.nilable(T::Array[::String])
      ).returns(T::Array[::Octoprint::Access::User])
    end
    def add(name:, password:, active:, admin:, groups: T.unsafe(nil), permissions: T.unsafe(nil)); end

    # Change a user's password
    #
    # Requires appropriate permissions based on whether changing own or other's password.
    #
    # @example Change a user's password
    #   Octoprint::Access::Users.change_password(
    #   username: "john_doe",
    #   password: "new_secure_password"
    #   )
    #
    # source://octoprint//lib/octoprint/access/users.rb#172
    sig { params(username: ::String, password: ::String).returns(T.untyped) }
    def change_password(username:, password:); end

    # Retrieve information about the current user
    #
    # @example Get current user
    #   user = Octoprint::Access::Users.current
    #   puts "Current user: #{user.name}"
    # @raise [RuntimeError] when no client is configured
    #
    # source://octoprint//lib/octoprint/access/users.rb#249
    sig { returns(::Octoprint::Access::User) }
    def current; end

    # Delete a user
    #
    # Requires the SETTINGS permission and a recent credentials check.
    #
    # @example Delete a user
    #   Octoprint::Access::Users.delete(username: "john_doe")
    #
    # source://octoprint//lib/octoprint/access/users.rb#134
    sig do
      params(
        username: T.nilable(::String),
        path: T.nilable(::String),
        params: T.nilable(T::Hash[::Symbol, T.untyped]),
        headers: T.nilable(T::Hash[::Symbol, T.untyped]),
        options: T.nilable(T::Hash[::Symbol, T.untyped])
      ).returns(T.untyped)
    end
    def delete(username: T.unsafe(nil), path: T.unsafe(nil), params: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil)); end

    # Delete a user's API key
    #
    # Requires appropriate permissions.
    #
    # @example Delete API key
    #   Octoprint::Access::Users.delete_api_key(username: "john_doe")
    #
    # source://octoprint//lib/octoprint/access/users.rb#234
    sig { params(username: ::String).returns(T.untyped) }
    def delete_api_key(username:); end

    # Delete a resource at the given path
    #
    # source://octoprint//lib/octoprint/access/users.rb#148
    sig { params(path: ::String).void }
    def delete_resource(path); end

    # Generate a new API key for a user
    #
    # Requires appropriate permissions.
    #
    # @example Generate new API key
    #   api_key = Octoprint::Access::Users.generate_api_key(username: "john_doe")
    #
    # source://octoprint//lib/octoprint/access/users.rb#218
    sig { params(username: ::String).returns(::String) }
    def generate_api_key(username:); end

    # Retrieve a specific user
    #
    # Requires the SETTINGS permission.
    #
    # @example Get a specific user
    #   user = Octoprint::Access::Users.get(username: "john_doe")
    #
    # source://octoprint//lib/octoprint/access/users.rb#86
    sig { params(username: ::String).returns(::Octoprint::Access::User) }
    def get(username:); end

    # Get a user's settings
    #
    # @example Get user settings
    #   settings = Octoprint::Access::Users.get_settings(username: "john_doe")
    #
    # source://octoprint//lib/octoprint/access/users.rb#186
    sig { params(username: ::String).returns(T::Hash[::Symbol, T.untyped]) }
    def get_settings(username:); end

    # Retrieve a list of users
    #
    # Requires the SETTINGS permission.
    #
    # @example Get all users
    #   users = Octoprint::Access::Users.list
    #   users.each do |user|
    #   puts "#{user.name} - Active: #{user.active}"
    #   end
    #
    # source://octoprint//lib/octoprint/access/users.rb#26
    sig { returns(T::Array[::Octoprint::Access::User]) }
    def list; end

    # Update an existing user
    #
    # Requires the SETTINGS permission and a recent credentials check.
    #
    # @example Update a user
    #   user = Octoprint::Access::Users.update(
    #   username: "john_doe",
    #   params: {
    #   active: false,
    #   groups: ["operators", "users"]
    #   }
    #   )
    #
    # source://octoprint//lib/octoprint/access/users.rb#108
    sig do
      params(
        username: ::String,
        params: T::Hash[::Symbol, T.untyped]
      ).returns(T::Array[::Octoprint::Access::User])
    end
    def update(username:, params:); end

    # Update a user's settings
    #
    # @example Update user settings
    #   settings = Octoprint::Access::Users.update_settings(
    #   username: "john_doe",
    #   settings: { interface: { color: "dark" } }
    #   )
    #
    # source://octoprint//lib/octoprint/access/users.rb#203
    sig { params(username: ::String, settings: T::Hash[::Symbol, T.untyped]).returns(T::Hash[::Symbol, T.untyped]) }
    def update_settings(username:, settings:); end

    private

    # source://octoprint//lib/octoprint/access/users.rb#265
    sig { params(path: ::String, params: T::Hash[::Symbol, T.untyped]).returns(T.untyped) }
    def patch_with_hash_format(path: T.unsafe(nil), params: T.unsafe(nil)); end

    # source://octoprint//lib/octoprint/access/users.rb#255
    sig { params(path: ::String, params: T::Hash[::Symbol, T.untyped]).returns(T.untyped) }
    def post_with_hash_format(path: T.unsafe(nil), params: T.unsafe(nil)); end

    # source://octoprint//lib/octoprint/access/users.rb#260
    sig { params(path: ::String, params: T::Hash[::Symbol, T.untyped]).returns(T.untyped) }
    def put_with_hash_format(path: T.unsafe(nil), params: T.unsafe(nil)); end
  end
end

# AutoInitializable provides automatic initialization and typed attribute generation.
#
# This module eliminates repetitive initialization code by automatically generating:
# - Typed instance variables from keyword arguments
# - Sorbet-typed attr_reader methods
# - Type conversion for nested objects
#
# @example Basic usage
#   class User
#   include AutoInitializable
#
#   auto_attr :name, type: String, nilable: false
#   auto_attr :email, type: String
#   auto_attr :age, type: Integer
#
#   auto_initialize!
#   end
#
#   user = User.new(name: "John", email: "john@example.com", age: 30)
#   user.name  # => "John" (typed as String)
#   user.email # => "john@example.com" (typed as T.nilable(String))
# @example Type conversion behavior
#   # Basic Ruby types (Hash, Array, String, Integer) are preserved as-is
#   auto_attr :data, type: Hash        # No conversion, preserves original hash
#
#   # Custom classes are auto-converted from hash data
#   auto_attr :user, type: User        # Calls User.new(**hash_data)
#
#   # Arrays of custom classes
#   auto_attr :users, type: User, array: true  # Maps each hash to User.new(**hash)
# @example With custom classes and arrays
#   class Profile
#   include AutoInitializable
#
#   auto_attr :user, type: User
#   auto_attr :tags, type: String, array: true
#   auto_attr :metadata, type: Hash
#
#   auto_initialize!
#   end
#
#   profile = Profile.new(
#   user: { name: "John", email: "john@example.com" },  # Auto-converted to User
#   tags: ["admin", "developer"],                       # Typed as T.nilable(T::Array[String])
#   metadata: { created_at: Time.now }                  # Preserved as Hash
#   )
#
# source://octoprint//lib/octoprint/auto_initializable.rb#53
module Octoprint::AutoInitializable
  mixes_in_class_methods ::Octoprint::AutoInitializable::ClassMethods
end

# Class methods added when AutoInitializable is included.
#
# These methods provide the DSL for declaring auto-initialized attributes
# and generating the corresponding initialization logic.
#
# source://octoprint//lib/octoprint/auto_initializable.rb#61
module Octoprint::AutoInitializable::ClassMethods
  # Declares an attribute that will be automatically initialized and typed.
  #
  # @example Arrays
  #   auto_attr :tags, type: String, array: true
  #   auto_attr :users, type: User, array: true
  # @example Basic attributes
  #   auto_attr :name, type: String, nilable: false
  #   auto_attr :email, type: String
  #   auto_attr :age, type: Integer
  # @example Complex types
  #   auto_attr :metadata, type: Hash
  #   auto_attr :profile, type: Profile
  # @example Custom key mapping
  #   auto_attr :display_name, type: String, from: :display
  # @note Basic Ruby types (Hash, Array, String, Integer, Float) are preserved without conversion.
  #   Custom classes will be instantiated from hash data using Class.new(**hash).
  #
  # source://octoprint//lib/octoprint/auto_initializable.rb#99
  sig do
    params(
      name: ::Symbol,
      type: T.untyped,
      from: T.nilable(::Symbol),
      array: T::Boolean,
      nilable: T::Boolean
    ).void
  end
  def auto_attr(name, type: T.unsafe(nil), from: T.unsafe(nil), array: T.unsafe(nil), nilable: T.unsafe(nil)); end

  # Returns the hash of declared attributes and their configuration.
  #
  # @example
  #   User.auto_attrs
  #   # => {
  #   #   name: { type: String, from: :name, array: false, nilable: false },
  #   #   email: { type: String, from: :email, array: false, nilable: true }
  #   # }
  #
  # source://octoprint//lib/octoprint/auto_initializable.rb#186
  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def auto_attrs; end

  # Generates the initialize method and typed attr_readers based on declared auto_attr calls.
  #
  # This method must be called after all auto_attr declarations to generate the actual
  # initialization code and Sorbet-typed attribute readers.
  #
  # @example
  #   class User
  #   include AutoInitializable
  #
  #   auto_attr :name, type: String
  #   auto_attr :age, type: Integer
  #
  #   auto_initialize!  # Must be called after auto_attr declarations
  #   end
  # @note This method generates:
  #   - An initialize method that accepts keyword arguments
  #   - Type conversion for nested objects
  #   - Sorbet-typed attr_reader methods
  #   - Automatic validation that required attributes are provided
  #
  # source://octoprint//lib/octoprint/auto_initializable.rb#130
  sig { void }
  def auto_initialize!; end

  private

  # Converts a value to the specified type if appropriate.
  #
  # This method handles type conversion for nested objects during initialization.
  # Basic Ruby types (Hash, Array, String, etc.) are preserved as-is to avoid
  # unwanted conversions. Custom classes are instantiated from hash data.
  #
  # @example
  #   convert_value({ name: "John" }, User)     # => User.new(name: "John")
  #   convert_value({ key: "value" }, Hash)     # => { key: "value" } (unchanged)
  #   convert_value("text", String)             # => "text" (unchanged)
  #
  # source://octoprint//lib/octoprint/auto_initializable.rb#207
  sig { params(value: T.untyped, type: T.untyped).returns(T.untyped) }
  def convert_value(value, type); end
end

# Base class for all API resources.
#
# source://octoprint//lib/octoprint/base_resource.rb#6
class Octoprint::BaseResource
  # @return [BaseResource] a new instance of BaseResource
  #
  # source://octoprint//lib/octoprint/base_resource.rb#153
  def initialize(**attrs); end

  class << self
    # Sends a DELETE request to the resource's endpoint.
    #
    # source://octoprint//lib/octoprint/base_resource.rb#122
    sig do
      params(
        path: ::String,
        params: T::Hash[::Symbol, T.untyped],
        headers: T::Hash[::Symbol, T.untyped],
        options: T::Hash[::Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def delete(path: T.unsafe(nil), params: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil)); end

    # Instantiates an object from a hash. Can be overridden by child classes
    #
    # @param attrs [Hash] the object's attributes
    # @return [BaseResource]
    #
    # source://octoprint//lib/octoprint/base_resource.rb#136
    def deserialize(attrs); end

    # Gets a single resource and instantiates the object.
    #
    # @return [BaseResource]
    #
    # source://octoprint//lib/octoprint/base_resource.rb#20
    def fetch_resource(path = T.unsafe(nil), deserialize: T.unsafe(nil), options: T.unsafe(nil)); end

    # Sends a PATCH request to the resource's endpoint.
    #
    # source://octoprint//lib/octoprint/base_resource.rb#96
    sig do
      params(
        path: ::String,
        params: T::Hash[::Symbol, T.untyped],
        headers: T::Hash[::Symbol, T.untyped],
        options: T::Hash[::Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def patch(path: T.unsafe(nil), params: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil)); end

    # Sends a POST request to the resource's endpoint.
    #
    # source://octoprint//lib/octoprint/base_resource.rb#44
    sig do
      params(
        path: ::String,
        params: T::Hash[::Symbol, T.untyped],
        headers: T::Hash[::Symbol, T.untyped],
        options: T::Hash[::Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def post(path: T.unsafe(nil), params: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil)); end

    # Sends a PUT request to the resource's endpoint.
    #
    # source://octoprint//lib/octoprint/base_resource.rb#70
    sig do
      params(
        path: ::String,
        params: T::Hash[::Symbol, T.untyped],
        headers: T::Hash[::Symbol, T.untyped],
        options: T::Hash[::Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def put(path: T.unsafe(nil), params: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil)); end

    # Defines the path for the resource's endpoint
    #
    # @param path [String] The API's endpoint path
    #
    # source://octoprint//lib/octoprint/base_resource.rb#13
    def resource_path(path); end

    private

    # source://octoprint//lib/octoprint/base_resource.rb#145
    sig { returns(::Octoprint::Client) }
    def client; end
  end
end

# The API client object.
#
# @attr api_key [String]
# @attr client [Client]
# @attr host [String]
#
# source://octoprint//lib/octoprint/client.rb#13
class Octoprint::Client
  # @raise [Exceptions::MissingCredentialsError]
  # @return [Client] a new instance of Client
  #
  # source://octoprint//lib/octoprint/client.rb#16
  def initialize(host:, api_key:); end

  # @return [String] the current value of api_key
  #
  # source://octoprint//lib/octoprint/client.rb#14
  def api_key; end

  # @return [Client] the current value of client
  #
  # source://octoprint//lib/octoprint/client.rb#14
  def client; end

  # @return [String] the current value of host
  #
  # source://octoprint//lib/octoprint/client.rb#14
  def host; end

  # Instantiates an object from a hash. Can be overridden by child classes
  #
  # @param body [Hash] the body of the request
  # @param http_method [Symbol|String] the http method of the request
  # @param options [Hash] options
  # @param path [String] the path of the request
  # @return [Hash]
  #
  # source://octoprint//lib/octoprint/client.rb#31
  def request(path, options_or_http_method = T.unsafe(nil), body: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil), http_method: T.unsafe(nil)); end

  # Every request inside the block will be executed as this client without affecting the gem's initial configuration
  #
  # @return [Client]
  #
  # source://octoprint//lib/octoprint/client.rb#57
  def use; end

  private

  # source://octoprint//lib/octoprint/client.rb#107
  def new_client(multipart: T.unsafe(nil)); end

  # source://octoprint//lib/octoprint/client.rb#82
  def parse_response(response); end

  # @raise [error_class]
  #
  # source://octoprint//lib/octoprint/client.rb#67
  def process_error(response); end

  # source://octoprint//lib/octoprint/client.rb#98
  def request_with_client(http_method, path, body, headers, force_multipart: T.unsafe(nil)); end

  # source://octoprint//lib/octoprint/client.rb#87
  def transform_keys_recursively(obj); end
end

# Connection handling with the 3D printer
#
# Octoprint's API doc: https://docs.octoprint.org/en/master/api/connection.html
#
# @attr current [Connection::Settings] connection state
# @attr options [Connection::Options] connection options
# @example
#   Octoprint.configure(host: 'https://octopi.local/', api_key: 'j98G2nsJq...')
#
#   connection = Octoprint::Connection.get
#   connection.current.state= #=> "Printing"
#   connection.options.ports #=> ["/dev/ttyACM0"]
#
# source://octoprint//lib/octoprint/connection.rb#18
class Octoprint::Connection < ::Octoprint::BaseResource
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/connection.rb#26
  def initialize(**kwargs); end

  # connection state
  #
  # @return [Connection::Settings] the current value of current
  #
  # source://octoprint//lib/octoprint/connection.rb#26
  def current; end

  # connection options
  #
  # @return [Connection::Options] the current value of options
  #
  # source://octoprint//lib/octoprint/connection.rb#26
  def options; end

  class << self
    # Opens the serial connection from Octoprint to the printer. When the options are left out, OctoPrint will use
    # existing preference if available or attempt autodetection.
    #
    # @option [Boolean]
    # @option [Boolean]
    # @option [Integer]
    # @option [String]
    # @option [String]
    # @param [Boolean] [Hash] a customizable set of options
    # @param [Integer] [Hash] a customizable set of options
    # @param [String] [Hash] a customizable set of options
    # @return [True]
    #
    # source://octoprint//lib/octoprint/connection.rb#60
    def connect(params = T.unsafe(nil)); end

    # Closses the serial connection from Octoprint to the printer
    #
    # @return [True]
    #
    # source://octoprint//lib/octoprint/connection.rb#46
    def disconnect; end

    # Fakes an acknowledgment message for OctoPrint in case one got lost on the serial line and the communication with
    # the printer since stalled. This should only be used in “emergencies” (e.g. to save prints), the reason for the
    # lost acknowledgment should always be properly investigated and removed instead of depending on this “symptom
    # solver”.
    #
    # @return [True]
    #
    # source://octoprint//lib/octoprint/connection.rb#70
    def fake_ack; end

    # Retrieve the current connection settings, including information regarding the available baudrates and serial ports
    # and the current connection state.
    #
    # @example
    #   client = Octoprint::Client.new(host: 'https://octopi.local/', api_key: 'j98G2nsJq...')
    #
    #   connection = Octoprint::Connection.get(client: client)
    #   connection.current.state= #=> "Printing"
    #   connection.options.ports #=> ["/dev/ttyACM0"]
    # @return [Connection]
    #
    # source://octoprint//lib/octoprint/connection.rb#39
    def get; end
  end
end

# Available connection options of the printer.
#
# Octoprint's API doc: https://docs.octoprint.org/en/master/api/connection.html
#
# @attr autoconnect [Boolean | nil]
# @attr baudrate_preference [Integer]
# @attr baudrates [Array<Integer>] Available baudrates
# @attr port_preference [String | nil]
# @attr ports [Array<String>] Available ports
# @attr printer_profile_preference [String]
# @attr printer_profiles [Array<Hash>]
# @example
#   Octoprint.configure(host: 'https://octopi.local/', api_key: 'j98G2nsJq...')
#
#   options = Octoprint::Connection.get.options
#
#   options.ports #=> ["/dev/ttyACM0"]
#   options.baudrates #=>  [250000, 230400, 115200, 57600, 38400, 19200, 9600]
#   options.printer_profiles #=>  [{:id=>"_default", :name=>"Creality CR-10s"}]
#   options.port_preference #=>  nil
#   options.baudrate_preference #=>  250000
#   options.printer_profile_preference #=>  "_default"
#   options.autoconnect #=>  nil
#
# source://octoprint//lib/octoprint/connection/options.rb#30
class Octoprint::Connection::Options
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/connection/options.rb#41
  def initialize(**kwargs); end

  # @return [Boolean | nil] the current value of autoconnect
  #
  # source://octoprint//lib/octoprint/connection/options.rb#41
  def autoconnect; end

  # @return [Integer] the current value of baudrate_preference
  #
  # source://octoprint//lib/octoprint/connection/options.rb#41
  def baudrate_preference; end

  # Available baudrates
  #
  # @return [Array<Integer>] the current value of baudrates
  #
  # source://octoprint//lib/octoprint/connection/options.rb#41
  def baudrates; end

  # @return [String | nil] the current value of port_preference
  #
  # source://octoprint//lib/octoprint/connection/options.rb#41
  def port_preference; end

  # Available ports
  #
  # @return [Array<String>] the current value of ports
  #
  # source://octoprint//lib/octoprint/connection/options.rb#41
  def ports; end

  # @return [String] the current value of printer_profile_preference
  #
  # source://octoprint//lib/octoprint/connection/options.rb#41
  def printer_profile_preference; end

  # @return [Array<Hash>] the current value of printer_profiles
  #
  # source://octoprint//lib/octoprint/connection/options.rb#41
  def printer_profiles; end
end

# Current connection settings of the printer.
#
# Octoprint's API doc: https://docs.octoprint.org/en/master/api/connection.html
#
# @attr baudrate [Integer] Serial communication baud rate
# @attr port [String] Serial port
# @attr printer_profile [String] Current printer profile
# @attr state [String] Connection state
# @example
#   Octoprint.configure(host: 'https://octopi.local/', api_key: 'j98G2nsJq...')
#
#   settings = Octoprint::Connection.get.current
#
#   settings.state #=> "Operational"
#   settings.port #=>  "/dev/ttyACM0"
#   settings.baudrate #=> 250000
#   settings.printer_profile #=> "_default"
#
# source://octoprint//lib/octoprint/connection/settings.rb#24
class Octoprint::Connection::Settings
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/connection/settings.rb#32
  def initialize(**kwargs); end

  # Serial communication baud rate
  #
  # @return [Integer] the current value of baudrate
  #
  # source://octoprint//lib/octoprint/connection/settings.rb#32
  def baudrate; end

  # Serial port
  #
  # @return [String] the current value of port
  #
  # source://octoprint//lib/octoprint/connection/settings.rb#32
  def port; end

  # Current printer profile
  #
  # @return [String] the current value of printer_profile
  #
  # source://octoprint//lib/octoprint/connection/settings.rb#32
  def printer_profile; end

  # Connection state
  #
  # @return [String] the current value of state
  #
  # source://octoprint//lib/octoprint/connection/settings.rb#32
  def state; end
end

# Deserializable provides declarative deserialization configuration for API responses.
#
# This module allows classes to define how they should be deserialized from API response
# data using a clean, declarative DSL. It automatically handles common patterns like
# camelCase to snake_case conversion and unknown field collection, while supporting
# advanced features like nested object conversion, array deserialization, and custom transformations.
#
# @example Advanced usage with arrays and transformations
#   class Post
#   include Deserializable
#   include AutoInitializable
#
#   auto_attr :title, type: String
#   auto_attr :author, type: User
#   auto_attr :tags, type: String, array: true
#   auto_attr :metadata, type: Hash
#   auto_attr :extra, type: Hash
#
#   auto_initialize!
#
#   deserialize_config do
#   nested :author, User                     # Convert author hash to User
#   array :tags, String                     # Array of strings (no conversion needed)
#   collect_extras                          # Collect unknown fields into :extra
#
#   # Custom transformation
#   transform do |data|
#   data[:metadata][:processed_at] = Time.now
#   end
#   end
#   end
# @example Automatic features (always enabled)
#   class ApiProfile
#   include Deserializable
#   include AutoInitializable
#
#   auto_attr :first_name, type: String
#   auto_attr :heated_bed, type: T::Boolean
#   auto_attr :phone_number, type: String
#   auto_attr :extra, type: Hash
#
#   auto_initialize!
#
#   # No configuration needed for common patterns!
#   end
#
#   # API response: { firstName: "John", heatedBed: true, phoneNumber: "123-456-7890", apiVersion: "1.2" }
#   # Automatic conversion: firstName -> first_name, heatedBed -> heated_bed, phoneNumber -> phone_number
#   # Unknown fields collected: apiVersion -> extra[:apiVersion]
#   profile = ApiProfile.deserialize(api_data)
#   profile.first_name  # => "John"
#   profile.heated_bed  # => true
#   profile.extra       # => { apiVersion: "1.2" }
# @example Basic usage
#   class User
#   include Deserializable
#   include AutoInitializable
#
#   auto_attr :name, type: String
#   auto_attr :display_name, type: String
#   auto_attr :profile, type: Profile
#
#   auto_initialize!
#
#   deserialize_config do
#   rename display: :display_name            # Rename API keys
#   nested :profile, Profile                 # Convert nested hash to Profile object
#   end
#   end
#
#   # API response: { name: "John", display: "John Doe", profile: { bio: "Developer" } }
#   user = User.deserialize(api_data)
#   user.name         # => "John"
#   user.display_name # => "John Doe"
#   user.profile      # => Profile instance
# @example Manual deserialization (without DSL)
#   class LegacyClass
#   include Deserializable
#
#   def self.deserialize(data)
#   # Manual processing
#   rename_keys(data, { old_key: :new_key })
#   deserialize_nested(data, :child, ChildClass)
#   new(**data)
#   end
#   end
#
# source://octoprint//lib/octoprint/deserializable.rb#94
module Octoprint::Deserializable
  mixes_in_class_methods ::Octoprint::Deserializable::ClassMethods
end

# Class methods added when Deserializable is included.
#
# These methods provide the DSL for configuring deserialization behavior
# and performing the actual deserialization of API responses.
#
# source://octoprint//lib/octoprint/deserializable.rb#102
module Octoprint::Deserializable::ClassMethods
  # Converts camelCase keys to snake_case keys in the data hash.
  #
  # Automatically converts API field names from camelCase to snake_case to match
  # Ruby naming conventions. This eliminates the need for manual key renaming
  # for common camelCase patterns.
  #
  # @example
  #   data = { firstName: "John", lastName: "Doe", phoneNumber: "123-456-7890" }
  #   convert_camel_case_keys(data)
  #   # data is now { first_name: "John", last_name: "Doe", phone_number: "123-456-7890" }
  #
  # source://octoprint//lib/octoprint/deserializable.rb#299
  sig { params(data: T::Hash[::Symbol, T.untyped]).returns(T::Hash[::Symbol, T.untyped]) }
  def convert_camel_case_keys(data); end

  # Deserializes API response data into a Ruby object.
  #
  # This method applies all configured transformations in order:
  # 1. Nested object conversions
  # 2. Array element conversions
  # 3. Key renaming
  # 4. Custom transformations
  # 5. Extra field collection (if enabled)
  # 6. Object instantiation
  #
  # @example
  #   api_data = { name: "John", display: "John Doe", profile: { bio: "Dev" } }
  #   user = User.deserialize(api_data)
  #   user.name         # => "John"
  #   user.display_name # => "John Doe" (renamed from display)
  #   user.profile      # => Profile instance (converted from hash)
  #
  # source://octoprint//lib/octoprint/deserializable.rb#158
  sig { params(data: T::Hash[::Symbol, T.untyped]).returns(T.untyped) }
  def deserialize(data); end

  # Deserializes an array field by converting each element to the specified class.
  #
  # Maps over each item in the array, attempting to deserialize hash items into
  # instances of the specified class. Non-hash items are left unchanged.
  #
  # @example
  #   data = { users: [{ name: "John" }, { name: "Jane" }] }
  #   deserialize_array(data, :users, User)
  #   # data[:users] is now [User("John"), User("Jane")]
  #
  # source://octoprint//lib/octoprint/deserializable.rb#270
  sig do
    params(
      data: T::Hash[::Symbol, T.untyped],
      field: ::Symbol,
      klass: T.untyped
    ).returns(T::Hash[::Symbol, T.untyped])
  end
  def deserialize_array(data, field, klass); end

  # Configures deserialization behavior using a declarative DSL.
  #
  # This method provides a clean, readable way to define how API response data
  # should be transformed into Ruby objects. The configuration is cached and
  # reused across deserialize calls.
  #
  # @example Basic configuration
  #   deserialize_config do
  #   rename display: :display_name          # Rename keys
  #   nested :profile, Profile              # Convert nested objects
  #   array :tags, Tag                     # Convert array elements
  #   collect_extras                       # Collect unknown fields
  #   end
  # @see DeserializationConfig DSL methods available in the configuration block
  # @yield [config] Provides DSL methods for configuring deserialization
  #
  # source://octoprint//lib/octoprint/deserializable.rb#124
  sig { params(block: T.nilable(T.proc.bind(::Octoprint::Deserializable::DeserializationConfig).void)).void }
  def deserialize_config(&block); end

  # Returns the current deserialization configuration.
  #
  # @api private
  #
  # source://octoprint//lib/octoprint/deserializable.rb#134
  sig { returns(T.nilable(::Octoprint::Deserializable::DeserializationConfig)) }
  def deserialize_configuration; end

  # Deserializes a nested object field within the data hash.
  #
  # Attempts to convert a nested hash or object into an instance of the specified class.
  # First tries calling the class's `deserialize` method, then falls back to `new(**hash)`.
  #
  # @example
  #   data = { profile: { name: "John", age: 30 } }
  #   deserialize_nested(data, :profile, User)
  #   # data[:profile] is now a User instance
  #
  # source://octoprint//lib/octoprint/deserializable.rb#240
  sig do
    params(
      data: T::Hash[::Symbol, T.untyped],
      field: ::Symbol,
      klass: T.untyped
    ).returns(T::Hash[::Symbol, T.untyped])
  end
  def deserialize_nested(data, field, klass); end

  # Collects unknown fields into an :extra hash if the class supports it.
  #
  # Moves any fields that aren't defined as auto_attrs into a separate :extra
  # hash to preserve API data that doesn't have corresponding Ruby attributes.
  # This is useful for maintaining forward compatibility with API changes.
  # Only collects extras if the class has an :extra attribute defined.
  #
  # @example
  #   # Class has auto_attrs: [:name, :email, :extra]
  #   data = { name: "John", email: "john@example.com", unknown_field: "value" }
  #   handle_extras(data)
  #   # data is now { name: "John", email: "john@example.com", extra: { unknown_field: "value" } }
  #
  # source://octoprint//lib/octoprint/deserializable.rb#353
  sig { params(data: T::Hash[::Symbol, T.untyped]).void }
  def handle_extras(data); end

  # Renames keys in a data hash according to the provided mapping.
  #
  # This is essential for handling API responses where field names conflict with
  # Ruby built-in methods or don't match Ruby conventions. Many APIs use field
  # names that would override important Object methods if used as attribute names.
  #
  # @example Avoiding Ruby method conflicts
  #   data = { display: "John Doe", hash: "abc123", class: "User" }
  #   rename_keys(data, { display: :display_name, hash: :md5_hash, class: :klass })
  #   # data is now { display_name: "John Doe", md5_hash: "abc123", klass: "User" }
  #   # Avoids conflicts with Object#display, Object#hash, Object#class
  # @note Common Ruby method conflicts include: display, hash, class, type, method, send
  #
  # source://octoprint//lib/octoprint/deserializable.rb#212
  sig do
    params(
      data: T::Hash[::Symbol, T.untyped],
      mapping: T::Hash[::Symbol, ::Symbol]
    ).returns(T::Hash[::Symbol, T.untyped])
  end
  def rename_keys(data, mapping); end

  private

  # Checks if a symbol represents a camelCase identifier.
  #
  # source://octoprint//lib/octoprint/deserializable.rb#317
  sig { params(key: ::Symbol).returns(T::Boolean) }
  def camel_case?(key); end

  # Converts a camelCase symbol to snake_case.
  #
  # source://octoprint//lib/octoprint/deserializable.rb#328
  sig { params(camel_key: ::Symbol).returns(::Symbol) }
  def camel_to_snake(camel_key); end
end

# Configuration object for declarative deserialization.
#
# This class provides the DSL methods available within deserialize_config blocks.
# It stores the configuration for how data should be transformed during deserialization.
#
# @api private
# @see Deserializable#deserialize_config
#
# source://octoprint//lib/octoprint/deserializable.rb#384
class Octoprint::Deserializable::DeserializationConfig
  # @api private
  #
  # source://octoprint//lib/octoprint/deserializable.rb#388
  sig { void }
  def initialize; end

  # Configures a field to be deserialized as an array of objects.
  #
  # Each element in the array will be converted to an instance of the specified class
  # if it's a hash, otherwise left unchanged.
  #
  # @api private
  # @example
  #   array :users, User           # data[:users] array of hashes becomes array of User instances
  #   array :tags, Tag            # data[:tags] becomes array of Tag instances
  #
  # source://octoprint//lib/octoprint/deserializable.rb#443
  sig { params(field: ::Symbol, klass: T.untyped).void }
  def array(field, klass); end

  # @api private
  #
  # source://octoprint//lib/octoprint/deserializable.rb#403
  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def array_objects; end

  # @api private
  #
  # source://octoprint//lib/octoprint/deserializable.rb#408
  sig { returns(T::Hash[::Symbol, ::Symbol]) }
  def key_mappings; end

  # Configures a field to be deserialized as a nested object.
  #
  # The field's hash value will be converted to an instance of the specified class
  # by calling either `klass.deserialize(hash)` or `klass.new(**hash)`.
  #
  # @api private
  # @example
  #   nested :profile, Profile      # data[:profile] hash becomes Profile instance
  #   nested :location, Location    # data[:location] becomes Location instance
  #
  # source://octoprint//lib/octoprint/deserializable.rb#427
  sig { params(field: ::Symbol, klass: T.untyped).void }
  def nested(field, klass); end

  # @api private
  #
  # source://octoprint//lib/octoprint/deserializable.rb#398
  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def nested_objects; end

  # Configures key renaming for API response fields.
  #
  # This is essential when API field names conflict with Ruby built-in methods
  # or don't match Ruby naming conventions. Many APIs use field names that
  # would override important Object methods if used directly as attribute names.
  #
  # @api private
  # @example Avoiding Ruby method conflicts
  #   rename display: :display_name, hash: :md5_hash, class: :klass
  #   # "display" conflicts with Object#display (prints to stdout)
  #   # "hash" conflicts with Object#hash (returns object hash code)
  #   # "class" conflicts with Object#class (returns object's class)
  # @example Converting API naming to Ruby conventions
  #   rename firstName: :first_name, lastName: :last_name
  #   # Convert camelCase API fields to snake_case Ruby attributes
  #
  # source://octoprint//lib/octoprint/deserializable.rb#465
  sig { params(mappings: T::Hash[::Symbol, ::Symbol]).void }
  def rename(mappings); end

  # Adds a custom transformation to be applied to the data.
  #
  # Transformations are applied after nested/array conversions and key renaming,
  # but before extra field collection. This allows for complex custom logic
  # that can't be expressed through the other DSL methods.
  #
  # @api private
  # @example
  #   transform do |data|
  #   data[:processed_at] = Time.now
  #   data[:full_name] = "#{data[:first_name]} #{data[:last_name]}"
  #   end
  # @yield [data] The data hash to transform
  #
  # source://octoprint//lib/octoprint/deserializable.rb#484
  sig { params(block: T.proc.params(data: T::Hash[::Symbol, T.untyped]).void).void }
  def transform(&block); end

  # @api private
  #
  # source://octoprint//lib/octoprint/deserializable.rb#413
  sig { returns(T::Array[T.proc.params(data: T::Hash[::Symbol, T.untyped]).void]) }
  def transformations; end
end

# Octoprint exceptions
#
# source://octoprint//lib/octoprint/exceptions.rb#6
module Octoprint::Exceptions; end

# The client can't access the requested resources because of bad authentication
#
# source://octoprint//lib/octoprint/exceptions.rb#10
class Octoprint::Exceptions::AuthenticationError < ::Octoprint::Exceptions::Error; end

# The can't be processed because of invalid inputs
#
# source://octoprint//lib/octoprint/exceptions.rb#12
class Octoprint::Exceptions::BadRequestError < ::Octoprint::Exceptions::Error; end

# source://octoprint//lib/octoprint/exceptions.rb#18
class Octoprint::Exceptions::ConflictError < ::Octoprint::Exceptions::Error; end

# Base error.
#
# source://octoprint//lib/octoprint/exceptions.rb#8
class Octoprint::Exceptions::Error < ::StandardError; end

# The server encountered an unexpected condition which prevented it from fulfilling the request
#
# source://octoprint//lib/octoprint/exceptions.rb#16
class Octoprint::Exceptions::InternalServerError < ::Octoprint::Exceptions::Error; end

# Credentials are missing from the configuration. Set them using `Octoprint.configure()`
#
# source://octoprint//lib/octoprint/exceptions.rb#14
class Octoprint::Exceptions::MissingCredentialsError < ::Octoprint::Exceptions::Error; end

# source://octoprint//lib/octoprint/exceptions.rb#20
class Octoprint::Exceptions::NotFoundError < ::Octoprint::Exceptions::Error; end

# source://octoprint//lib/octoprint/exceptions.rb#17
class Octoprint::Exceptions::UnknownError < ::Octoprint::Exceptions::Error; end

# source://octoprint//lib/octoprint/exceptions.rb#19
class Octoprint::Exceptions::UnsupportedMediaTypeError < ::Octoprint::Exceptions::Error; end

# Information about files on the server
#
# Octoprint's API doc: https://docs.octoprint.org/en/master/api/files.html
#
# source://octoprint//lib/octoprint/files.rb#11
class Octoprint::Files < ::Octoprint::BaseResource
  # @return [Files] a new instance of Files
  #
  # source://octoprint//lib/octoprint/files.rb#17
  def initialize(files:, free: T.unsafe(nil), total: T.unsafe(nil)); end

  # Returns the value of attribute files.
  #
  # source://octoprint//lib/octoprint/files.rb#15
  def files; end

  # Returns the value of attribute free.
  #
  # source://octoprint//lib/octoprint/files.rb#15
  def free; end

  # Returns the value of attribute total.
  #
  # source://octoprint//lib/octoprint/files.rb#15
  def total; end

  class << self
    # Copies a file or folder
    #
    # source://octoprint//lib/octoprint/files.rb#217
    sig { params(filename: ::String, destination: ::String, location: ::Octoprint::Location).returns(T.untyped) }
    def copy(filename:, destination:, location: T.unsafe(nil)); end

    # Creates a folder
    #
    # @example
    #   folder = Octoprint::Files.create_folder(foldername: "test")
    #   folder.name #=> "test"
    #   folder.origin #=> "local"
    #   folder.path #=> "test"
    #   folder.refs #=> {resource: "http://octoprint.local/api/files/local/test"}
    #
    # source://octoprint//lib/octoprint/files.rb#114
    sig do
      params(
        foldername: ::String,
        location: ::Octoprint::Location,
        path: T.nilable(::String),
        _kargs: T::Hash[::Symbol, T.untyped]
      ).returns(::Octoprint::Files::OperationResult)
    end
    def create_folder(foldername:, location: T.unsafe(nil), path: T.unsafe(nil), **_kargs); end

    # Deletes a file
    #
    # source://octoprint//lib/octoprint/files.rb#246
    sig { params(filename: ::String, location: ::Octoprint::Location).returns(T.untyped) }
    def delete_file(filename:, location: T.unsafe(nil)); end

    # Fetches a single file or folder
    #
    # source://octoprint//lib/octoprint/files.rb#47
    sig do
      params(
        filename: ::String,
        location: ::Octoprint::Location,
        options: T.nilable(T::Hash[::Symbol, T.untyped])
      ).returns(::Octoprint::Files::File)
    end
    def get(filename:, location: T.unsafe(nil), options: T.unsafe(nil)); end

    # Issues a file command
    #
    # @option options
    # @option options
    # @option options
    #
    # source://octoprint//lib/octoprint/files.rb#146
    sig do
      params(
        filename: ::String,
        command: ::String,
        location: ::Octoprint::Location,
        options: T::Hash[::Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def issue_command(filename:, command:, location: T.unsafe(nil), options: T.unsafe(nil)); end

    # Fetches the list of files at a location
    #
    # source://octoprint//lib/octoprint/files.rb#32
    sig { params(location: ::Octoprint::Location, options: T::Hash[::Symbol, T.untyped]).returns(::Octoprint::Files) }
    def list(location: T.unsafe(nil), options: T.unsafe(nil)); end

    # Moves a file or folder
    #
    # source://octoprint//lib/octoprint/files.rb#232
    sig { params(filename: ::String, destination: ::String, location: ::Octoprint::Location).returns(T.untyped) }
    def move(filename:, destination:, location: T.unsafe(nil)); end

    # Selects a file for printing
    #
    # source://octoprint//lib/octoprint/files.rb#163
    sig do
      params(
        filename: ::String,
        location: ::Octoprint::Location,
        print: T.nilable(T::Boolean)
      ).returns(T.untyped)
    end
    def select(filename:, location: T.unsafe(nil), print: T.unsafe(nil)); end

    # Slices an STL file into GCODE
    #
    # source://octoprint//lib/octoprint/files.rb#199
    sig do
      params(
        filename: ::String,
        location: ::Octoprint::Location,
        print: T.nilable(T::Boolean),
        profile: T.nilable(T::Hash[::Symbol, T.untyped])
      ).returns(T.untyped)
    end
    def slice(filename:, location: T.unsafe(nil), print: T.unsafe(nil), profile: T.unsafe(nil)); end

    # Unselects the currently selected file
    #
    # source://octoprint//lib/octoprint/files.rb#178
    sig { params(filename: ::String, location: ::Octoprint::Location).returns(T.untyped) }
    def unselect(filename:, location: T.unsafe(nil)); end

    # Uploads a file
    #
    # @option options
    # @option options
    # @option options
    # @option options
    #
    # source://octoprint//lib/octoprint/files.rb#76
    sig do
      params(
        file_path: ::String,
        location: ::Octoprint::Location,
        options: {path: T.nilable(::String), select: T.nilable(T::Boolean), print: T.nilable(T::Boolean), userdata: T.nilable(::String)}
      ).returns(::Octoprint::Files::OperationResult)
    end
    def upload(file_path, location: T.unsafe(nil), options: T.unsafe(nil)); end
  end
end

# File information
#
# source://octoprint//lib/octoprint/files/file.rb#10
class Octoprint::Files::File
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/files/file.rb#35
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def children; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def dashboard; end

  # Convert Unix timestamp to Time object
  #
  # source://octoprint//lib/octoprint/files/file.rb#49
  sig { returns(T.nilable(::Time)) }
  def date; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def date_timestamp; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def display_layer_progress; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def display_name; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def extra; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def gcode_analysis; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def md5_hash; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def name; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def origin; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def path; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def prints; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def refs; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def size; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def statistics; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def type; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def type_path; end

  # source://octoprint//lib/octoprint/files/file.rb#35
  def userdata; end
end

# A folder in the file system
#
# source://octoprint//lib/octoprint/files/folder.rb#9
class Octoprint::Files::Folder
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/files/folder.rb#21
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/files/folder.rb#21
  def display_name; end

  # source://octoprint//lib/octoprint/files/folder.rb#21
  def name; end

  # source://octoprint//lib/octoprint/files/folder.rb#21
  def origin; end

  # source://octoprint//lib/octoprint/files/folder.rb#21
  def path; end

  # source://octoprint//lib/octoprint/files/folder.rb#21
  def refs; end
end

# Result of uploading a file or creating a folder
#
# source://octoprint//lib/octoprint/files/operation_result.rb#7
class Octoprint::Files::OperationResult
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/files/operation_result.rb#18
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/files/operation_result.rb#18
  def done; end

  # source://octoprint//lib/octoprint/files/operation_result.rb#18
  def effective_print; end

  # source://octoprint//lib/octoprint/files/operation_result.rb#18
  def effective_select; end

  # source://octoprint//lib/octoprint/files/operation_result.rb#18
  def files; end

  # source://octoprint//lib/octoprint/files/operation_result.rb#18
  def folder; end
end

# References relevant to this file, left out in abridged version
#
# source://octoprint//lib/octoprint/files/refs.rb#9
class Octoprint::Files::Refs
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/files/refs.rb#17
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/files/refs.rb#17
  def download; end

  # source://octoprint//lib/octoprint/files/refs.rb#17
  def model; end

  # source://octoprint//lib/octoprint/files/refs.rb#17
  def resource; end
end

# Information about the current print job.
#
# @example Get current job
#   job = Octoprint::Job.get
#   puts "State: #{job.state}"
#   puts "Progress: #{job.progress.percent}%"
# @see https://docs.octoprint.org/en/master/api/job.html
#
# source://octoprint//lib/octoprint/job.rb#13
class Octoprint::Job < ::Octoprint::BaseResource
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/job.rb#40
  def initialize(**kwargs); end

  # @return [String, nil] Error message if any
  #
  # source://octoprint//lib/octoprint/job.rb#40
  def error; end

  # @return [Hash] Any additional fields returned by the API
  #
  # source://octoprint//lib/octoprint/job.rb#40
  def extra; end

  # @return [Job::Information] Information about the target file
  #
  # source://octoprint//lib/octoprint/job.rb#40
  def information; end

  # @return [Job::Progress] Information about print progress
  #
  # source://octoprint//lib/octoprint/job.rb#40
  def progress; end

  # @return [String] Current state of the job
  #
  # source://octoprint//lib/octoprint/job.rb#40
  def state; end

  class << self
    # Retrieve information about the current job.
    #
    # @example Get current job
    #   job = Octoprint::Job.get
    #   puts "State: #{job.state}"
    # @raise [Octoprint::Exceptions::Error] if the request fails
    #
    # source://octoprint//lib/octoprint/job.rb#57
    sig { returns(::Octoprint::Job) }
    def get; end
  end
end

# Information regarding the target of the current print job.
#
# @example Access job information
#   job = Octoprint::Job.get
#   info = job.information
#   puts "File: #{info.file[:name]}"
#   puts "Estimated time: #{info.estimated_print_time} seconds"
# @see https://docs.octoprint.org/en/master/api/datamodel.html#sec-api-datamodel-jobs-job
#
# source://octoprint//lib/octoprint/job/information.rb#15
class Octoprint::Job::Information
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/job/information.rb#40
  def initialize(**kwargs); end

  # @return [Float, nil] The estimated print time for the file, in seconds
  #
  # source://octoprint//lib/octoprint/job/information.rb#40
  def estimated_print_time; end

  # @return [Hash] Any additional fields returned by the API
  #
  # source://octoprint//lib/octoprint/job/information.rb#40
  def extra; end

  # @return [Hash, nil] Information regarding the estimated filament usage
  #
  # source://octoprint//lib/octoprint/job/information.rb#40
  def filament; end

  # @return [Hash] The file that is the target of the current print job
  #
  # source://octoprint//lib/octoprint/job/information.rb#40
  def file; end

  # @return [Float, nil] The print time of the last print of the file, in seconds
  #
  # source://octoprint//lib/octoprint/job/information.rb#40
  def last_print_time; end
end

# Information regarding the progress of the current print job.
#
# @example Access job progress
#   job = Octoprint::Job.get
#   progress = job.progress
#   puts "Completion: #{progress.completion * 100}%"
#   puts "Time left: #{progress.print_time_left} seconds"
# @see https://docs.octoprint.org/en/master/api/datamodel.html#progress-information
#
# source://octoprint//lib/octoprint/job/progress.rb#15
class Octoprint::Job::Progress
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/job/progress.rb#44
  def initialize(**kwargs); end

  # @return [Float] The completion percentage of the current print job
  #
  # source://octoprint//lib/octoprint/job/progress.rb#44
  def completion; end

  # @return [Hash] Any additional fields returned by the API
  #
  # source://octoprint//lib/octoprint/job/progress.rb#44
  def extra; end

  # @return [Integer] Current position in the file being printed, in bytes
  #
  # source://octoprint//lib/octoprint/job/progress.rb#44
  def filepos; end

  # @return [Float] Time already spent printing, in seconds
  #
  # source://octoprint//lib/octoprint/job/progress.rb#44
  def print_time; end

  # @return [Float] Estimate of time left to print, in seconds
  #
  # source://octoprint//lib/octoprint/job/progress.rb#44
  def print_time_left; end

  # @return [String] Origin of the current time left estimate
  #
  # source://octoprint//lib/octoprint/job/progress.rb#44
  def print_time_left_origin; end
end

# Language pack management for OctoPrint server internationalization
#
# This class provides methods to manage language packs on the OctoPrint server.
# Language packs enable OctoPrint's user interface to be displayed in different
# languages. The API supports listing installed packs, uploading new language
# pack archives, and removing existing language packs.
#
# Language packs are organized by identifier (e.g., "_core", plugin names) and
# contain translations for specific locales (e.g., "fr", "de", "es").
#
# Octoprint's API doc: https://docs.octoprint.org/en/1.11.2/api/languages.html
#
# @example List all available language packs
#   languages = Octoprint::Languages.list
#   languages.language_packs.each do |pack_id, pack|
#   puts "#{pack.display}: #{pack.languages.join(', ')}"
#   end
# @example Remove a language pack
#   Octoprint::Languages.delete_pack(locale: "fr", pack: "_core")
# @example Upload a new language pack
#   result = Octoprint::Languages.upload("path/to/language-pack.zip")
#   puts "Uploaded #{result.length} language packs"
#   result.each do |pack|
#   puts "- #{pack.display} (#{pack.identifier}): #{pack.languages.join(', ')}"
#   end
# @example Upload with specific locale
#   result = Octoprint::Languages.upload("french.zip", locale: "fr")
#   puts "Installed French translations for #{result.length} components"
#
# source://octoprint//lib/octoprint/languages.rb#36
class Octoprint::Languages < ::Octoprint::BaseResource
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/languages.rb#46
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/languages.rb#46
  def extra; end

  # source://octoprint//lib/octoprint/languages.rb#46
  def language_packs; end

  class << self
    # Deletes a language pack
    #
    # source://octoprint//lib/octoprint/languages.rb#98
    sig { params(locale: ::String, pack: ::String).returns(T.untyped) }
    def delete_pack(locale:, pack:); end

    # Fetches the list of available language packs
    #
    # source://octoprint//lib/octoprint/languages.rb#63
    sig { returns(::Octoprint::Languages) }
    def list; end

    # Uploads a language pack
    #
    # source://octoprint//lib/octoprint/languages.rb#77
    sig do
      params(
        file_path: ::String,
        locale: T.nilable(::String)
      ).returns(T::Array[::Octoprint::Languages::LanguagePack])
    end
    def upload(file_path, locale: T.unsafe(nil)); end
  end
end

# Represents a single language pack available on the server
#
# A language pack contains translations for a specific component (like the core
# OctoPrint interface or a plugin) and includes information about which locales
# are available within that pack.
#
# @example Access language pack information
#   pack = languages.language_packs["_core"]
#   puts pack.display           # => "Core"
#   puts pack.identifier        # => "_core"
#   puts pack.languages         # => ["fr", "de", "es"]
#
# source://octoprint//lib/octoprint/languages/language_pack.rb#17
class Octoprint::Languages::LanguagePack
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/languages/language_pack.rb#27
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/languages/language_pack.rb#27
  def display; end

  # source://octoprint//lib/octoprint/languages/language_pack.rb#27
  def extra; end

  # source://octoprint//lib/octoprint/languages/language_pack.rb#27
  def identifier; end

  # source://octoprint//lib/octoprint/languages/language_pack.rb#27
  def languages; end
end

# The target location to which to upload the file.
#
# Currently only local and sdcard are supported here, with local referring to OctoPrint’s uploads folder and sdcard
# referring to the printer’s SD card.
#
# Octoprint's API doc: https://docs.octoprint.org/en/master/api/files.html
#
# source://octoprint//lib/octoprint/location.rb#11
class Octoprint::Location < ::T::Enum
  enums do
    Local = new
    SDCard = new
  end

  # source://octoprint//lib/octoprint/location.rb#17
  def to_s; end
end

# Log file management API
#
# This class provides methods to manage log files on the OctoPrint server.
# The logging functionality allows you to retrieve information about available
# log files and delete them when needed for maintenance or cleanup purposes.
#
# Log files contain important debugging and operational information from the
# OctoPrint server, including printer communication logs, error messages,
# and system events.
#
# OctoPrint's API doc: https://docs.octoprint.org/en/1.11.2/bundledplugins/logging.html
#
# @example Access log file details and references
#   logs = Octoprint::Logs.list
#   log_file = logs.files.first
#   puts "Log file: #{log_file.name}"
#   puts "Size: #{log_file.size} bytes"
#   puts "Last modified: #{log_file.modification_time}"
#   if log_file.refs
#   puts "Download URL: #{log_file.refs.download}"
#   puts "Resource URL: #{log_file.refs.resource}"
#   end
# @example Check disk space and cleanup if needed
#   logs = Octoprint::Logs.list
#   if logs.free && logs.free < 100_000_000 # Less than 100MB free
#   puts "Low disk space detected (#{logs.free} bytes free)"
#   # Delete archived log files to free space
#   archived_logs = logs.files.select { |log| log.name.include?('.gz') }
#   archived_logs.each do |log_file|
#   Octoprint::Logs.delete_file(filename: log_file.name)
#   puts "Deleted archived log: #{log_file.name}"
#   end
#   end
# @example Delete old log files
#   logs = Octoprint::Logs.list
#   old_logs = logs.files.select { |log| log.name.match?(/\.log\.\d+$/) }
#   old_logs.each do |log_file|
#   success = Octoprint::Logs.delete_file(filename: log_file.name)
#   puts success ? "Deleted #{log_file.name}" : "Failed to delete #{log_file.name}"
#   end
# @example List all available log files
#   logs = Octoprint::Logs.list
#   puts "Available log files (#{logs.files.length}):"
#   logs.files.each do |log_file|
#   puts "- #{log_file.name}: #{log_file.size} bytes, modified #{log_file.modification_time}"
#   end
#   puts "Free disk space: #{logs.free} bytes" if logs.free
#
# source://octoprint//lib/octoprint/logs.rb#55
class Octoprint::Logs < ::Octoprint::BaseResource
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/logs.rb#65
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/logs.rb#65
  def files; end

  # source://octoprint//lib/octoprint/logs.rb#65
  def free; end

  class << self
    # Deletes a specific log file
    #
    # @example
    #   result = Octoprint::Logs.delete_file(filename: "octoprint.log.1")
    #   puts "Deleted successfully" if result
    #
    # source://octoprint//lib/octoprint/logs.rb#94
    sig { params(filename: ::String).returns(T::Boolean) }
    def delete_file(filename:); end

    # Retrieves a list of available log files
    #
    # @example
    #   logs = Octoprint::Logs.list
    #   logs.files.each { |file| puts "#{file.name}: #{file.size} bytes" }
    #   puts "Free space: #{logs.free} bytes"
    #
    # source://octoprint//lib/octoprint/logs.rb#81
    sig { returns(::Octoprint::Logs) }
    def list; end
  end
end

# Individual log file representation
#
# Represents a single log file on the OctoPrint server with its metadata,
# including size, modification date, and download/resource references.
#
# @example Accessing download and resource URLs
#   log_file = logs.files.first
#   if log_file.refs
#   download_url = log_file.refs.download  # Direct download URL
#   resource_url = log_file.refs.resource  # API resource URL
#   end
# @example Working with log file information
#   logs = Octoprint::Logs.list
#   log_file = logs.files.first
#
#   puts log_file.name              # => "octoprint.log"
#   puts log_file.size              # => 1048576 (in bytes)
#   puts log_file.modification_time # => 2023-12-31 12:00:00 UTC
#   puts log_file.to_s              # => "octoprint.log (1048576 bytes, modified: 2023-12-31 12:00:00 UTC)"
#
# source://octoprint//lib/octoprint/logs/log_file.rb#26
class Octoprint::Logs::LogFile
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/logs/log_file.rb#36
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/logs/log_file.rb#36
  def date; end

  # Convert Unix timestamp to Time object
  #
  # source://octoprint//lib/octoprint/logs/log_file.rb#55
  sig { returns(::Time) }
  def modification_time; end

  # source://octoprint//lib/octoprint/logs/log_file.rb#36
  def name; end

  # source://octoprint//lib/octoprint/logs/log_file.rb#36
  def refs; end

  # source://octoprint//lib/octoprint/logs/log_file.rb#36
  def size; end

  # Returns a human-readable string representation of the log file
  #
  # source://octoprint//lib/octoprint/logs/log_file.rb#47
  sig { returns(::String) }
  def to_s; end
end

# References relevant to this log file
#
# Contains URLs for accessing the log file through different endpoints,
# including direct download and API resource access.
#
# @example Accessing log file URLs
#   log_file = Octoprint::Logs.list.files.first
#   refs = log_file.refs
#
#   puts refs.resource  # => "http://octoprint.local/plugin/logging/logs/octoprint.log"
#   puts refs.download  # => "http://octoprint.local/downloads/logs/octoprint.log"
#
# source://octoprint//lib/octoprint/logs/references.rb#19
class Octoprint::Logs::References
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/logs/references.rb#26
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/logs/references.rb#26
  def download; end

  # source://octoprint//lib/octoprint/logs/references.rb#26
  def resource; end
end

# Printer profile management for OctoPrint server configuration
#
# This class provides methods to manage printer profiles on the OctoPrint server.
# Printer profiles define the physical characteristics and capabilities of 3D printers
# including print volume, extruder configuration, heated bed capabilities, and movement speeds.
#
# Octoprint's API doc: https://docs.octoprint.org/en/1.11.2/api/printerprofiles.html
#
# @example Create a new printer profile
#   profile_data = {
#   name: "My Custom Printer",
#   model: "Custom Model",
#   volume: { width: 200, depth: 200, height: 180 }
#   }
#   new_profile = Octoprint::PrinterProfiles.create(profile: profile_data)
# @example Delete a printer profile
#   Octoprint::PrinterProfiles.delete(identifier: "old_printer")
# @example Get a specific printer profile
#   profile = Octoprint::PrinterProfiles.get(identifier: "_default")
#   puts "Volume: #{profile.volume.width}x#{profile.volume.depth}x#{profile.volume.height}mm"
# @example List all printer profiles
#   profiles = Octoprint::PrinterProfiles.list
#   profiles.profiles.each do |id, profile|
#   puts "#{profile.name}: #{profile.model} (#{profile.id})"
#   end
# @example Update an existing printer profile
#   updates = { name: "Updated Printer Name" }
#   Octoprint::PrinterProfiles.update(identifier: "custom_printer", profile: updates)
#
# source://octoprint//lib/octoprint/printer_profiles.rb#37
class Octoprint::PrinterProfiles < ::Octoprint::BaseResource
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/printer_profiles.rb#47
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/printer_profiles.rb#47
  def extra; end

  # source://octoprint//lib/octoprint/printer_profiles.rb#47
  def profiles; end

  class << self
    # Creates a new printer profile
    #
    # source://octoprint//lib/octoprint/printer_profiles.rb#92
    sig do
      params(
        profile: T::Hash[::Symbol, T.untyped],
        based_on: T.nilable(::String)
      ).returns(::Octoprint::PrinterProfiles::PrinterProfile)
    end
    def create(profile:, based_on: T.unsafe(nil)); end

    # Deletes a printer profile
    #
    # source://octoprint//lib/octoprint/printer_profiles.rb#129
    sig { params(identifier: ::String).returns(T.untyped) }
    def delete_profile(identifier:); end

    # Fetches a specific printer profile
    #
    # source://octoprint//lib/octoprint/printer_profiles.rb#77
    sig { params(identifier: ::String).returns(::Octoprint::PrinterProfiles::PrinterProfile) }
    def get(identifier:); end

    # Fetches the list of available printer profiles
    #
    # source://octoprint//lib/octoprint/printer_profiles.rb#64
    sig { returns(::Octoprint::PrinterProfiles) }
    def list; end

    # Updates an existing printer profile
    #
    # source://octoprint//lib/octoprint/printer_profiles.rb#112
    sig do
      params(
        identifier: ::String,
        profile: T::Hash[::Symbol, T.untyped]
      ).returns(::Octoprint::PrinterProfiles::PrinterProfile)
    end
    def update(identifier:, profile:); end

    private

    # Sends a PATCH request to the resource's endpoint.
    #
    # source://octoprint//lib/octoprint/printer_profiles.rb#153
    sig do
      params(
        path: ::String,
        params: T::Hash[::Symbol, T.untyped],
        headers: T::Hash[::Symbol, T.untyped],
        options: T::Hash[::Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def patch(path: T.unsafe(nil), params: T.unsafe(nil), headers: T.unsafe(nil), options: T.unsafe(nil)); end
  end
end

# Represents a single printer profile configuration
#
# A printer profile contains the physical characteristics and capabilities
# of a 3D printer, including dimensions, extruder configuration, heated bed
# capabilities, and movement speeds.
#
# @example Access printer profile information
#   profile = printer_profiles.profiles["_default"]
#   puts profile.name           # => "Default"
#   puts profile.model          # => "Generic RepRap Printer"
#   puts profile.volume.width   # => 200
#
# source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#17
class Octoprint::PrinterProfiles::PrinterProfile
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def initialize(**kwargs); end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def axes; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def color; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def current; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def default; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def extra; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def extruder; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def heated_bed; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def heated_chamber; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def id; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def model; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def name; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def resource; end

  # source://octoprint//lib/octoprint/printer_profiles/printer_profile.rb#36
  def volume; end
end

# Information about the OctoPrint server.
#
# Octoprint's API doc: https://docs.octoprint.org/en/master/api/server.html
#
# @attr safemode [String|nil] Server's version
# @attr version [String] Server's version
# @example
#   Octoprint.configure(host: 'https://octopi.local/', api_key: 'j98G2nsJq...')
#
#   server = Octoprint::ServerInformation.get
#   server.version= #=> "1.7.3"
#   server.safemode #=> "incomplete_startup"
#
# source://octoprint//lib/octoprint/server_information.rb#18
class Octoprint::ServerInformation < ::Octoprint::BaseResource
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/server_information.rb#37
  def initialize(**kwargs); end

  # @return [Hash] Any additional fields returned by the API
  #
  # source://octoprint//lib/octoprint/server_information.rb#37
  def extra; end

  # @return [String, nil] The server's safe mode status
  #
  # source://octoprint//lib/octoprint/server_information.rb#37
  def safemode; end

  # @return [String] The server's version number
  #
  # source://octoprint//lib/octoprint/server_information.rb#37
  def version; end

  class << self
    # Retrieve information regarding server status.
    #
    # @example Get server information
    #   server = Octoprint::ServerInformation.get
    #   puts "Version: #{server.version}"
    # @raise [Octoprint::Exceptions::Error] if the request fails
    #
    # source://octoprint//lib/octoprint/server_information.rb#48
    sig { returns(::Octoprint::ServerInformation) }
    def get; end
  end
end

# Version information about the OctoPrint server.
#
# @example Get server version
#   version = Octoprint::ServerVersion.get
#   puts "API: #{version.api}"
#   puts "Server: #{version.server}"
#   puts "Text: #{version.text}"
# @see https://docs.octoprint.org/en/master/api/version.html
#
# source://octoprint//lib/octoprint/server_version.rb#14
class Octoprint::ServerVersion < ::Octoprint::BaseResource
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/server_version.rb#37
  def initialize(**kwargs); end

  # @return [String] The server's API version
  #
  # source://octoprint//lib/octoprint/server_version.rb#37
  def api; end

  # @return [Hash] Any additional fields returned by the API
  #
  # source://octoprint//lib/octoprint/server_version.rb#37
  def extra; end

  # @return [String] The server's version number
  #
  # source://octoprint//lib/octoprint/server_version.rb#37
  def server; end

  # @return [String] Server version including the prefix "OctoPrint"
  #
  # source://octoprint//lib/octoprint/server_version.rb#37
  def text; end

  class << self
    # Retrieve information regarding server and API version.
    #
    # @example Get server version
    #   version = Octoprint::ServerVersion.get
    #   puts "API: #{version.api}"
    #   puts "Server: #{version.server}"
    # @raise [Octoprint::Exceptions::Error] if the request fails
    #
    # source://octoprint//lib/octoprint/server_version.rb#49
    sig { returns(::Octoprint::ServerVersion) }
    def get; end
  end
end

# The SystemCommands API allows retrieval and execution of system commands on the OctoPrint server.
# System commands can be used to shutdown or restart the OctoPrint server or the system it's running on.
#
# @see https://docs.octoprint.org/en/master/api/system.html OctoPrint System API Documentation
#
# source://octoprint//lib/octoprint/system_commands.rb#9
class Octoprint::SystemCommands < ::Octoprint::BaseResource
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/system_commands.rb#28
  def initialize(**kwargs); end

  # @return [Array<Command>] List of core (predefined) system commands
  #
  # source://octoprint//lib/octoprint/system_commands.rb#28
  def core; end

  # @return [Array<Command>] List of custom (user-defined) system commands
  #
  # source://octoprint//lib/octoprint/system_commands.rb#28
  def custom; end

  # @return [Hash] Any additional fields returned by the API that are not explicitly defined
  #
  # source://octoprint//lib/octoprint/system_commands.rb#28
  def extra; end

  class << self
    # Executes a registered system command on the OctoPrint server.
    #
    # This method sends a POST request to execute a specific system command.
    # The command must be pre-registered on the server and available in the specified source.
    #
    # @example Execute core reboot command
    #   Octoprint::SystemCommands.execute("core", "reboot")
    # @example Execute core restart command
    #   Octoprint::SystemCommands.execute("core", "restart")
    # @example Execute custom command
    #   Octoprint::SystemCommands.execute("custom", "my_custom_command")
    # @raise [Octoprint::Exceptions::Error] if the request fails or command is not found
    #
    # source://octoprint//lib/octoprint/system_commands.rb#106
    sig { params(source: ::String, action: ::String).returns(T::Boolean) }
    def execute(source, action); end

    # Retrieves all registered system commands from the OctoPrint server.
    #
    # This method fetches both core and custom system commands. Core commands are
    # predefined by OctoPrint (like shutdown, restart), while custom commands are
    # user-defined.
    #
    # @example Get all system commands
    #   commands = Octoprint::SystemCommands.list
    #
    #   # Access core commands
    #   commands.core.each do |cmd|
    #   puts "Core: #{cmd.name} - #{cmd.action}"
    #   end
    #
    #   # Access custom commands
    #   commands.custom.each do |cmd|
    #   puts "Custom: #{cmd.name} - #{cmd.action}"
    #   end
    # @raise [Octoprint::Exceptions::Error] if the request fails
    #
    # source://octoprint//lib/octoprint/system_commands.rb#57
    sig { returns(::Octoprint::SystemCommands) }
    def list; end

    # Retrieves all registered system commands for a specific source from the OctoPrint server.
    #
    # This method fetches system commands from a specific source (e.g., "core" or "custom").
    # The source determines which set of commands to retrieve.
    #
    # @example Get core system commands
    #   commands = Octoprint::SystemCommands.list_by_source("core")
    #   commands.each do |cmd|
    #   puts "#{cmd.name} - #{cmd.action}"
    #   end
    # @example Get custom system commands
    #   commands = Octoprint::SystemCommands.list_by_source("custom")
    #   commands.each do |cmd|
    #   puts "#{cmd.name} - #{cmd.action}"
    #   end
    # @raise [Octoprint::Exceptions::Error] if the request fails
    #
    # source://octoprint//lib/octoprint/system_commands.rb#82
    sig { params(source: ::String).returns(T::Array[::Octoprint::SystemCommands::Command]) }
    def list_by_source(source); end
  end
end

# Represents a single system command available on the OctoPrint server.
# System commands can be used to perform actions like shutdown, restart, etc.
#
# @see https://docs.octoprint.org/en/master/api/system.html#data-model
#
# source://octoprint//lib/octoprint/system_commands/command.rb#10
class Octoprint::SystemCommands::Command
  include ::Octoprint::Deserializable
  include ::Octoprint::AutoInitializable
  extend ::Octoprint::Deserializable::ClassMethods
  extend ::Octoprint::AutoInitializable::ClassMethods

  # source://octoprint//lib/octoprint/system_commands/command.rb#39
  def initialize(**kwargs); end

  # @return [String] The unique identifier/action name for this command
  #
  # source://octoprint//lib/octoprint/system_commands/command.rb#39
  def action; end

  # @return [String, nil] Optional confirmation message to show before executing
  #
  # source://octoprint//lib/octoprint/system_commands/command.rb#39
  def confirm; end

  # @return [Hash] Any additional fields returned by the API that are not explicitly defined
  #
  # source://octoprint//lib/octoprint/system_commands/command.rb#39
  def extra; end

  # @return [String] The human-readable name of the command
  #
  # source://octoprint//lib/octoprint/system_commands/command.rb#39
  def name; end

  # @return [String] The URL endpoint for executing this command
  #
  # source://octoprint//lib/octoprint/system_commands/command.rb#39
  def resource; end

  # @return [String] The source of the command (e.g., "core" or "custom")
  #
  # source://octoprint//lib/octoprint/system_commands/command.rb#39
  def source; end
end

# Common type aliases for use with auto_attr and Sorbet signatures.
#
# This module provides convenient type aliases for commonly used types
# in the OctoPrint API. These can be used with auto_attr or in regular
# Sorbet type annotations.
#
# @example Using in Sorbet signatures
#   sig { params(data: Types::Hash).returns(Types::NilableString) }
#   def process_data(data)
#   data[:name]
#   end
# @example Using with auto_attr
#   class User
#   include AutoInitializable
#
#   auto_attr :name, type: String, nilable: false
#   auto_attr :email, type: Types::NilableString   # Alternative syntax
#   auto_attr :tags, type: Types::StringArray
#   auto_attr :metadata, type: Types::Hash
#
#   auto_initialize!
#   end
#
# source://octoprint//lib/octoprint/types.rb#28
module Octoprint::Types; end

# Baud rate for serial connections
#
# @example 115200, 250000, 500000
#
# source://octoprint//lib/octoprint/types.rb#136
Octoprint::Types::BaudRate = Integer

# Bed temperature in Celsius
#
# @example 60.0, 80.5
#
# source://octoprint//lib/octoprint/types.rb#114
Octoprint::Types::BedTemperature = Float

# Connection Types
# Connection state string
#
# @example "Connected", "Disconnected", "Connecting"
#
# source://octoprint//lib/octoprint/types.rb#132
Octoprint::Types::ConnectionState = String

# Number of extruders
#
# @example 1, 2, 4
#
# source://octoprint//lib/octoprint/types.rb#110
Octoprint::Types::ExtruderCount = Integer

# File Types
# A file path string
#
# @example "/path/to/file.gcode"
#
# source://octoprint//lib/octoprint/types.rb#75
Octoprint::Types::FilePath = String

# File size in bytes
#
# @example 1048576
#
# source://octoprint//lib/octoprint/types.rb#79
Octoprint::Types::FileSize = Integer

# Network Types
# A hostname or IP address
#
# @example "octopi.local" or "192.168.1.100"
#
# source://octoprint//lib/octoprint/types.rb#93
Octoprint::Types::Hostname = String

# ISO 8601 formatted date string
#
# @example "2023-12-31T12:00:00Z"
#
# source://octoprint//lib/octoprint/types.rb#88
Octoprint::Types::Iso8601String = String

# Job Types
# Job state string
#
# @example "Printing", "Paused", "Operational"
#
# source://octoprint//lib/octoprint/types.rb#119
Octoprint::Types::JobState = String

# A port number
#
# @example 80, 443, 5000
#
# source://octoprint//lib/octoprint/types.rb#97
Octoprint::Types::Port = Integer

# Print time in seconds
#
# @example 3600, 7200
#
# source://octoprint//lib/octoprint/types.rb#127
Octoprint::Types::PrintTime = Integer

# Printer Types
# A printer identifier
#
# @example "ender3", "_default"
#
# source://octoprint//lib/octoprint/types.rb#106
Octoprint::Types::PrinterId = String

# Print progress percentage (0.0 to 100.0)
#
# @example 45.5, 100.0
#
# source://octoprint//lib/octoprint/types.rb#123
Octoprint::Types::ProgressPercent = Float

# Serial port name
#
# @example "/dev/ttyUSB0", "COM3"
#
# source://octoprint//lib/octoprint/types.rb#140
Octoprint::Types::SerialPort = String

# Time Types
# Unix timestamp (seconds since epoch)
#
# @example 1640995200
#
# source://octoprint//lib/octoprint/types.rb#84
Octoprint::Types::UnixTimestamp = Integer

# A URL string
#
# @example "https://octopi.local/api/version"
#
# source://octoprint//lib/octoprint/types.rb#101
Octoprint::Types::Url = String

# Alias for backward compatibility
#
# @deprecated Use Octoprint::Access::User instead
#
# source://octoprint//lib/octoprint.rb#52
Octoprint::User = Octoprint::Access::User

# Utility operations for testing paths, URLs, and connectivity.
#
# @example Test a path
#   result = Octoprint::Util.test_path(path: "/tmp/test")
#   puts "Exists: #{result.exists}"
# @see https://docs.octoprint.org/en/1.11.2/api/util.html
#
# source://octoprint//lib/octoprint/util.rb#12
class Octoprint::Util < ::Octoprint::BaseResource
  include ::Octoprint::AutoInitializable
  include ::Octoprint::Deserializable
  extend ::Octoprint::AutoInitializable::ClassMethods
  extend ::Octoprint::Deserializable::ClassMethods

  # source://octoprint//lib/octoprint/util.rb#35
  def initialize(**kwargs); end

  # @return [Boolean, nil] Whether the tested resource exists
  #
  # source://octoprint//lib/octoprint/util.rb#35
  def exists; end

  # @return [Hash] Any additional fields returned by the API
  #
  # source://octoprint//lib/octoprint/util.rb#35
  def extra; end

  # @return [String, nil] The result of the utility operation
  #
  # source://octoprint//lib/octoprint/util.rb#35
  def result; end

  # @return [String, nil] Status of the operation
  #
  # source://octoprint//lib/octoprint/util.rb#35
  def status; end

  class << self
    # Test network address
    #
    # source://octoprint//lib/octoprint/util.rb#150
    sig { params(address: T.nilable(::String)).returns(::Octoprint::Util) }
    def test_address(address: T.unsafe(nil)); end

    # Test file system paths
    #
    # source://octoprint//lib/octoprint/util.rb#54
    sig do
      params(
        path: ::String,
        check_type: T.nilable(::String),
        check_access: T.nilable(::String),
        allow_create_dir: T.nilable(T::Boolean),
        check_writable_dir: T.nilable(T::Boolean)
      ).returns(::Octoprint::Util)
    end
    def test_path(path:, check_type: T.unsafe(nil), check_access: T.unsafe(nil), allow_create_dir: T.unsafe(nil), check_writable_dir: T.unsafe(nil)); end

    # Test DNS hostname resolution
    #
    # source://octoprint//lib/octoprint/util.rb#138
    sig { params(name: ::String).returns(::Octoprint::Util) }
    def test_resolution(name:); end

    # Test server connectivity
    #
    # source://octoprint//lib/octoprint/util.rb#124
    sig do
      params(
        host: ::String,
        port: ::Integer,
        protocol: T.nilable(::String),
        timeout: T.nilable(::Float)
      ).returns(::Octoprint::Util)
    end
    def test_server(host:, port:, protocol: T.unsafe(nil), timeout: T.unsafe(nil)); end

    # Test URL connectivity
    #
    # source://octoprint//lib/octoprint/util.rb#92
    sig do
      params(
        url: ::String,
        method: T.nilable(::String),
        timeout: T.nilable(::Integer),
        status: T.nilable(::Integer),
        auth_user: T.nilable(::String),
        auth_pass: T.nilable(::String),
        auth_digest: T.nilable(::String),
        auth_bearer: T.nilable(::String),
        content_type_whitelist: T.nilable(::String),
        content_type_blacklist: T.nilable(::String)
      ).returns(::Octoprint::Util)
    end
    def test_url(url:, method: T.unsafe(nil), timeout: T.unsafe(nil), status: T.unsafe(nil), auth_user: T.unsafe(nil), auth_pass: T.unsafe(nil), auth_digest: T.unsafe(nil), auth_bearer: T.unsafe(nil), content_type_whitelist: T.unsafe(nil), content_type_blacklist: T.unsafe(nil)); end

    private

    # source://octoprint//lib/octoprint/util.rb#105
    def build_url_test_params(url, options); end
  end
end

# This gem's version
#
# source://octoprint//lib/octoprint/version.rb#6
Octoprint::VERSION = T.let(T.unsafe(nil), String)

# source://octoprint//lib/tapioca/dsl/compilers/auto_initializable.rb#4
module Tapioca; end

# source://octoprint//lib/tapioca/dsl/compilers/auto_initializable.rb#5
module Tapioca::Dsl; end

# source://octoprint//lib/tapioca/dsl/compilers/auto_initializable.rb#6
module Tapioca::Dsl::Compilers; end

# Tapioca compiler for classes using AutoInitializable module.
#
# This compiler generates RBI files with proper Sorbet type signatures
# for classes that include the AutoInitializable module, replacing the
# need for dynamic code generation at runtime.
#
# source://octoprint//lib/tapioca/dsl/compilers/auto_initializable.rb#12
class Tapioca::Dsl::Compilers::AutoInitializable < ::Tapioca::Dsl::Compiler
  extend T::Generic

  ConstantType = type_member { { upper: Module } }

  # Generates RBI content for the AutoInitializable class.
  #
  # source://octoprint//lib/tapioca/dsl/compilers/auto_initializable.rb#35
  sig { override.void }
  def decorate; end

  private

  # Generates Sorbet type string for a configuration.
  #
  # source://octoprint//lib/tapioca/dsl/compilers/auto_initializable.rb#55
  def generate_sorbet_type(config); end

  class << self
    # Gather all classes that include AutoInitializable module.
    #
    # source://octoprint//lib/tapioca/dsl/compilers/auto_initializable.rb#17
    sig { override.returns(T::Enumerable[::Module]) }
    def gather_constants; end
  end
end

class Tapioca::Error < ::StandardError; end
