# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `react_on_rails` gem.
# Please instead update this file by running `bin/tapioca gem react_on_rails`.


# source://react_on_rails//lib/react_on_rails/error.rb#3
module ReactOnRails
  class << self
    # source://react_on_rails//lib/react_on_rails/configuration.rb#33
    def configuration; end

    # @yield [configuration]
    #
    # source://react_on_rails//lib/react_on_rails/configuration.rb#24
    def configure; end
  end
end

# source://react_on_rails//lib/react_on_rails/configuration.rb#73
class ReactOnRails::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#134
  def initialize(node_modules_location: T.unsafe(nil), server_bundle_js_file: T.unsafe(nil), prerender: T.unsafe(nil), replay_console: T.unsafe(nil), make_generated_server_bundle_the_entrypoint: T.unsafe(nil), trace: T.unsafe(nil), development_mode: T.unsafe(nil), defer_generated_component_packs: T.unsafe(nil), logging_on_server: T.unsafe(nil), server_renderer_pool_size: T.unsafe(nil), server_renderer_timeout: T.unsafe(nil), raise_on_prerender_error: T.unsafe(nil), skip_display_none: T.unsafe(nil), generated_assets_dirs: T.unsafe(nil), generated_assets_dir: T.unsafe(nil), webpack_generated_files: T.unsafe(nil), rendering_extension: T.unsafe(nil), build_test_command: T.unsafe(nil), build_production_command: T.unsafe(nil), generated_component_packs_loading_strategy: T.unsafe(nil), same_bundle_for_client_and_server: T.unsafe(nil), i18n_dir: T.unsafe(nil), i18n_yml_dir: T.unsafe(nil), i18n_output_format: T.unsafe(nil), i18n_yml_safe_load_options: T.unsafe(nil), random_dom_id: T.unsafe(nil), server_render_method: T.unsafe(nil), rendering_props_extension: T.unsafe(nil), components_subdirectory: T.unsafe(nil), auto_load_bundle: T.unsafe(nil), component_registry_timeout: T.unsafe(nil), server_bundle_output_path: T.unsafe(nil), enforce_private_server_bundles: T.unsafe(nil)); end

  # Returns the value of attribute auto_load_bundle.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def auto_load_bundle; end

  # Sets the attribute auto_load_bundle
  #
  # @param value the value to set the attribute auto_load_bundle to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def auto_load_bundle=(_arg0); end

  # Returns the value of attribute build_production_command.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def build_production_command; end

  # Sets the attribute build_production_command
  #
  # @param value the value to set the attribute build_production_command to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def build_production_command=(_arg0); end

  # Returns the value of attribute build_test_command.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def build_test_command; end

  # Sets the attribute build_test_command
  #
  # @param value the value to set the attribute build_test_command to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def build_test_command=(_arg0); end

  # Returns the value of attribute component_registry_timeout.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def component_registry_timeout; end

  # Sets the attribute component_registry_timeout
  #
  # @param value the value to set the attribute component_registry_timeout to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def component_registry_timeout=(_arg0); end

  # Returns the value of attribute components_subdirectory.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def components_subdirectory; end

  # Sets the attribute components_subdirectory
  #
  # @param value the value to set the attribute components_subdirectory to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def components_subdirectory=(_arg0); end

  # Returns the value of attribute defer_generated_component_packs.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def defer_generated_component_packs; end

  # Sets the attribute defer_generated_component_packs
  #
  # @param value the value to set the attribute defer_generated_component_packs to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def defer_generated_component_packs=(_arg0); end

  # Returns the value of attribute development_mode.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def development_mode; end

  # Sets the attribute development_mode
  #
  # @param value the value to set the attribute development_mode to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def development_mode=(_arg0); end

  # Returns the value of attribute enforce_private_server_bundles.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def enforce_private_server_bundles; end

  # Sets the attribute enforce_private_server_bundles
  #
  # @param value the value to set the attribute enforce_private_server_bundles to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def enforce_private_server_bundles=(_arg0); end

  # Returns the value of attribute generated_assets_dir.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def generated_assets_dir; end

  # Sets the attribute generated_assets_dir
  #
  # @param value the value to set the attribute generated_assets_dir to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def generated_assets_dir=(_arg0); end

  # Returns the value of attribute generated_assets_dirs.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def generated_assets_dirs; end

  # Sets the attribute generated_assets_dirs
  #
  # @param value the value to set the attribute generated_assets_dirs to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def generated_assets_dirs=(_arg0); end

  # Returns the value of attribute generated_component_packs_loading_strategy.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def generated_component_packs_loading_strategy; end

  # Sets the attribute generated_component_packs_loading_strategy
  #
  # @param value the value to set the attribute generated_component_packs_loading_strategy to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def generated_component_packs_loading_strategy=(_arg0); end

  # Returns the value of attribute i18n_dir.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_dir; end

  # Sets the attribute i18n_dir
  #
  # @param value the value to set the attribute i18n_dir to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_dir=(_arg0); end

  # Returns the value of attribute i18n_output_format.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_output_format; end

  # Sets the attribute i18n_output_format
  #
  # @param value the value to set the attribute i18n_output_format to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_output_format=(_arg0); end

  # Returns the value of attribute i18n_yml_dir.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_yml_dir; end

  # Sets the attribute i18n_yml_dir
  #
  # @param value the value to set the attribute i18n_yml_dir to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_yml_dir=(_arg0); end

  # Returns the value of attribute i18n_yml_safe_load_options.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_yml_safe_load_options; end

  # Sets the attribute i18n_yml_safe_load_options
  #
  # @param value the value to set the attribute i18n_yml_safe_load_options to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def i18n_yml_safe_load_options=(_arg0); end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#115
  def immediate_hydration; end

  # Deprecated: immediate_hydration configuration has been removed
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#98
  def immediate_hydration=(value); end

  # Returns the value of attribute logging_on_server.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def logging_on_server; end

  # Sets the attribute logging_on_server
  #
  # @param value the value to set the attribute logging_on_server to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def logging_on_server=(_arg0); end

  # Returns the value of attribute make_generated_server_bundle_the_entrypoint.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def make_generated_server_bundle_the_entrypoint; end

  # Sets the attribute make_generated_server_bundle_the_entrypoint
  #
  # @param value the value to set the attribute make_generated_server_bundle_the_entrypoint to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def make_generated_server_bundle_the_entrypoint=(_arg0); end

  # Returns the value of attribute node_modules_location.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def node_modules_location; end

  # Sets the attribute node_modules_location
  #
  # @param value the value to set the attribute node_modules_location to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def node_modules_location=(_arg0); end

  # Returns the value of attribute prerender.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def prerender; end

  # Sets the attribute prerender
  #
  # @param value the value to set the attribute prerender to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def prerender=(_arg0); end

  # Returns the value of attribute raise_on_prerender_error.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def raise_on_prerender_error; end

  # Sets the attribute raise_on_prerender_error
  #
  # @param value the value to set the attribute raise_on_prerender_error to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def raise_on_prerender_error=(_arg0); end

  # Returns the value of attribute random_dom_id.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def random_dom_id; end

  # Sets the attribute random_dom_id
  #
  # @param value the value to set the attribute random_dom_id to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def random_dom_id=(_arg0); end

  # Returns the value of attribute rendering_extension.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def rendering_extension; end

  # Sets the attribute rendering_extension
  #
  # @param value the value to set the attribute rendering_extension to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def rendering_extension=(_arg0); end

  # Returns the value of attribute rendering_props_extension.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def rendering_props_extension; end

  # Sets the attribute rendering_props_extension
  #
  # @param value the value to set the attribute rendering_props_extension to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def rendering_props_extension=(_arg0); end

  # Returns the value of attribute replay_console.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def replay_console; end

  # Sets the attribute replay_console
  #
  # @param value the value to set the attribute replay_console to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def replay_console=(_arg0); end

  # Returns the value of attribute same_bundle_for_client_and_server.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def same_bundle_for_client_and_server; end

  # Sets the attribute same_bundle_for_client_and_server
  #
  # @param value the value to set the attribute same_bundle_for_client_and_server to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def same_bundle_for_client_and_server=(_arg0); end

  # Returns the value of attribute server_bundle_js_file.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_bundle_js_file; end

  # Sets the attribute server_bundle_js_file
  #
  # @param value the value to set the attribute server_bundle_js_file to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_bundle_js_file=(_arg0); end

  # Returns the value of attribute server_bundle_output_path.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_bundle_output_path; end

  # Sets the attribute server_bundle_output_path
  #
  # @param value the value to set the attribute server_bundle_output_path to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_bundle_output_path=(_arg0); end

  # Returns the value of attribute server_render_method.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_render_method; end

  # Sets the attribute server_render_method
  #
  # @param value the value to set the attribute server_render_method to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_render_method=(_arg0); end

  # Returns the value of attribute server_renderer_pool_size.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_renderer_pool_size; end

  # Sets the attribute server_renderer_pool_size
  #
  # @param value the value to set the attribute server_renderer_pool_size to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_renderer_pool_size=(_arg0); end

  # Returns the value of attribute server_renderer_timeout.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_renderer_timeout; end

  # Sets the attribute server_renderer_timeout
  #
  # @param value the value to set the attribute server_renderer_timeout to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def server_renderer_timeout=(_arg0); end

  # on ReactOnRails
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#194
  def setup_config_values; end

  # Returns the value of attribute skip_display_none.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def skip_display_none; end

  # Sets the attribute skip_display_none
  #
  # @param value the value to set the attribute skip_display_none to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def skip_display_none=(_arg0); end

  # Returns the value of attribute trace.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def trace; end

  # Sets the attribute trace
  #
  # @param value the value to set the attribute trace to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def trace=(_arg0); end

  # Returns the value of attribute webpack_generated_files.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def webpack_generated_files; end

  # Sets the attribute webpack_generated_files
  #
  # @param value the value to set the attribute webpack_generated_files to.
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#74
  def webpack_generated_files=(_arg0); end

  private

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#344
  def adjust_precompile_task; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#324
  def apply_shakapacker_private_output_path(relative_path); end

  # Auto-detect server_bundle_output_path from Shakapacker 9.0+ private_output_path
  # Checks if user explicitly set a value and warns them to use auto-detection instead
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#282
  def auto_detect_server_bundle_path_from_shakapacker; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#336
  def check_autobundling_requirements; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#211
  def check_component_registry_timeout; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#331
  def check_minimum_shakapacker_version; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#402
  def check_server_render_method_is_only_execjs; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#467
  def compile_command_conflict_message; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#414
  def configure_generated_assets_dirs_deprecation; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#451
  def configure_skip_display_none_deprecation; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#431
  def ensure_webpack_generated_files_exists; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#381
  def error_if_using_packer_and_generated_assets_dir_not_match_public_output_path; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#457
  def raise_missing_components_subdirectory; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#256
  def validate_enforce_private_server_bundles; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/configuration.rb#220
  def validate_generated_component_packs_loading_strategy; end

  # source://react_on_rails//lib/react_on_rails/configuration.rb#308
  def warn_about_explicit_configuration(shakapacker_path); end

  class << self
    # Returns the value of attribute immediate_hydration_mutex.
    #
    # source://react_on_rails//lib/react_on_rails/configuration.rb#94
    def immediate_hydration_mutex; end

    # Sets the attribute immediate_hydration_mutex
    #
    # @param value the value to set the attribute immediate_hydration_mutex to.
    #
    # source://react_on_rails//lib/react_on_rails/configuration.rb#94
    def immediate_hydration_mutex=(_arg0); end

    # Returns the value of attribute immediate_hydration_warned.
    #
    # source://react_on_rails//lib/react_on_rails/configuration.rb#94
    def immediate_hydration_warned; end

    # Sets the attribute immediate_hydration_warned
    #
    # @param value the value to set the attribute immediate_hydration_warned to.
    #
    # source://react_on_rails//lib/react_on_rails/configuration.rb#94
    def immediate_hydration_warned=(_arg0); end
  end
end

# source://react_on_rails//lib/react_on_rails/controller.rb#4
module ReactOnRails::Controller
  # source://react_on_rails//lib/react_on_rails/controller.rb#17
  def redux_store(store_name, props: T.unsafe(nil), immediate_hydration: T.unsafe(nil)); end
end

# source://react_on_rails//lib/react_on_rails/configuration.rb#30
ReactOnRails::DEFAULT_COMPONENT_REGISTRY_TIMEOUT = T.let(T.unsafe(nil), Integer)

# source://react_on_rails//lib/react_on_rails/configuration.rb#29
ReactOnRails::DEFAULT_GENERATED_ASSETS_DIR = T.let(T.unsafe(nil), String)

# source://react_on_rails//lib/react_on_rails/configuration.rb#31
ReactOnRails::DEFAULT_SERVER_BUNDLE_OUTPUT_PATH = T.let(T.unsafe(nil), String)

# source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#8
module ReactOnRails::Dev; end

# source://react_on_rails//lib/react_on_rails/dev/file_manager.rb#5
class ReactOnRails::Dev::FileManager
  class << self
    # source://react_on_rails//lib/react_on_rails/dev/file_manager.rb#7
    def cleanup_stale_files; end

    private

    # source://react_on_rails//lib/react_on_rails/dev/file_manager.rb#16
    def cleanup_overmind_sockets; end

    # source://react_on_rails//lib/react_on_rails/dev/file_manager.rb#29
    def cleanup_rails_pid_file; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/file_manager.rb#51
    def overmind_running?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/file_manager.rb#55
    def process_running?(pid); end

    # source://react_on_rails//lib/react_on_rails/dev/file_manager.rb#66
    def remove_file_if_exists(file_path, description); end
  end
end

# PackGenerator triggers the generation of React on Rails packs
#
# Design decisions:
# 1. Why trigger via Rake task instead of direct Ruby code?
#    - The actual pack generation logic lives in lib/react_on_rails/packs_generator.rb
#    - The rake task (lib/tasks/generate_packs.rake) provides a stable, documented interface
#    - This allows the implementation to evolve without breaking bin/dev
#    - Users can also run the task directly: `rake react_on_rails:generate_packs`
#
# 2. Why two execution strategies (direct vs bundle exec)?
#    - Direct Rake execution: Faster when already in Bundler/Rails context (bin/dev)
#    - Bundle exec fallback: Required when called outside Rails context
#    - This optimization avoids subprocess overhead in the common case
#
# 3. Why is the class named "PackGenerator" when it delegates?
#    - It's a semantic wrapper around pack generation for the dev workflow
#    - Provides a clean API for bin/dev without exposing Rake internals
#    - Handles hook detection, error handling, and output formatting
#
# source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#27
class ReactOnRails::Dev::PackGenerator
  class << self
    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#29
    def generate(verbose: T.unsafe(nil)); end

    private

    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#126
    def capture_output(silent); end

    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#143
    def handle_rake_error(error, _silent); end

    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#114
    def load_rake_tasks; end

    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#120
    def prepare_rake_task; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#86
    def rails_available?; end

    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#61
    def run_pack_generation(silent: T.unsafe(nil), verbose: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#99
    def run_rake_task_directly(silent: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#154
    def run_via_bundle_exec(silent: T.unsafe(nil), verbose: T.unsafe(nil)); end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#77
    def should_run_directly?; end

    # DRY helper method for Bundler context switching with API compatibility
    # Supports both new (with_unbundled_env) and legacy (with_clean_env) Bundler APIs
    #
    # source://react_on_rails//lib/react_on_rails/dev/pack_generator.rb#176
    def with_unbundled_context(&block); end
  end
end

# source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#7
class ReactOnRails::Dev::ProcessManager
  class << self
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#18
    def ensure_procfile(procfile); end

    # Check if a process is available and usable in the current execution context
    # This accounts for bundler context where system commands might be intercepted
    #
    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#14
    def installed?(process); end

    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#28
    def run_with_process_manager(procfile); end

    private

    # Check if a process is actually usable in the current execution context
    # This is important for commands that might be intercepted by bundler
    #
    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#61
    def installed_in_current_context?(process); end

    # Check if a process is available system-wide (outside bundle context)
    #
    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#116
    def process_available_in_system?(process); end

    # Try to run a process if it's available, with intelligent fallback strategy
    # Returns:
    #   - true if process ran and exited successfully (exit code 0)
    #   - false if process ran but exited with error (non-zero exit code)
    #   - nil if process was not found/available
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#91
    def run_process_if_available(process, args); end

    # Run a process outside of bundler context
    # This allows using system-installed processes even when they're not in the Gemfile
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#104
    def run_process_outside_bundle(process, args); end

    # Improved error message with helpful guidance
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#146
    def show_process_manager_installation_help; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#171
    def valid_procfile_path?(procfile); end

    # Get appropriate version flags for different processes
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#75
    def version_flags_for(process); end

    # DRY helper method for Bundler context switching with API compatibility
    # Supports both new (with_unbundled_env) and legacy (with_clean_env) Bundler APIs
    #
    # source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#134
    def with_unbundled_context(&block); end
  end
end

# Timeout for version check operations to prevent hanging
#
# source://react_on_rails//lib/react_on_rails/dev/process_manager.rb#9
ReactOnRails::Dev::ProcessManager::VERSION_CHECK_TIMEOUT = T.let(T.unsafe(nil), Integer)

# source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#11
class ReactOnRails::Dev::ServerManager
  class << self
    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#110
    def cleanup_socket_files; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#39
    def development_processes; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#102
    def find_port_pids(port); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#66
    def find_process_pids(pattern); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#87
    def kill_port_processes(ports); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#30
    def kill_processes; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#51
    def kill_running_processes; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#127
    def print_kill_summary(killed_any); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#152
    def run_from_command_line(args = T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#137
    def show_help; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#15
    def start(mode = T.unsafe(nil), procfile = T.unsafe(nil), verbose: T.unsafe(nil), route: T.unsafe(nil), rails_env: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#74
    def terminate_processes(pids); end

    private

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#608
    def box_border(width); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#612
    def box_bottom(width); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#616
    def box_empty_line(width); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#620
    def format_box_line(content, box_width); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#246
    def handle_precompile_hook_failure(hook_value, stdout, stderr); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#299
    def help_commands; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#335
    def help_customization; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#365
    def help_mode_details; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#319
    def help_options; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#629
    def help_troubleshooting; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#294
    def help_usage; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#586
    def print_procfile_info(procfile, route: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#576
    def print_server_info(title, features, port = T.unsafe(nil), route: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#604
    def procfile_port(procfile); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#565
    def run_development(procfile, verbose: T.unsafe(nil), route: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#218
    def run_precompile_hook_if_present; end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#399
    def run_production_like(_verbose: T.unsafe(nil), route: T.unsafe(nil), rails_env: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#536
    def run_static_development(procfile, verbose: T.unsafe(nil), route: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#270
    def warn_if_shakapacker_version_too_old; end
  end
end

# source://react_on_rails//lib/react_on_rails/dev/server_manager.rb#12
ReactOnRails::Dev::ServerManager::HELP_FLAGS = T.let(T.unsafe(nil), Array)

# ServiceChecker validates that required external services are running
# before starting the development server.
#
# Configuration is read from .dev-services.yml in the app root:
#
# services:
#   redis:
#     check_command: "redis-cli ping"
#     expected_output: "PONG"
#     start_command: "redis-server"
#     description: "Redis (for caching and background jobs)"
#   postgresql:
#     check_command: "pg_isready"
#     expected_output: "accepting connections"
#     start_command: "pg_ctl -D /usr/local/var/postgres start"
#     description: "PostgreSQL database"
#
# source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#26
class ReactOnRails::Dev::ServiceChecker
  class << self
    # Check all required services and provide helpful output
    #
    # @param config_path [String] Path to .dev-services.yml (default: ./.dev-services.yml)
    # @return [Boolean] true if all services are running or no config exists
    #
    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#42
    def check_services(config_path: T.unsafe(nil)); end

    private

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#59
    def check_and_report_services(config, config_path); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#101
    def check_service(_name, config); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#67
    def collect_service_failures(services); end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#53
    def config_has_services?(config); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#92
    def load_config(config_path); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#154
    def print_all_services_ok; end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#161
    def print_failures_summary(failures); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#149
    def print_service_failed(name, description); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#144
    def print_service_ok(name, description); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#138
    def print_services_header(config_path); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#82
    def report_results(failures); end

    # source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#117
    def run_check_command(command); end
  end
end

# Configuration file keys
#
# source://react_on_rails//lib/react_on_rails/dev/service_checker.rb#28
ReactOnRails::Dev::ServiceChecker::CONFIG_KEYS = T.let(T.unsafe(nil), Hash)

# source://react_on_rails//lib/react_on_rails/engine.rb#6
class ReactOnRails::Engine < ::Rails::Engine
  class << self
    # Check if package.json doesn't exist yet
    #
    # @return [Boolean] true if package.json is missing
    #
    # source://react_on_rails//lib/react_on_rails/engine.rb#78
    def package_json_missing?; end

    # Check if we're running a Rails generator
    #
    # @return [Boolean] true if running a generator
    #
    # source://react_on_rails//lib/react_on_rails/engine.rb#72
    def running_generator?; end

    # Determine if version validation should be skipped
    #
    # This method checks multiple conditions to determine if package version validation
    # should be skipped. Validation is skipped during setup scenarios where the npm
    # package isn't installed yet (e.g., during generator execution).
    #
    # @example Testing with parallel processes
    #   # In RSpec configuration:
    #   config.before(:each) do |example|
    #   ENV.delete("REACT_ON_RAILS_SKIP_VALIDATION")
    #   end
    # @note Thread Safety: ENV variables are process-global. In practice, Rails generators
    #   run in a single process, so concurrent execution is not a concern. If running
    #   generators concurrently (e.g., in parallel tests), ensure tests run in separate
    #   processes to avoid ENV variable conflicts.
    # @note Manual ENV Setting: While this ENV variable is designed to be set by generators,
    #   users can manually set it (e.g., `REACT_ON_RAILS_SKIP_VALIDATION=true rails server`)
    #   to bypass validation. This should only be done temporarily during debugging or
    #   setup scenarios. The validation helps catch version mismatches early, so bypassing
    #   it in production is not recommended.
    # @return [Boolean] true if validation should be skipped
    #
    # source://react_on_rails//lib/react_on_rails/engine.rb#44
    def skip_version_validation?; end
  end
end

# source://react_on_rails//lib/react_on_rails/error.rb#4
class ReactOnRails::Error < ::StandardError; end

# source://react_on_rails//lib/react_on_rails/git_utils.rb#6
module ReactOnRails::GitUtils
  class << self
    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/git_utils.rb#7
    def uncommitted_changes?(message_handler, git_installed: T.unsafe(nil)); end
  end
end

# source://react_on_rails//lib/react_on_rails/helper.rb#18
module ReactOnRails::Helper
  include ::ReactOnRails::Utils::Required
  include ::ReactOnRails::ProHelper

  # source://react_on_rails//lib/react_on_rails/helper.rb#406
  def build_react_component_result_for_server_rendered_hash(server_rendered_html: T.unsafe(nil), component_specification_tag: T.unsafe(nil), console_script: T.unsafe(nil), render_options: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#379
  def build_react_component_result_for_server_rendered_string(server_rendered_html: T.unsafe(nil), component_specification_tag: T.unsafe(nil), console_script: T.unsafe(nil), render_options: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#466
  def compose_react_component_html_with_spec_and_console(component_specification_tag, rendered_output, console_script); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#365
  def create_render_options(react_component_name, options); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#375
  def generated_components_pack_path(component_name); end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#663
  def in_mailer?; end

  # source://react_on_rails//lib/react_on_rails/helper.rb#633
  def initialize_redux_stores(render_options); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#508
  def internal_react_component(react_component_name, options = T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#254
  def json_safe_and_pretty(hash_or_string); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#333
  def load_pack_for_generated_component(react_component_name, render_options); end

  # prepend the rails_context if not yet applied
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#502
  def prepend_render_rails_context(render_value); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#539
  def props_string(props); end

  # This is the definitive list of the default values used for the rails_context, which is the
  # second parameter passed to both component and store Render-Functions.
  # This method can be called from views and from the controller, as `helpers.rails_context`
  #
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#272
  def rails_context(server_side: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#475
  def rails_context_if_not_already_rendered; end

  # @raise [ReactOnRails::SmartError]
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#677
  def raise_missing_autoloaded_bundle(react_component_name); end

  # @raise [ReactOnRails::PrerenderError]
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#543
  def raise_prerender_error(json_result, react_component_name, props, js_code); end

  # react_component_name: can be a React function or class component or a "Render-Function".
  # "Render-Functions" differ from a React function in that they take two parameters, the
  #   props and the railsContext, like this:
  #
  #   let MyReactComponentApp = (props, railsContext) => <MyReactComponent {...props}/>;
  #
  #   Alternately, you can define the Render-Function with an additional property
  #   `.renderFunction = true`:
  #
  #   let MyReactComponentApp = (props) => <MyReactComponent {...props}/>;
  #   MyReactComponent.renderFunction = true;
  #
  #   Exposing the react_component_name is necessary to both a plain ReactComponent as well as
  #     a generator:
  #   See README.md for how to "register" your React components.
  #   See spec/dummy/client/app/packs/server-bundle.js and
  #     spec/dummy/client/app/packs/client-bundle.js for examples of this.
  #
  # options:
  #   props: Ruby Hash or JSON string which contains the properties to pass to the react object. Do
  #      not pass any props if you are separately initializing the store by the `redux_store` helper.
  #   prerender: <true/false> set to false when debugging!
  #   id: You can optionally set the id, or else a unique one is automatically generated.
  #   html_options: You can set other html attributes that will go on this component
  #   trace: <true/false> set to true to print additional debugging information in the browser
  #          default is true for development, off otherwise
  #   replay_console: <true/false> Default is true. False will disable echoing server rendering
  #                   logs to browser. While this can make troubleshooting server rendering difficult,
  #                   so long as you have the default configuration of logging_on_server set to
  #                   true, you'll still see the errors on the server.
  #   raise_on_prerender_error: <true/false> Default to false. True will raise exception on server
  #      if the JS code throws
  # Any other options are passed to the content tag, including the id.
  # random_dom_id can be set to override the default from the config/initializers. That's only
  # used if you have multiple instance of the same component on the Rails view.
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#59
  def react_component(component_name, options = T.unsafe(nil)); end

  # react_component_hash is used to return multiple HTML strings for server rendering, such as for
  # adding meta-tags to a page.
  # It is exactly like react_component except for the following:
  # 1. prerender: true is automatically added, as this method doesn't make sense for client only
  #    rendering.
  # 2. Your JavaScript Render-Function for server rendering must return an Object rather than a React component.
  # 3. Your view code must expect an object and not a string.
  #
  # Here is an example of the view code:
  #    <% react_helmet_app = react_component_hash("ReactHelmetApp", prerender: true,
  #                                               props: { helloWorldData: { name: "Mr. Server Side Rendering"}},
  #                                               id: "react-helmet-0", trace: true) %>
  #    <% content_for :title do %>
  #      <%= react_helmet_app['title'] %>
  #    <% end %>
  #    <%= react_helmet_app["componentHtml"] %>
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#115
  def react_component_hash(component_name, options = T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#493
  def react_on_rails_attribution_comment; end

  # source://react_on_rails//lib/react_on_rails/helper.rb#160
  def redux_store(store_name, props: T.unsafe(nil), defer: T.unsafe(nil), immediate_hydration: T.unsafe(nil)); end

  # Place this view helper (no parameters) at the end of your shared layout. This tell
  # ReactOnRails where to client render the redux store hydration data. Since we're going
  # to be setting up the stores in the controllers, we need to know where on the view to put the
  # client side rendering of this hydration data, which is a hidden div with a matching class
  # that contains a data props.
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#182
  def redux_store_hydration_data; end

  # source://react_on_rails//lib/react_on_rails/helper.rb#353
  def registered_stores; end

  # source://react_on_rails//lib/react_on_rails/helper.rb#357
  def registered_stores_defer_render; end

  # source://react_on_rails//lib/react_on_rails/helper.rb#361
  def registered_stores_including_deferred; end

  # source://react_on_rails//lib/react_on_rails/helper.rb#533
  def render_redux_store_data(redux_store_data); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#659
  def replay_console_option(val); end

  # source://react_on_rails//lib/react_on_rails/helper.rb#190
  def sanitized_props_string(props); end

  # Helper method to take javascript expression and returns the output from evaluating it.
  # If you have more than one line that needs to be executed, wrap it in an IIFE.
  # JS exceptions are caught and console messages are handled properly.
  # Options include:{ prerender:, trace:, raise_on_prerender_error:, throw_js_errors: }
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#198
  def server_render_js(js_expression, options = T.unsafe(nil)); end

  # Returns object with values that are NOT html_safe!
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#563
  def server_rendered_react_component(render_options); end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#553
  def should_raise_streaming_prerender_error?(chunk_json_result, render_options); end

  # Wraps console replay JavaScript code in a script tag with CSP nonce if available.
  # The console_script_code is already sanitized by scriptSanitizedVal() in the JavaScript layer,
  # so using html_safe here is secure.
  #
  # source://react_on_rails//lib/react_on_rails/helper.rb#443
  def wrap_console_script_with_nonce(console_script_code); end
end

# source://react_on_rails//lib/react_on_rails/helper.rb#22
ReactOnRails::Helper::COMPONENT_HTML_KEY = T.let(T.unsafe(nil), String)

# source://react_on_rails//lib/react_on_rails/json_output.rb#6
class ReactOnRails::JsonOutput
  class << self
    # source://react_on_rails//lib/react_on_rails/json_output.rb#7
    def escape(json); end
  end
end

# source://react_on_rails//lib/react_on_rails/json_parse_error.rb#4
class ReactOnRails::JsonParseError < ::ReactOnRails::Error
  # @return [JsonParseError] a new instance of JsonParseError
  #
  # source://react_on_rails//lib/react_on_rails/json_parse_error.rb#7
  def initialize(parse_error:, json:); end

  # Returns the value of attribute json.
  #
  # source://react_on_rails//lib/react_on_rails/json_parse_error.rb#5
  def json; end

  # source://react_on_rails//lib/react_on_rails/json_parse_error.rb#22
  def raven_context; end

  # source://react_on_rails//lib/react_on_rails/json_parse_error.rb#26
  def to_error_context; end

  # source://react_on_rails//lib/react_on_rails/json_parse_error.rb#18
  def to_honeybadger_context; end
end

# source://react_on_rails//lib/react_on_rails/locales/base.rb#6
module ReactOnRails::Locales
  class << self
    # source://react_on_rails//lib/react_on_rails/locales/base.rb#7
    def compile(force: T.unsafe(nil)); end

    private

    # @raise [ReactOnRails::Error]
    #
    # source://react_on_rails//lib/react_on_rails/locales/base.rb#24
    def check_config_directory_exists(directory:, key_name:, remove_if:); end
  end
end

# source://react_on_rails//lib/react_on_rails/locales/base.rb#38
class ReactOnRails::Locales::Base
  # @return [Base] a new instance of Base
  #
  # source://react_on_rails//lib/react_on_rails/locales/base.rb#39
  def initialize(force: T.unsafe(nil)); end

  private

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#113
  def convert; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#109
  def default_locale; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#69
  def exist_files; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#87
  def file(name); end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#60
  def file_format; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#79
  def file_names; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#83
  def files; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#73
  def files_are_outdated; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#156
  def flatten(translations); end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#149
  def flatten_defaults(val); end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#145
  def format(input); end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#121
  def generate_file(template, path); end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#126
  def generate_translations; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#101
  def i18n_dir; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#105
  def i18n_yml_dir; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#91
  def locale_files; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/locales/base.rb#62
  def obsolete?; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#174
  def template_default; end

  # source://react_on_rails//lib/react_on_rails/locales/base.rb#168
  def template_translations; end
end

# source://react_on_rails//lib/react_on_rails/locales/to_js.rb#7
class ReactOnRails::Locales::ToJs < ::ReactOnRails::Locales::Base
  private

  # source://react_on_rails//lib/react_on_rails/locales/to_js.rb#10
  def file_format; end

  # source://react_on_rails//lib/react_on_rails/locales/to_js.rb#20
  def template_default; end

  # source://react_on_rails//lib/react_on_rails/locales/to_js.rb#14
  def template_translations; end
end

# source://react_on_rails//lib/react_on_rails/locales/to_json.rb#7
class ReactOnRails::Locales::ToJson < ::ReactOnRails::Locales::Base
  private

  # source://react_on_rails//lib/react_on_rails/locales/to_json.rb#10
  def file_format; end

  # source://react_on_rails//lib/react_on_rails/locales/to_json.rb#18
  def template_default; end

  # source://react_on_rails//lib/react_on_rails/locales/to_json.rb#14
  def template_translations; end
end

# source://react_on_rails//lib/react_on_rails/packer_utils.rb#6
module ReactOnRails::PackerUtils
  class << self
    # The function doesn't ensure that the asset exists.
    # - It just returns url to the asset if dev server is running
    # - Otherwise it returns file path to the asset
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#80
    def asset_uri_from_packer(asset_name); end

    # This returns either a URL for the webpack-dev-server, non-server bundle or
    # the hashed server bundle if using the same bundle for the client.
    # Otherwise returns a file path.
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#51
    def bundle_js_uri_from_packer(bundle_name); end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#116
    def check_manifest_not_cached; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#7
    def dev_server_running?; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#11
    def dev_server_url; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#194
    def extract_precompile_hook; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#204
    def hook_contains_generate_packs?(hook_value); end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#108
    def manifest_exists?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#100
    def nested_entries?; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#104
    def packer_public_output_path; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#96
    def packer_source_entry_path; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#92
    def packer_source_path; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#112
    def packer_source_path_explicit?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#88
    def precompile?; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#73
    def public_output_uri_path; end

    # @raise [ReactOnRails::Error]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#140
    def raise_nested_entries_disabled; end

    # @raise [ReactOnRails::Error]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#150
    def raise_shakapacker_version_incompatible_for_autobundling; end

    # @raise [ReactOnRails::Error]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#161
    def raise_shakapacker_version_incompatible_for_basic_pack_generation; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#225
    def resolve_hook_script_path(hook_value); end

    # Check if shakapacker.yml has a precompile hook configured
    # This prevents react_on_rails from running generate_packs twice
    #
    # Returns false if detection fails for any reason (missing shakapacker, malformed config, etc.)
    # to ensure generate_packs runs rather than being incorrectly skipped
    #
    # Note: Currently checks a single hook value. Future enhancement will support hook lists
    # to allow prepending/appending multiple commands. See related Shakapacker issue for details.
    #
    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#178
    def shakapacker_precompile_hook_configured?; end

    # Returns the configured precompile hook value for logging/debugging
    # Returns nil if no hook is configured
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#235
    def shakapacker_precompile_hook_value; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#15
    def shakapacker_version; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#21
    def shakapacker_version_as_array; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#30
    def shakapacker_version_requirement_met?(required_version); end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#35
    def supports_async_loading?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#43
    def supports_autobundling?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#39
    def supports_basic_pack_generation?; end

    # source://react_on_rails//lib/react_on_rails/packer_utils.rb#128
    def webpack_assets_status_checker; end
  end
end

# source://react_on_rails//lib/react_on_rails/packs_generator.rb#8
class ReactOnRails::PacksGenerator
  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#25
  def generate_packs_if_stale; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#19
  def react_on_rails_npm_package; end

  private

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#175
  def add_generated_pack_to_server_bundle; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#218
  def build_expected_files_set; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#138
  def build_server_pack_content(component_on_server_imports, server_components, client_components); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#296
  def clean_directory_with_feedback(dir_path, verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#277
  def clean_generated_directories_with_feedback(verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#205
  def clean_non_generated_files_with_feedback(verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#230
  def clean_unexpected_files_from_directory(dir_path, expected_files, verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#381
  def client_component_to_path; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#103
  def client_entrypoint?(file_path); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#375
  def common_component_to_path; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#361
  def component_name(file_path); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#367
  def component_name_to_path(paths); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#407
  def components_search_path; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#317
  def create_directory_with_feedback(dir_path, verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#57
  def create_pack(file_path, verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#131
  def create_server_pack(verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#255
  def delete_unexpected_files(unexpected_files, dir_path, verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#267
  def display_cleanup_summary(total_deleted, verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#371
  def filter_component_files(paths); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#245
  def find_unexpected_files(existing_files, dir_path, expected_files); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#66
  def first_js_statement_in_code(content); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#50
  def generate_packs(verbose: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#357
  def generated_pack_path(file_path); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#328
  def generated_packs_directory_path; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#334
  def generated_server_bundle_directory_path; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#193
  def generated_server_bundle_file_path; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#155
  def generated_server_pack_file_content; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#109
  def pack_file_contents(file_path); end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#413
  def raise_client_component_overrides_common(component_name); end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#433
  def raise_missing_client_component(component_name); end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#423
  def raise_server_component_overrides_common(component_name); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#341
  def relative_component_path_from_generated_pack(ror_component_path); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#349
  def relative_path(from, to); end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#323
  def server_bundle_entrypoint; end

  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#392
  def server_component_to_path; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/packs_generator.rb#442
  def stale_or_missing_packs?; end

  class << self
    # source://react_on_rails//lib/react_on_rails/packs_generator.rb#15
    def instance; end
  end
end

# source://react_on_rails//lib/react_on_rails/packs_generator.rb#10
ReactOnRails::PacksGenerator::COMPONENT_EXTENSIONS = T.let(T.unsafe(nil), Regexp)

# source://react_on_rails//lib/react_on_rails/packs_generator.rb#9
ReactOnRails::PacksGenerator::CONTAINS_CLIENT_OR_SERVER_REGEX = T.let(T.unsafe(nil), Regexp)

# source://react_on_rails//lib/react_on_rails/packs_generator.rb#11
ReactOnRails::PacksGenerator::MINIMUM_SHAKAPACKER_VERSION = T.let(T.unsafe(nil), String)

# Auto-registration requires nested_entries support which was added in 7.0.0
#
# source://react_on_rails//lib/react_on_rails/packs_generator.rb#13
ReactOnRails::PacksGenerator::MINIMUM_SHAKAPACKER_VERSION_FOR_AUTO_BUNDLING = T.let(T.unsafe(nil), String)

# source://react_on_rails//lib/react_on_rails/prerender_error.rb#7
class ReactOnRails::PrerenderError < ::ReactOnRails::Error
  # err might be nil if JS caught the error
  #
  # @return [PrerenderError] a new instance of PrerenderError
  #
  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#14
  def initialize(component_name: T.unsafe(nil), err: T.unsafe(nil), props: T.unsafe(nil), js_code: T.unsafe(nil), console_messages: T.unsafe(nil)); end

  # TODO: Consider remove providing original `err` as already have access to `self.cause`
  # http://blog.honeybadger.io/nested-errors-in-ruby-with-exception-cause/
  #
  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#11
  def component_name; end

  # TODO: Consider remove providing original `err` as already have access to `self.cause`
  # http://blog.honeybadger.io/nested-errors-in-ruby-with-exception-cause/
  #
  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#11
  def console_messages; end

  # TODO: Consider remove providing original `err` as already have access to `self.cause`
  # http://blog.honeybadger.io/nested-errors-in-ruby-with-exception-cause/
  #
  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#11
  def err; end

  # TODO: Consider remove providing original `err` as already have access to `self.cause`
  # http://blog.honeybadger.io/nested-errors-in-ruby-with-exception-cause/
  #
  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#11
  def js_code; end

  # TODO: Consider remove providing original `err` as already have access to `self.cause`
  # http://blog.honeybadger.io/nested-errors-in-ruby-with-exception-cause/
  #
  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#11
  def props; end

  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#31
  def raven_context; end

  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#35
  def to_error_context; end

  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#27
  def to_honeybadger_context; end

  private

  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#99
  def build_troubleshooting_suggestions(component_name, err, console_messages); end

  # source://react_on_rails//lib/react_on_rails/prerender_error.rb#51
  def calc_message(component_name, console_messages, err, js_code, props); end
end

# source://react_on_rails//lib/react_on_rails/prerender_error.rb#8
ReactOnRails::PrerenderError::MAX_ERROR_SNIPPET_TO_LOG = T.let(T.unsafe(nil), Integer)

# source://react_on_rails//lib/react_on_rails/pro_helper.rb#4
module ReactOnRails::ProHelper
  # Generates the complete component specification script tag.
  # Handles both immediate hydration (Pro feature) and standard cases.
  #
  # source://react_on_rails//lib/react_on_rails/pro_helper.rb#7
  def generate_component_script(render_options); end

  # Generates the complete store hydration script tag.
  # Handles both immediate hydration (Pro feature) and standard cases.
  #
  # source://react_on_rails//lib/react_on_rails/pro_helper.rb#40
  def generate_store_script(redux_store_data); end
end

# source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#6
module ReactOnRails::ReactComponent; end

# source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#7
class ReactOnRails::ReactComponent::RenderOptions
  include ::ReactOnRails::Utils::Required

  # TODO: remove the required for named params
  #
  # @return [RenderOptions] a new instance of RenderOptions
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#15
  def initialize(react_component_name: T.unsafe(nil), options: T.unsafe(nil)); end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#74
  def auto_load_bundle; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#30
  def client_props; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#48
  def dom_id; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#66
  def html_options; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#137
  def html_streaming?; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#98
  def immediate_hydration; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#110
  def internal_option(key); end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#94
  def logging_on_server; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#70
  def prerender; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#26
  def props; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#90
  def raise_non_shell_server_rendering_errors; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#86
  def raise_on_prerender_error; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#44
  def random_dom_id; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#58
  def random_dom_id?; end

  # Returns the value of attribute react_component_name.
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#20
  def react_component_name; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#118
  def render_mode; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#82
  def replay_console; end

  # Returns the value of attribute request_digest.
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#10
  def request_digest; end

  # Sets the attribute request_digest
  #
  # @param value the value to set the attribute request_digest to.
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#10
  def request_digest=(_arg0); end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#132
  def rsc_payload_streaming?; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#114
  def set_option(key, value); end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#142
  def store_dependencies; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#127
  def streaming?; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#22
  def throw_js_errors; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#106
  def to_s; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#78
  def trace; end

  private

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#154
  def base_dom_id; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#158
  def generate_unique_dom_id; end

  # Returns the value of attribute options.
  #
  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#152
  def options; end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#162
  def retrieve_configuration_value_for(key); end

  # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#168
  def retrieve_react_on_rails_pro_config_value_for(key); end

  class << self
    # source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#146
    def generate_request_id; end
  end
end

# source://react_on_rails//lib/react_on_rails/react_component/render_options.rb#12
ReactOnRails::ReactComponent::RenderOptions::NO_PROPS = T.let(T.unsafe(nil), Hash)

# source://react_on_rails//lib/react_on_rails/server_rendering_js_code.rb#4
module ReactOnRails::ServerRenderingJsCode
  class << self
    # source://react_on_rails//lib/react_on_rails/server_rendering_js_code.rb#6
    def js_code_renderer; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_js_code.rb#36
    def render(props_string, rails_context, redux_stores, react_component_name, render_options); end

    # source://react_on_rails//lib/react_on_rails/server_rendering_js_code.rb#14
    def server_rendering_component_js_code(props_string: T.unsafe(nil), rails_context: T.unsafe(nil), redux_stores: T.unsafe(nil), react_component_name: T.unsafe(nil), render_options: T.unsafe(nil)); end
  end
end

# source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#7
module ReactOnRails::ServerRenderingPool
  class << self
    # source://react_on_rails//lib/react_on_rails/server_rendering_pool.rb#11
    def pool; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool.rb#19
    def reset_pool(*_arg0, **_arg1, &_arg2); end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool.rb#19
    def reset_pool_if_server_bundle_was_modified(*_arg0, **_arg1, &_arg2); end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool.rb#21
    def server_render_js_with_console_logging(js_code, render_options); end
  end
end

# source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#9
class ReactOnRails::ServerRenderingPool::RubyEmbeddedJavaScript
  class << self
    # Reimplement console methods for replaying on the client
    # Save a handle to the original console if needed.
    #
    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#198
    def console_polyfill; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#127
    def create_js_context; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#107
    def eval_js(js_code, _render_options); end

    # js_code: JavaScript expression that returns a string.
    # render_options: lib/react_on_rails/react_component/render_options.rb
    # Using these options:
    #    trace: saves the executed JS to a file, used in development
    #    logging_on_server: put on server logs, not just in browser console
    #
    # Returns a Hash:
    #   html: string of HTML for direct insertion on the page by evaluating js_code
    #   consoleReplayScript: script for replaying console
    #   hasErrors: true if server rendering errors
    # Note, js_code does not have to be based on React.
    # js_code MUST RETURN json stringify Object
    # Calling code will probably call 'html_safe' on return value before rendering to the view.
    #
    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#52
    def exec_server_render_js(js_code, render_options, js_evaluator = T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#159
    def execjs_timer_polyfills; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#113
    def read_bundle_js_code; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#11
    def reset_pool; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#18
    def reset_pool_if_server_bundle_was_modified; end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#89
    def trace_js_code_used(msg, js_code, file_name = T.unsafe(nil), force: T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#187
    def undefined_for_exec_js_logging(function_name); end

    private

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#222
    def file_url_to_string(url); end

    # source://react_on_rails//lib/react_on_rails/server_rendering_pool/ruby_embedded_java_script.rb#233
    def parse_result_and_replay_console_messages(result_string, render_options); end
  end
end

# SmartError provides enhanced error messages with actionable suggestions
#
# source://react_on_rails//lib/react_on_rails/smart_error.rb#8
class ReactOnRails::SmartError < ::ReactOnRails::Error
  # @return [SmartError] a new instance of SmartError
  #
  # source://react_on_rails//lib/react_on_rails/smart_error.rb#11
  def initialize(error_type:, component_name: T.unsafe(nil), props: T.unsafe(nil), js_code: T.unsafe(nil), **additional_context); end

  # Returns the value of attribute additional_context.
  #
  # source://react_on_rails//lib/react_on_rails/smart_error.rb#9
  def additional_context; end

  # Returns the value of attribute component_name.
  #
  # source://react_on_rails//lib/react_on_rails/smart_error.rb#9
  def component_name; end

  # Returns the value of attribute error_type.
  #
  # source://react_on_rails//lib/react_on_rails/smart_error.rb#9
  def error_type; end

  # Returns the value of attribute js_code.
  #
  # source://react_on_rails//lib/react_on_rails/smart_error.rb#9
  def js_code; end

  # Returns the value of attribute props.
  #
  # source://react_on_rails//lib/react_on_rails/smart_error.rb#9
  def props; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#22
  def solution; end

  private

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#271
  def additional_info; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#43
  def build_error_message; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#124
  def component_not_registered_solution; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#245
  def configuration_error_solution; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#261
  def default_solution; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#81
  def error_description; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#61
  def error_type_title; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#295
  def find_similar_components(name); end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#185
  def hydration_mismatch_solution; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#168
  def missing_auto_loaded_bundle_solution; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#229
  def redux_store_not_found_solution; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#209
  def server_rendering_error_solution; end

  # source://react_on_rails//lib/react_on_rails/smart_error.rb#290
  def troubleshooting_section; end
end

# source://react_on_rails//lib/react_on_rails/test_helper.rb#4
module ReactOnRails::TestHelper
  class << self
    # Because you will probably want to run RSpec tests that rely on compiled webpack assets
    # (typically, your integration/feature specs where `js: true`), you will want to ensure you
    # don't accidentally run tests on missing or stale webpack assets. If you did use stale
    # Webpack assets, you will get invalid test results as your tests do not use the very latest
    # JavaScript code.
    #
    # Call this method from inside of the `RSpec.configure` block in your `spec/rails_helper.rb`
    # file, passing the config as an argument. You can customize this to your particular needs by
    # replacing any of the default components.
    #
    # RSpec.configure do |config|
    #   ReactOnRails::TestHelper.configure_rspec_to_compile_assets(config)
    #
    # You can pass an RSpec metatag as an list of parameter to this helper method
    # if you want this helper to run on examples other than where `js: true` or
    # `server_rendering: true` (default). The helper will compile webpack files at most
    # once per test run.
    #
    # If you do not want to be slowed down by re-compiling webpack assets from scratch every test
    # run, you can call `yarn run build:client` (and `yarn run build:server` if doing server
    # rendering) to have webpack recompile these files in the background, which will be *much*
    # faster. The helper looks for these processes and will abort recompiling if it finds them
    # to be running.
    #
    # See docs/additional-reading/rspec-configuration.md for more info
    #
    # Params:
    # config - config for rspec
    # metatags - metatags to add the ensure_assets_compiled check.
    #            Default is :js, :server_rendering, :controller
    #
    # source://react_on_rails//lib/react_on_rails/test_helper.rb#35
    def configure_rspec_to_compile_assets(config, *metatags); end

    # Main entry point to ensuring assets are compiled. See `configure_rspec_to_compile_assets` for
    # an example of usage.
    #
    # Typical usage passes all params as nil defaults.
    # webpack_assets_status_checker: provide: `up_to_date?`, `whats_not_up_to_date`, `source_path`
    #                         defaults to ReactOnRails::TestHelper::WebpackAssetsStatusChecker
    # webpack_assets_compiler: provide one method: `def compile`
    #                         defaults to ReactOnRails::TestHelper::WebpackAssetsCompiler
    # source_path and generated_assets_full_path are passed into the default webpack_assets_status_checker if you
    #                        don't provide one.
    # webpack_generated_files List of files to check for up-to-date-status, defaulting to
    #                        webpack_generated_files in your configuration
    #
    # source://react_on_rails//lib/react_on_rails/test_helper.rb#65
    def ensure_assets_compiled(webpack_assets_status_checker: T.unsafe(nil), webpack_assets_compiler: T.unsafe(nil), source_path: T.unsafe(nil), generated_assets_full_path: T.unsafe(nil), webpack_generated_files: T.unsafe(nil)); end
  end
end

# source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#5
class ReactOnRails::TestHelper::EnsureAssetsCompiled
  # @return [EnsureAssetsCompiled] a new instance of EnsureAssetsCompiled
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#15
  def initialize(webpack_assets_status_checker: T.unsafe(nil), webpack_assets_compiler: T.unsafe(nil)); end

  # Several Scenarios:
  # 1. No webpack watch processes for static assets and files are missing or out of date.
  # 2. Only webpack watch process for server bundle as we're the hot reloading setup.
  # 3. For whatever reason, the watch processes are running, but some clean script removed
  #    the generated bundles.
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#26
  def call; end

  # source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#48
  def puts_start_compile_check_message(stale_files); end

  # Returns the value of attribute webpack_assets_compiler.
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#12
  def webpack_assets_compiler; end

  # Returns the value of attribute webpack_assets_status_checker.
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#12
  def webpack_assets_status_checker; end

  class << self
    # Returns the value of attribute has_been_run.
    #
    # source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#7
    def has_been_run; end

    # Sets the attribute has_been_run
    #
    # @param value the value to set the attribute has_been_run to.
    #
    # source://react_on_rails//lib/react_on_rails/test_helper/ensure_assets_compiled.rb#7
    def has_been_run=(_arg0); end
  end
end

# source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_compiler.rb#7
class ReactOnRails::TestHelper::WebpackAssetsCompiler
  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_compiler.rb#8
  def compile_assets; end
end

# source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#11
class ReactOnRails::TestHelper::WebpackAssetsStatusChecker
  include ::ReactOnRails::Utils::Required

  # @return [WebpackAssetsStatusChecker] a new instance of WebpackAssetsStatusChecker
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#19
  def initialize(generated_assets_full_path: T.unsafe(nil), source_path: T.unsafe(nil), webpack_generated_files: T.unsafe(nil)); end

  # source_path is typically configured in the (shaka/web)packer.yml file
  # for `source_path`
  # or for legacy React on Rails, it's /client, where all client files go
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#17
  def generated_assets_full_path; end

  # source_path is typically configured in the (shaka/web)packer.yml file
  # for `source_path`
  # or for legacy React on Rails, it's /client, where all client files go
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#17
  def source_path; end

  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#33
  def stale_generated_files(files); end

  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#29
  def stale_generated_webpack_files; end

  private

  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#65
  def all_compiled_assets; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#96
  def assets_exist?; end

  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#88
  def client_files; end

  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#100
  def make_file_list(glob); end

  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#92
  def make_globs(dirs); end

  # source://react_on_rails//lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#50
  def resolve_asset_path(bundle_name); end
end

# source://react_on_rails//lib/react_on_rails/utils.rb#12
module ReactOnRails::Utils
  class << self
    # source://react_on_rails//lib/react_on_rails/utils.rb#118
    def bundle_js_file_path(bundle_name); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#501
    def default_troubleshooting_section; end

    # Detects which package manager is being used.
    # First checks the packageManager field in package.json (Node.js Corepack standard),
    # then falls back to checking for lock files.
    #
    # @return [Symbol] The package manager symbol (:npm, :yarn, :pnpm, :bun)
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#335
    def detect_package_manager; end

    # source://react_on_rails//lib/react_on_rails/utils.rb#308
    def find_most_recent_mtime(files); end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#288
    def full_text_errors_enabled?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#242
    def gem_available?(name); end

    # DEPRECATED: Use public_bundles_full_path for clarity about public vs private bundle paths
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#238
    def generated_assets_full_path; end

    # source://react_on_rails//lib/react_on_rails/utils.rb#17
    def immediate_hydration_pro_license_warning(name, type = T.unsafe(nil)); end

    # Invokes command, exiting with a detailed message if there's a failure.
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#89
    def invoke_and_exit_if_failed(cmd, failure_message); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#37
    def normalize_immediate_hydration(value, name, type = T.unsafe(nil)); end

    # Converts an absolute path (String or Pathname) to a path relative to Rails.root.
    # If the path is already relative or doesn't contain Rails.root, returns it as-is.
    #
    # This method is used to normalize paths from Shakapacker's privateOutputPath (which is
    # absolute) to relative paths suitable for React on Rails configuration.
    #
    # Note: Absolute paths that don't start with Rails.root are intentionally passed through
    # unchanged. While there's no known use case for server bundles outside Rails.root,
    # this behavior preserves the original path for debugging and error messages.
    #
    # @example Absolute paths outside Rails.root (edge case)
    #   normalize_to_relative_path("/other/path/bundles") # => "/other/path/bundles"
    # @example Already relative paths pass through
    #   normalize_to_relative_path("ssr-generated")      # => "ssr-generated"
    #   normalize_to_relative_path("./ssr-generated")    # => "./ssr-generated"
    # @example Converting absolute paths within Rails.root
    #   # Assuming Rails.root is "/app"
    #   normalize_to_relative_path("/app/ssr-generated") # => "ssr-generated"
    #   normalize_to_relative_path("/app/foo/bar")       # => "foo/bar"
    # @param path [String, Pathname] The path to normalize
    # @return [String, nil] The relative path as a string, or nil if path is nil
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#473
    def normalize_to_relative_path(path); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#80
    def object_to_boolean(value); end

    # Returns the appropriate install command for the detected package manager.
    # Generates the correct command with exact version syntax.
    #
    # @param package_name [String] The name of the package to install
    # @param version [String] The exact version to install
    # @return [String] The command to run (e.g., "yarn add react-on-rails@16.0.0 --exact")
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#407
    def package_manager_install_exact_command(package_name, version); end

    # Returns the appropriate remove command for the detected package manager.
    #
    # @param package_name [String] The name of the package to remove
    # @return [String] The command to run (e.g., "yarn remove react-on-rails")
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#430
    def package_manager_remove_command(package_name); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#220
    def prepend_cd_node_modules_directory(cmd); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#315
    def prepend_to_file_if_text_not_present(file:, text_to_prepend:, regex:); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#233
    def public_bundles_full_path; end

    # source://react_on_rails//lib/react_on_rails/utils.rb#204
    def rails_version_less_than(version); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#259
    def react_on_rails_pro?; end

    # Return an empty string if React on Rails Pro is not installed
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#270
    def react_on_rails_pro_version; end

    # RSC support detection has been moved to React on Rails Pro
    # See react_on_rails_pro/lib/react_on_rails_pro/utils.rb
    #
    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#282
    def rsc_support_enabled?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#200
    def running_on_windows?; end

    # source://react_on_rails//lib/react_on_rails/utils.rb#193
    def server_bundle_js_file_path; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#114
    def server_bundle_path_is_http?; end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#84
    def server_rendering_is_enabled?; end

    # source://react_on_rails//lib/react_on_rails/utils.rb#292
    def smart_trim(str, max_length = T.unsafe(nil)); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#224
    def source_path; end

    # https://forum.shakacode.com/t/yak-of-the-week-ruby-2-4-pathname-empty-changed-to-look-at-file-size/901
    # return object if truthy, else return nil
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#59
    def truthy_presence(obj); end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#228
    def using_packer_source_path_is_not_defined_and_custom_node_modules?; end

    # Wraps message and makes it colored.
    # Pass in the msg and color as a symbol.
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#69
    def wrap_message(msg, color = T.unsafe(nil)); end

    private

    # source://react_on_rails//lib/react_on_rails/utils.rb#132
    def bundle_js_file_path_with_packer(bundle_name); end

    # source://react_on_rails//lib/react_on_rails/utils.rb#391
    def detect_package_manager_from_lock_files; end

    # source://react_on_rails//lib/react_on_rails/utils.rb#376
    def detect_package_manager_from_package_json; end

    # source://react_on_rails//lib/react_on_rails/utils.rb#170
    def handle_missing_manifest_entry(bundle_name, is_server_bundle); end

    # @return [Boolean]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#156
    def server_bundle?(bundle_name); end

    # Validates package_name and version inputs to prevent command injection
    #
    # @param package_name [String] The package name to validate
    # @param version [String] The version to validate
    # @raise [ReactOnRails::Error] if inputs contain potentially unsafe characters
    # @raise [ReactOnRails::Error]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#362
    def validate_package_command_inputs!(package_name, version); end

    # Validates package_name input to prevent command injection
    #
    # @param package_name [String] The package name to validate
    # @raise [ReactOnRails::Error] if package_name contains potentially unsafe characters
    # @raise [ReactOnRails::Error]
    #
    # source://react_on_rails//lib/react_on_rails/utils.rb#344
    def validate_package_name!(package_name); end
  end
end

# source://react_on_rails//lib/react_on_rails/utils.rb#214
module ReactOnRails::Utils::Required
  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/utils.rb#215
  def required(arg_name); end
end

# source://react_on_rails//lib/react_on_rails/utils.rb#13
ReactOnRails::Utils::TRUNCATION_FILLER = T.let(T.unsafe(nil), String)

# source://react_on_rails//lib/react_on_rails/version.rb#4
ReactOnRails::VERSION = T.let(T.unsafe(nil), String)

# Responsible for checking versions of rubygem versus yarn node package
# against each other at runtime.
#
# source://react_on_rails//lib/react_on_rails/version_checker.rb#6
class ReactOnRails::VersionChecker
  # @return [VersionChecker] a new instance of VersionChecker
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#16
  def initialize(node_package_version); end

  # Returns the value of attribute node_package_version.
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#7
  def node_package_version; end

  # Validates version and package compatibility.
  # Raises ReactOnRails::Error if:
  # - package.json file is not found
  # - Both react-on-rails and react-on-rails-pro packages are installed
  # - Pro gem is installed but using react-on-rails package
  # - Pro package is installed but Pro gem is not installed
  # - Non-exact version is used
  # - Versions don't match
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#28
  def validate_version_and_package_compatibility!; end

  private

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#203
  def gem_version; end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#207
  def gem_version_parts; end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#211
  def package_json_location; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#156
  def validate_exact_version!; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#93
  def validate_no_duplicate_packages!(has_base_package, has_pro_package); end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#60
  def validate_package_gem_compatibility!; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#37
  def validate_package_json_exists!; end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#71
  def validate_packages_installed!(has_base_package, has_pro_package); end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#113
  def validate_pro_gem_uses_pro_package!(is_pro_gem, has_pro_package); end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#132
  def validate_pro_package_has_pro_gem!(is_pro_gem, has_pro_package); end

  # @raise [ReactOnRails::Error]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#180
  def validate_version_match!; end

  class << self
    # source://react_on_rails//lib/react_on_rails/version_checker.rb#12
    def build; end
  end
end

# source://react_on_rails//lib/react_on_rails/version_checker.rb#216
class ReactOnRails::VersionChecker::NodePackageVersion
  # @return [NodePackageVersion] a new instance of NodePackageVersion
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#241
  def initialize(package_json, yarn_lock = T.unsafe(nil), package_lock = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#320
  def local_path_or_url?; end

  # Returns the value of attribute package_json.
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#217
  def package_json; end

  # Returns the value of attribute package_lock.
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#217
  def package_lock; end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#285
  def package_name; end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#327
  def parts; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#312
  def range_operator?; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#316
  def range_syntax?; end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#247
  def raw; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#277
  def react_on_rails_package?; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#281
  def react_on_rails_pro_package?; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#291
  def semver_wildcard?; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#300
  def special_version_string?; end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#304
  def wildcard_or_x_range?; end

  # Returns the value of attribute yarn_lock.
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#217
  def yarn_lock; end

  private

  # Check if a version string represents a local path or URL
  #
  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#363
  def local_path_or_url_version?(version); end

  # @return [Boolean]
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#437
  def package_installed?(package_name); end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#444
  def package_json_contents; end

  # source://react_on_rails//lib/react_on_rails/version_checker.rb#448
  def parsed_package_contents; end

  # Resolve version from lockfiles if available, otherwise use package.json version
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#341
  def resolve_version(package_json_version, package_name); end

  # Parse version from package-lock.json
  # Supports both v1 (dependencies) and v2/v3 (packages) formats
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#408
  def version_from_package_lock(package_name); end

  # Parse version from yarn.lock
  # Looks for entries like:
  #   react-on-rails@^16.1.1:
  #     version "16.1.1"
  # The pattern ensures exact package name match to avoid matching similar names
  # (e.g., "react-on-rails" won't match "react-on-rails-pro")
  #
  # source://react_on_rails//lib/react_on_rails/version_checker.rb#376
  def version_from_yarn_lock(package_name); end

  class << self
    # source://react_on_rails//lib/react_on_rails/version_checker.rb#219
    def build; end

    # source://react_on_rails//lib/react_on_rails/version_checker.rb#223
    def package_json_path; end

    # source://react_on_rails//lib/react_on_rails/version_checker.rb#234
    def package_lock_path; end

    # source://react_on_rails//lib/react_on_rails/version_checker.rb#227
    def yarn_lock_path; end
  end
end

# Semver uses - to separate pre-release, but RubyGems use .
#
# source://react_on_rails//lib/react_on_rails/version_checker.rb#10
ReactOnRails::VersionChecker::VERSION_PARTS_REGEX = T.let(T.unsafe(nil), Regexp)

# source://react_on_rails//lib/react_on_rails/version_syntax_converter.rb#6
class ReactOnRails::VersionSyntaxConverter
  # source://react_on_rails//lib/react_on_rails/version_syntax_converter.rb#14
  def npm_to_rubygem(npm_version); end

  # source://react_on_rails//lib/react_on_rails/version_syntax_converter.rb#7
  def rubygem_to_npm(rubygem_version = T.unsafe(nil)); end
end

module ReactOnRailsHelper
  include ::ReactOnRails::Utils::Required
  include ::ReactOnRails::ProHelper
  include ::ReactOnRails::Helper
end
