# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `shakapacker` gem.
# Please instead update this file by running `bin/tapioca gem shakapacker`.


module ActionController::Base::HelperMethods
  include ::Shakapacker::Helper
end

# = Shakapacker
#
# Shakapacker is a Ruby gem that integrates webpack and rspack with Rails applications,
# providing a modern asset pipeline for JavaScript, CSS, and other web assets.
#
# The main Shakapacker module provides singleton-style access to configuration,
# compilation, and asset manifest functionality. Most methods delegate to a shared
# {Shakapacker::Instance} object.
#
# == Basic Usage
#
#   # Access configuration
#   Shakapacker.config.source_path
#   #=> Pathname("/path/to/app/packs")
#
#   # Check if dev server is running
#   Shakapacker.dev_server.running?
#   #=> true
#
#   # Look up compiled assets
#   Shakapacker.manifest.lookup("application.js")
#   #=> "/packs/application-abc123.js"
#
#   # Compile assets
#   Shakapacker.compile
#
# == Configuration
#
# Configuration is loaded from +config/shakapacker.yml+ and can be accessed via
# {Shakapacker.config}. The configuration determines the source paths, output paths,
# compilation settings, and dev server options.
#
# @see Shakapacker::Configuration
# @see Shakapacker::Instance
#
# source://shakapacker//lib/shakapacker.rb#40
module Shakapacker
  extend ::Shakapacker

  # Creates the default configuration files and directory structure
  #
  # @return [void]
  # @see Shakapacker::Commands#bootstrap
  #
  # source://shakapacker//lib/shakapacker.rb#187
  def bootstrap(*_arg0, **_arg1, &_arg2); end

  # Removes old compiled packs, keeping the most recent versions
  #
  # @param age [Integer, nil] maximum age in seconds for packs to keep
  # @param count [Integer, nil] number of versions to keep per entry
  # @return [void]
  # @see Shakapacker::Commands#clean
  #
  # source://shakapacker//lib/shakapacker.rb#187
  def clean(*_arg0, **_arg1, &_arg2); end

  # Removes all compiled packs
  #
  # @return [void]
  # @see Shakapacker::Commands#clobber
  #
  # source://shakapacker//lib/shakapacker.rb#187
  def clobber(*_arg0, **_arg1, &_arg2); end

  # Returns the commands instance for build operations
  #
  # @return [Shakapacker::Commands] the commands object
  # @see Shakapacker::Instance#commands
  #
  # source://shakapacker//lib/shakapacker.rb#167
  def commands(*_arg0, **_arg1, &_arg2); end

  # Compiles all webpack/rspack packs
  #
  # @return [Boolean] true if compilation succeeded
  # @see Shakapacker::Commands#compile
  #
  # source://shakapacker//lib/shakapacker.rb#187
  def compile(*_arg0, **_arg1, &_arg2); end

  # Returns the compiler instance for compiling assets
  #
  # @return [Shakapacker::Compiler] the compiler
  # @see Shakapacker::Instance#compiler
  #
  # source://shakapacker//lib/shakapacker.rb#167
  def compiler(*_arg0, **_arg1, &_arg2); end

  # Returns the Shakapacker configuration object
  #
  # @return [Shakapacker::Configuration] the configuration
  # @see Shakapacker::Instance#config
  #
  # source://shakapacker//lib/shakapacker.rb#167
  def config(*_arg0, **_arg1, &_arg2); end

  # Returns the dev server instance for querying server status
  #
  # @return [Shakapacker::DevServer] the dev server
  # @see Shakapacker::Instance#dev_server
  #
  # source://shakapacker//lib/shakapacker.rb#167
  def dev_server(*_arg0, **_arg1, &_arg2); end

  # Temporarily redirects Shakapacker logging to STDOUT
  #
  # This is useful for debugging or when you want to see compilation output
  # in the console instead of the Rails log.
  #
  # @api public
  # @example
  #   Shakapacker.ensure_log_goes_to_stdout do
  #   Shakapacker.compile
  #   end
  # @return [Object] the return value of the block
  # @yield the block to execute with STDOUT logging
  #
  # source://shakapacker//lib/shakapacker.rb#120
  def ensure_log_goes_to_stdout; end

  # Sets NODE_ENV based on RAILS_ENV if not already set
  #
  # Environment mapping:
  # - +development+ and +test+ environments use their RAILS_ENV value for NODE_ENV
  # - All other environments (+production+, +staging+, etc.) use "production" for webpack optimizations
  #
  # This method is typically called automatically during Rails initialization.
  #
  # @api private
  # @return [String] the NODE_ENV value that was set
  #
  # source://shakapacker//lib/shakapacker.rb#104
  def ensure_node_env!; end

  # Returns the current Rails environment as an ActiveSupport::StringInquirer
  #
  # @return [ActiveSupport::StringInquirer] the environment
  # @see Shakapacker::Instance#env
  #
  # source://shakapacker//lib/shakapacker.rb#145
  def env(*_arg0, **_arg1, &_arg2); end

  # Returns whether CSS inlining is enabled
  #
  # @return [Boolean] true if CSS should be inlined
  # @see Shakapacker::Instance#inlining_css?
  #
  # source://shakapacker//lib/shakapacker.rb#145
  def inlining_css?(*_arg0, **_arg1, &_arg2); end

  # Returns the shared Shakapacker instance
  #
  # This instance is used by all module-level delegate methods. It provides
  # access to configuration, compilation, manifest lookup, and more.
  #
  # @api public
  # @return [Shakapacker::Instance] the shared instance
  #
  # source://shakapacker//lib/shakapacker.rb#68
  def instance; end

  # Sets the shared Shakapacker instance
  #
  # This is primarily used for testing or advanced customization scenarios.
  # In most applications, the default instance is sufficient.
  #
  # @api public
  # @param instance [Shakapacker::Instance] the instance to use
  # @return [Shakapacker::Instance] the instance that was set
  #
  # source://shakapacker//lib/shakapacker.rb#57
  def instance=(instance); end

  # Returns the logger instance used by Shakapacker
  #
  # @return [Logger] the logger instance
  # @see Shakapacker::Instance#logger
  #
  # source://shakapacker//lib/shakapacker.rb#145
  def logger(*_arg0, **_arg1, &_arg2); end

  # Sets the logger instance used by Shakapacker
  #
  # @param logger [Logger] the logger to use
  # @return [Logger] the logger that was set
  # @see Shakapacker::Instance#logger=
  #
  # source://shakapacker//lib/shakapacker.rb#145
  def logger=(arg); end

  # Returns the manifest instance for looking up compiled assets
  #
  # @return [Shakapacker::Manifest] the manifest
  # @see Shakapacker::Instance#manifest
  #
  # source://shakapacker//lib/shakapacker.rb#167
  def manifest(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/deprecation_helper.rb#6
  def puts_deprecation_message(message); end

  # Temporarily overrides NODE_ENV for the duration of the block
  #
  # This is useful when you need to perform operations with a specific NODE_ENV
  # value without permanently changing the environment.
  #
  # @api public
  # @example
  #   Shakapacker.with_node_env("production") do
  #   # This code runs with NODE_ENV=production
  #   Shakapacker.compile
  #   end
  # @param env [String] the NODE_ENV value to use temporarily
  # @return [Object] the return value of the block
  # @yield the block to execute with the temporary NODE_ENV
  #
  # source://shakapacker//lib/shakapacker.rb#86
  def with_node_env(env); end
end

# source://shakapacker//lib/shakapacker/base_strategy.rb#2
class Shakapacker::BaseStrategy
  # @return [BaseStrategy] a new instance of BaseStrategy
  #
  # source://shakapacker//lib/shakapacker/base_strategy.rb#3
  def initialize; end

  # source://shakapacker//lib/shakapacker/base_strategy.rb#7
  def after_compile_hook; end

  private

  # Returns the value of attribute config.
  #
  # source://shakapacker//lib/shakapacker/base_strategy.rb#13
  def config; end

  # source://shakapacker//lib/shakapacker/base_strategy.rb#15
  def default_watched_paths; end
end

# source://shakapacker//lib/shakapacker/commands.rb#1
class Shakapacker::Commands
  # @return [Commands] a new instance of Commands
  #
  # source://shakapacker//lib/shakapacker/commands.rb#4
  def initialize(instance); end

  # source://shakapacker//lib/shakapacker/commands.rb#47
  def bootstrap; end

  # Cleanup old assets in the compile directory. By default it will
  # keep the latest version, 2 backups created within the past hour.
  #
  # Examples
  #
  #   To force only 1 backup to be kept, set count=1 and age=0.
  #
  #   To only keep files created within the last 10 minutes, set count=0 and
  #   age=600.
  #
  # source://shakapacker//lib/shakapacker/commands.rb#18
  def clean(count = T.unsafe(nil), age = T.unsafe(nil)); end

  # source://shakapacker//lib/shakapacker/commands.rb#42
  def clobber; end

  # source://shakapacker//lib/shakapacker/commands.rb#51
  def compile; end

  # source://shakapacker//lib/shakapacker/commands.rb#2
  def compiler(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/commands.rb#2
  def config(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/commands.rb#2
  def logger(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/commands.rb#2
  def manifest(*_arg0, **_arg1, &_arg2); end

  private

  # source://shakapacker//lib/shakapacker/commands.rb#69
  def current_version; end

  # source://shakapacker//lib/shakapacker/commands.rb#58
  def packs; end
end

# source://shakapacker//lib/shakapacker/compiler.rb#7
class Shakapacker::Compiler
  # @return [Compiler] a new instance of Compiler
  #
  # source://shakapacker//lib/shakapacker/compiler.rb#15
  def initialize(instance); end

  # source://shakapacker//lib/shakapacker/compiler.rb#13
  def after_compile_hook(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/compiler.rb#19
  def compile; end

  # source://shakapacker//lib/shakapacker/compiler.rb#12
  def config(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/compiler.rb#10
  def env; end

  # source://shakapacker//lib/shakapacker/compiler.rb#10
  def env=(val); end

  # source://shakapacker//lib/shakapacker/compiler.rb#13
  def fresh?(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/compiler.rb#12
  def logger(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/compiler.rb#13
  def stale?(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/compiler.rb#12
  def strategy(*_arg0, **_arg1, &_arg2); end

  private

  # source://shakapacker//lib/shakapacker/compiler.rb#41
  def acquire_ipc_lock; end

  # source://shakapacker//lib/shakapacker/compiler.rb#201
  def bin_shakapacker_path; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/compiler.rb#54
  def compiling?; end

  # source://shakapacker//lib/shakapacker/compiler.rb#69
  def create_lock_file_dir; end

  # Returns the value of attribute instance.
  #
  # source://shakapacker//lib/shakapacker/compiler.rb#39
  def instance; end

  # source://shakapacker//lib/shakapacker/compiler.rb#74
  def lock_file_path; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/compiler.rb#48
  def locked?; end

  # source://shakapacker//lib/shakapacker/compiler.rb#61
  def open_lock_file; end

  # source://shakapacker//lib/shakapacker/compiler.rb#78
  def optional_ruby_runner; end

  # source://shakapacker//lib/shakapacker/compiler.rb#90
  def run_precompile_hook; end

  # source://shakapacker//lib/shakapacker/compiler.rb#168
  def run_webpack; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/compiler.rb#83
  def should_run_precompile_hook?; end

  # source://shakapacker//lib/shakapacker/compiler.rb#120
  def validate_precompile_hook(hook_command); end

  # source://shakapacker//lib/shakapacker/compiler.rb#56
  def wait_for_compilation_to_complete; end

  # source://shakapacker//lib/shakapacker/compiler.rb#192
  def webpack_env; end

  class << self
    # source://shakapacker//lib/shakapacker/compiler.rb#10
    def env; end

    # source://shakapacker//lib/shakapacker/compiler.rb#10
    def env=(val); end
  end
end

# source://shakapacker//lib/shakapacker/compiler_strategy.rb#5
class Shakapacker::CompilerStrategy
  class << self
    # source://shakapacker//lib/shakapacker/compiler_strategy.rb#6
    def from_config; end
  end
end

# Configuration management for Shakapacker
#
# Loads and provides access to settings from +config/shakapacker.yml+, including:
# - Source and output paths
# - Compilation settings
# - Dev server configuration
# - Asset bundler selection (webpack vs rspack)
# - JavaScript transpiler configuration (babel, swc, esbuild)
#
# Configuration values can be overridden via environment variables:
# - +SHAKAPACKER_CONFIG+ - path to config file
# - +SHAKAPACKER_PRECOMPILE+ - whether to precompile assets
# - +SHAKAPACKER_ASSETS_BUNDLER+ - which bundler to use
# - +SHAKAPACKER_ASSET_HOST+ - CDN or asset host URL
#
# @example Accessing configuration
#   config = Shakapacker.config
#   config.source_path
#   #=> #<Pathname:/app/app/packs>
#   config.webpack?
#   #=> true
# @see https://github.com/shakacode/shakapacker/blob/main/docs/shakapacker.yml.md
#
# source://shakapacker//lib/shakapacker/configuration.rb#29
class Shakapacker::Configuration
  # Creates a new configuration instance
  #
  # @param bundler_override [String, nil] optional bundler override (webpack or rspack)
  # @param config_path [Pathname] the path to shakapacker.yml
  # @param env [ActiveSupport::StringInquirer] the Rails environment
  # @param root_path [Pathname] the application root path
  # @return [Shakapacker::Configuration] the new configuration instance
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#62
  def initialize(root_path:, config_path:, env:, bundler_override: T.unsafe(nil)); end

  # Returns additional paths to include in compilation
  #
  # These paths are added to webpack/rspack's resolve configuration to allow
  # importing modules from additional directories.
  #
  # @return [Array<String>] array of additional paths
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#139
  def additional_paths; end

  # Returns the asset host URL for serving assets
  #
  # Resolution order:
  # 1. SHAKAPACKER_ASSET_HOST environment variable
  # 2. asset_host setting in config file
  # 3. Rails ActionController::Base.helpers.compute_asset_host
  #
  # Used to serve assets from a CDN or different domain.
  #
  # @return [String, nil] the asset host URL or nil
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#485
  def asset_host; end

  # Returns the assets bundler to use (webpack or rspack)
  #
  # Resolution order:
  # 1. CLI --bundler flag (via bundler_override)
  # 2. SHAKAPACKER_ASSETS_BUNDLER environment variable
  # 3. assets_bundler setting in config file
  # 4. bundler setting in config file (deprecated)
  # 5. Defaults to "webpack"
  #
  # @return [String] "webpack" or "rspack"
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#257
  def assets_bundler; end

  # Returns the path to the bundler configuration directory
  #
  # This is where webpack.config.js or rspack.config.js should be located.
  # Defaults to config/webpack for webpack or config/rspack for rspack.
  #
  # @return [String] the relative path to the bundler config directory
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#373
  def assets_bundler_config_path; end

  # Deprecated alias for {#assets_bundler}
  #
  # @deprecated Use {#assets_bundler} instead
  # @return [String] the assets bundler
  # @see #assets_bundler
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#273
  def bundler; end

  # Override for the assets bundler (set via CLI flag)
  #
  # @api private
  # @return [String, nil] the bundler override or nil
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#53
  def bundler_override; end

  # Returns whether manifest caching is enabled
  #
  # When true, the manifest.json file is cached in memory and only reloaded
  # when it changes. This improves performance in production.
  #
  # @return [Boolean] true if manifest should be cached
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#213
  def cache_manifest?; end

  # Returns the absolute path to the compilation cache directory
  #
  # Webpack/rspack uses this directory to cache compilation results for faster
  # subsequent builds.
  #
  # @return [Pathname] the absolute cache path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#223
  def cache_path; end

  # Returns whether automatic compilation is enabled
  #
  # When true, Shakapacker will automatically compile assets when they're requested
  # and are stale. This is typically enabled in development and disabled in production.
  #
  # @return [Boolean] true if automatic compilation is enabled
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#84
  def compile?; end

  # Returns the compiler strategy for determining staleness
  #
  # Options:
  # - +"mtime"+ - use file modification times (faster, less accurate)
  # - +"digest"+ - use file content digests (slower, more accurate)
  #
  # @return [String] the compiler strategy ("mtime" or "digest")
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#243
  def compiler_strategy; end

  # The path to the shakapacker.yml configuration file
  #
  # @return [Pathname] the config file path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#44
  def config_path; end

  # Returns the CSS Modules export mode configuration
  #
  # Controls how CSS Module class names are exported in JavaScript:
  # - "named" (default): Use named exports with camelCase conversion (v9 behavior)
  # - "default": Use default export with both original and camelCase names (v8 behavior)
  #
  # @raise [ArgumentError] if an invalid value is configured
  # @return [String] "named" or "default"
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#350
  def css_modules_export_mode; end

  # Returns the raw configuration data hash
  #
  # Returns the merged configuration from the shakapacker.yml file for the current environment.
  # The hash has symbolized keys loaded from the config file. Individual config values can be
  # accessed through specific accessor methods like {#source_path}, which apply defaults via {#fetch}.
  #
  # The returned hash is frozen to prevent accidental mutations. To access config values,
  # use the provided accessor methods instead of modifying this hash directly.
  #
  # @api public
  # @example
  #   config.data[:source_path]  #=> "app/javascript"
  #   config.data[:compile]      #=> true
  # @note The hash is frozen to prevent mutations. Use accessor methods for safe config access.
  # @return [Hash<Symbol, Object>] the raw configuration data with symbolized keys (frozen)
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#396
  def data; end

  # Returns the dev server configuration hash
  #
  # Contains settings like host, port, https, hmr, etc. for the webpack-dev-server.
  #
  # @return [Hash] the dev server configuration
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#74
  def dev_server; end

  # Returns whether HTTP/2 Early Hints are enabled
  #
  # When true, sends Early Hints headers to start loading assets before
  # the full response is ready.
  #
  # @return [Boolean] true if early hints are enabled
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#508
  def early_hints; end

  # Returns whether consistent versioning check is enabled
  #
  # When true, verifies that package.json and Gemfile versions of shakapacker match.
  #
  # @return [Boolean] true if version consistency checking is enabled
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#103
  def ensure_consistent_versioning?; end

  # The current Rails environment
  #
  # @return [ActiveSupport::StringInquirer] the environment
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#48
  def env; end

  # Fetches a configuration value
  #
  # Looks up the value in the loaded configuration data, falling back to
  # the default configuration if not found.
  #
  # @api private
  # @param key [Symbol] the configuration key to fetch
  # @return [Object] the configuration value
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#471
  def fetch(key); end

  # Returns whether subresource integrity (SRI) is enabled
  #
  # When true, generates integrity hashes for script and link tags to
  # protect against compromised CDNs or man-in-the-middle attacks.
  #
  # @return [Boolean] true if integrity checking is enabled
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#498
  def integrity; end

  # Returns the JavaScript transpiler to use (babel, swc, or esbuild)
  #
  # Resolution order:
  # 1. javascript_transpiler setting in config file
  # 2. webpack_loader setting in config file (deprecated)
  # 3. Default based on bundler (swc for rspack, babel for webpack)
  #
  # Validates that the configured transpiler matches installed packages.
  #
  # @return [String] "babel", "swc", or "esbuild"
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#318
  def javascript_transpiler; end

  # Returns the absolute path to the manifest.json file
  #
  # The manifest maps source file names to their compiled output paths with digests.
  # Defaults to manifest.json in the public output directory if not configured.
  #
  # @return [Pathname] the absolute manifest path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#158
  def manifest_path; end

  # Returns whether nested entries are enabled
  #
  # When true, allows organizing entry points in subdirectories within the
  # source entry path.
  #
  # @return [Boolean] true if nested entries are allowed
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#94
  def nested_entries?; end

  # Returns the precompile hook command to run after compilation
  #
  # The hook is a shell command that runs after successful compilation,
  # useful for post-processing tasks.
  #
  # @return [String, nil] the hook command or nil if not configured
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#297
  def precompile_hook; end

  # Returns the absolute path to the private output directory
  #
  # The private output path is for server-side bundles (e.g., SSR) that should
  # not be publicly accessible. Returns nil if not configured.
  #
  # @return [Pathname, nil] the absolute private output path or nil
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#190
  def private_output_path; end

  # Alias for {#manifest_path}
  #
  # @return [Pathname] the absolute manifest path
  # @see #manifest_path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#170
  def public_manifest_path; end

  # Returns the absolute path to the public output directory
  #
  # This is where compiled assets are written for public serving
  # (typically +public/packs+).
  #
  # @return [Pathname] the absolute public output path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#203
  def public_output_path; end

  # Returns the absolute path to the public root directory
  #
  # This is typically the Rails +public/+ directory where compiled assets
  # are served from.
  #
  # @return [Pathname] the absolute public path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#180
  def public_path; end

  # The application root path
  #
  # @return [Pathname] the root path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#40
  def root_path; end

  # Returns whether rspack is the configured bundler
  #
  # @return [Boolean] true if using rspack
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#280
  def rspack?; end

  # Returns whether Shakapacker should precompile assets
  #
  # Checks in order:
  # 1. SHAKAPACKER_PRECOMPILE environment variable (yes/true/y/t or no/false/n/f)
  # 2. shakapacker_precompile setting in config file
  # 3. Defaults to false if config file doesn't exist
  #
  # @return [Boolean] true if assets should be precompiled
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#115
  def shakapacker_precompile?; end

  # Returns the absolute path to the source entry directory
  #
  # Entry points (application.js, etc.) are found in this directory.
  #
  # @return [Pathname] the absolute entry path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#148
  def source_entry_path; end

  # Returns the absolute path to the source directory
  #
  # This is where your JavaScript/CSS source files live (e.g., app/packs).
  #
  # @return [Pathname] the absolute source path
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#129
  def source_path; end

  # Returns whether webpack is the configured bundler
  #
  # @return [Boolean] true if using webpack
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#287
  def webpack?; end

  # Returns whether webpack/rspack compilation output should be shown
  #
  # When true, displays webpack/rspack's compilation progress and results.
  #
  # @return [Boolean] true if compilation output should be displayed
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#232
  def webpack_compile_output?; end

  # Deprecated alias for {#javascript_transpiler}
  #
  # @deprecated Use {#javascript_transpiler} instead
  # @return [String] the JavaScript transpiler
  # @see #javascript_transpiler
  #
  # source://shakapacker//lib/shakapacker/configuration.rb#338
  def webpack_loader; end

  private

  # source://shakapacker//lib/shakapacker/configuration.rb#402
  def default_javascript_transpiler; end

  # source://shakapacker//lib/shakapacker/configuration.rb#582
  def defaults; end

  # source://shakapacker//lib/shakapacker/configuration.rb#545
  def load; end

  # source://shakapacker//lib/shakapacker/configuration.rb#603
  def log_fallback(requested_env, fallback_env); end

  # source://shakapacker//lib/shakapacker/configuration.rb#597
  def relative_path(path); end

  # source://shakapacker//lib/shakapacker/configuration.rb#530
  def resolve_paths_for_comparison; end

  # source://shakapacker//lib/shakapacker/configuration.rb#513
  def validate_output_paths!; end

  # source://shakapacker//lib/shakapacker/configuration.rb#407
  def validate_transpiler_configuration(transpiler); end

  # source://shakapacker//lib/shakapacker/configuration.rb#446
  def warn_transpiler_mismatch(configured, message); end

  class << self
    # Flag indicating whether Shakapacker is currently being installed
    # Used to suppress certain validations during installation
    #
    # @api private
    # @return [Boolean] true if installation is in progress
    #
    # source://shakapacker//lib/shakapacker/configuration.rb#35
    def installing; end

    # Flag indicating whether Shakapacker is currently being installed
    # Used to suppress certain validations during installation
    #
    # @api private
    # @return [Boolean] true if installation is in progress
    #
    # source://shakapacker//lib/shakapacker/configuration.rb#35
    def installing=(_arg0); end
  end
end

# Default environment when RAILS_ENV is not set
#
# source://shakapacker//lib/shakapacker.rb#44
Shakapacker::DEFAULT_ENV = T.let(T.unsafe(nil), String)

# Environments that use their RAILS_ENV value for NODE_ENV
# All other environments (production, staging, etc.) use "production" for webpack optimizations
#
# source://shakapacker//lib/shakapacker.rb#47
Shakapacker::DEV_TEST_ENVS = T.let(T.unsafe(nil), Array)

# Development server status and configuration
#
# Provides methods to query the status and configuration of the webpack-dev-server
# or rspack-dev-server. This includes checking if the server is running, accessing
# its host/port, and querying features like HMR (Hot Module Replacement).
#
# The dev server runs during development to provide live reloading and hot module
# replacement. In production, the dev server is not used.
#
# @example Checking dev server status
#   dev_server = Shakapacker.dev_server
#   dev_server.running?
#   #=> true
#   dev_server.host_with_port
#   #=> "localhost:3035"
#   dev_server.hmr?
#   #=> true
# @see Shakapacker::DevServerRunner
#
# source://shakapacker//lib/shakapacker/dev_server.rb#20
class Shakapacker::DevServer
  # Creates a new dev server instance
  #
  # @param config [Shakapacker::Configuration] the Shakapacker configuration
  # @return [Shakapacker::DevServer] the new dev server instance
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#38
  def initialize(config); end

  # The Shakapacker configuration
  #
  # @return [Shakapacker::Configuration] the configuration
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#32
  def config; end

  # Configure dev server connection timeout (in seconds), default: 0.1
  #
  # @example
  #   Shakapacker::DevServer.connect_timeout = 1
  # @return [Float] the connection timeout in seconds
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#28
  def connect_timeout; end

  # source://shakapacker//lib/shakapacker/dev_server.rb#28
  def connect_timeout=(val); end

  # Returns the environment variable prefix for dev server settings
  #
  # Environment variables for dev server settings use this prefix (default: "SHAKAPACKER_DEV_SERVER").
  # For example, SHAKAPACKER_DEV_SERVER_PORT sets the port.
  #
  # @return [String] the env var prefix (typically "SHAKAPACKER_DEV_SERVER")
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#166
  def env_prefix; end

  # Returns whether Hot Module Replacement (HMR) is enabled
  #
  # When true, the dev server updates modules in the browser without a full
  # page reload, preserving application state.
  # Can be overridden via SHAKAPACKER_DEV_SERVER_HMR environment variable.
  #
  # @return [Boolean] true if HMR is enabled
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#140
  def hmr?; end

  # Returns the dev server host
  #
  # Can be overridden via SHAKAPACKER_DEV_SERVER_HOST environment variable.
  #
  # @return [String] the host (e.g., "localhost", "0.0.0.0")
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#64
  def host; end

  # Returns the host and port as a single string
  #
  # @example
  #   dev_server.host_with_port
  #   #=> "localhost:3035"
  # @return [String] the host:port combination (e.g., "localhost:3035")
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#119
  def host_with_port; end

  # Returns whether CSS inlining is enabled
  #
  # When true, CSS is injected inline via JavaScript instead of being loaded
  # as separate stylesheet files. This enables HMR for CSS.
  # Can be overridden via SHAKAPACKER_DEV_SERVER_INLINE_CSS environment variable.
  #
  # @return [Boolean] true if CSS should be inlined
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#151
  def inline_css?; end

  # Returns the dev server port
  #
  # Can be overridden via SHAKAPACKER_DEV_SERVER_PORT environment variable.
  #
  # @return [Integer] the port number (typically 3035)
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#73
  def port; end

  # Returns whether pretty output is enabled
  #
  # When true, the dev server produces prettier, more readable output.
  # Can be overridden via SHAKAPACKER_DEV_SERVER_PRETTY environment variable.
  #
  # @return [Boolean] true if pretty output is enabled
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#129
  def pretty?; end

  # Returns the protocol for the dev server
  #
  # This is an alias that returns "https" if server is "https", otherwise "http".
  #
  # @return [String] "http" or "https"
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#107
  def protocol; end

  # Returns whether the dev server is currently running
  #
  # Checks by attempting to open a TCP connection to the configured host and port.
  # Returns false if the connection fails or if dev server is not configured.
  #
  # @return [Boolean] true if the dev server is running
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#48
  def running?; end

  # Returns the server type (http or https)
  #
  # Can be overridden via SHAKAPACKER_DEV_SERVER_SERVER environment variable.
  # Validates that the value is "http" or "https", falling back to "http" if invalid.
  #
  # @return [String] "http" or "https"
  #
  # source://shakapacker//lib/shakapacker/dev_server.rb#83
  def server; end

  private

  # source://shakapacker//lib/shakapacker/dev_server.rb#179
  def defaults; end

  # source://shakapacker//lib/shakapacker/dev_server.rb#171
  def fetch(key); end

  class << self
    # source://shakapacker//lib/shakapacker/dev_server.rb#28
    def connect_timeout; end

    # source://shakapacker//lib/shakapacker/dev_server.rb#28
    def connect_timeout=(val); end
  end
end

# Default environment variable prefix for dev server settings
#
# source://shakapacker//lib/shakapacker/dev_server.rb#22
Shakapacker::DevServer::DEFAULT_ENV_PREFIX = T.let(T.unsafe(nil), String)

# source://shakapacker//lib/shakapacker/dev_server_proxy.rb#3
class Shakapacker::DevServerProxy < ::Rack::Proxy
  # @return [DevServerProxy] a new instance of DevServerProxy
  #
  # source://shakapacker//lib/shakapacker/dev_server_proxy.rb#6
  def initialize(app = T.unsafe(nil), opts = T.unsafe(nil)); end

  # source://shakapacker//lib/shakapacker/dev_server_proxy.rb#4
  def config(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/dev_server_proxy.rb#4
  def dev_server(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/dev_server_proxy.rb#12
  def perform_request(env); end

  private

  # source://shakapacker//lib/shakapacker/dev_server_proxy.rb#30
  def public_output_uri_path; end
end

# source://shakapacker//lib/shakapacker/digest_strategy.rb#6
class Shakapacker::DigestStrategy < ::Shakapacker::BaseStrategy
  # source://shakapacker//lib/shakapacker/digest_strategy.rb#17
  def after_compile_hook; end

  # Returns true if all the compiled packs are up to date with the underlying asset files.
  #
  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/digest_strategy.rb#8
  def fresh?; end

  # Returns true if the compiled packs are out of date with the underlying asset files.
  #
  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/digest_strategy.rb#13
  def stale?; end

  private

  # source://shakapacker//lib/shakapacker/digest_strategy.rb#58
  def compilation_digest_path; end

  # source://shakapacker//lib/shakapacker/digest_strategy.rb#27
  def last_compilation_digest; end

  # source://shakapacker//lib/shakapacker/digest_strategy.rb#53
  def record_compilation_digest; end

  # source://shakapacker//lib/shakapacker/digest_strategy.rb#32
  def watched_files_digest; end
end

# source://shakapacker//lib/shakapacker/doctor.rb#7
class Shakapacker::Doctor
  # @return [Doctor] a new instance of Doctor
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#15
  def initialize(config = T.unsafe(nil), root_path = T.unsafe(nil), options = T.unsafe(nil)); end

  # Returns the value of attribute config.
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#8
  def config; end

  # Returns the value of attribute info.
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#8
  def info; end

  # Returns the value of attribute issues.
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#8
  def issues; end

  # Returns the value of attribute options.
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#8
  def options; end

  # Returns the value of attribute root_path.
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#8
  def root_path; end

  # source://shakapacker//lib/shakapacker/doctor.rb#24
  def run; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#34
  def success?; end

  # Returns the value of attribute warnings.
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#8
  def warnings; end

  private

  # source://shakapacker//lib/shakapacker/doctor.rb#44
  def add_action_required(message); end

  # source://shakapacker//lib/shakapacker/doctor.rb#48
  def add_info_warning(message); end

  # source://shakapacker//lib/shakapacker/doctor.rb#40
  def add_warning(message, category = T.unsafe(nil)); end

  # source://shakapacker//lib/shakapacker/doctor.rb#311
  def check_assets_compilation; end

  # source://shakapacker//lib/shakapacker/doctor.rb#441
  def check_babel_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#453
  def check_babel_performance_suggestion; end

  # source://shakapacker//lib/shakapacker/doctor.rb#388
  def check_binstub; end

  # source://shakapacker//lib/shakapacker/doctor.rb#667
  def check_bundler_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#114
  def check_config_file; end

  # source://shakapacker//lib/shakapacker/doctor.rb#596
  def check_css_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#602
  def check_css_modules_configuration; end

  # source://shakapacker//lib/shakapacker/doctor.rb#642
  def check_css_modules_import_patterns; end

  # source://shakapacker//lib/shakapacker/doctor.rb#719
  def check_dependency(package_name, issues_array, description); end

  # source://shakapacker//lib/shakapacker/doctor.rb#180
  def check_deprecated_config; end

  # source://shakapacker//lib/shakapacker/doctor.rb#120
  def check_entry_points; end

  # source://shakapacker//lib/shakapacker/doctor.rb#222
  def check_environment_consistency; end

  # source://shakapacker//lib/shakapacker/doctor.rb#483
  def check_esbuild_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#679
  def check_file_type_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#409
  def check_javascript_transpiler_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#342
  def check_legacy_webpacker_files; end

  # source://shakapacker//lib/shakapacker/doctor.rb#704
  def check_less_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#358
  def check_node_installation; end

  # source://shakapacker//lib/shakapacker/doctor.rb#725
  def check_optional_dependency(package_name, warnings_array, description); end

  # source://shakapacker//lib/shakapacker/doctor.rb#141
  def check_output_paths; end

  # source://shakapacker//lib/shakapacker/doctor.rb#382
  def check_package_manager; end

  # source://shakapacker//lib/shakapacker/doctor.rb#255
  def check_peer_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#714
  def check_postcss_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#287
  def check_rspack_peer_deps(deps); end

  # source://shakapacker//lib/shakapacker/doctor.rb#699
  def check_sass_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#236
  def check_sri_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#709
  def check_stylus_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#536
  def check_swc_config_conflicts; end

  # source://shakapacker//lib/shakapacker/doctor.rb#553
  def check_swc_config_settings(config_path); end

  # source://shakapacker//lib/shakapacker/doctor.rb#457
  def check_swc_dependencies(bundler); end

  # source://shakapacker//lib/shakapacker/doctor.rb#492
  def check_transpiler_config_consistency; end

  # source://shakapacker//lib/shakapacker/doctor.rb#690
  def check_typescript_dependencies; end

  # source://shakapacker//lib/shakapacker/doctor.rb#198
  def check_version_consistency; end

  # source://shakapacker//lib/shakapacker/doctor.rb#274
  def check_webpack_peer_deps(deps); end

  # source://shakapacker//lib/shakapacker/doctor.rb#300
  def check_windows_platform; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#755
  def config_exists?; end

  # source://shakapacker//lib/shakapacker/doctor.rb#784
  def detect_package_manager; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#768
  def less_files_exist?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#731
  def package_installed?(package_name); end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#739
  def package_json_exists?; end

  # source://shakapacker//lib/shakapacker/doctor.rb#743
  def package_json_path; end

  # source://shakapacker//lib/shakapacker/doctor.rb#780
  def package_manager; end

  # source://shakapacker//lib/shakapacker/doctor.rb#83
  def perform_checks; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#776
  def postcss_config_exists?; end

  # source://shakapacker//lib/shakapacker/doctor.rb#52
  def print_help; end

  # source://shakapacker//lib/shakapacker/doctor.rb#747
  def read_package_json; end

  # source://shakapacker//lib/shakapacker/doctor.rb#822
  def report_results; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#764
  def sass_files_exist?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#586
  def stimulus_likely_used?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#772
  def stylus_files_exist?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#759
  def typescript_files_exist?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#792
  def versions_compatible?(gem_version, npm_version); end
end

# Warning categories for better organization
#
# source://shakapacker//lib/shakapacker/doctor.rb#11
Shakapacker::Doctor::CATEGORY_ACTION_REQUIRED = T.let(T.unsafe(nil), Symbol)

# source://shakapacker//lib/shakapacker/doctor.rb#13
Shakapacker::Doctor::CATEGORY_INFO = T.let(T.unsafe(nil), Symbol)

# source://shakapacker//lib/shakapacker/doctor.rb#12
Shakapacker::Doctor::CATEGORY_RECOMMENDED = T.let(T.unsafe(nil), Symbol)

# source://shakapacker//lib/shakapacker/doctor.rb#828
class Shakapacker::Doctor::Reporter
  # @return [Reporter] a new instance of Reporter
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#831
  def initialize(doctor); end

  # Returns the value of attribute doctor.
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#829
  def doctor; end

  # source://shakapacker//lib/shakapacker/doctor.rb#835
  def print_report; end

  private

  # source://shakapacker//lib/shakapacker/doctor.rb#1115
  def build_wrapped_lines(text, available_width); end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#1154
  def dependency_issue?(message); end

  # source://shakapacker//lib/shakapacker/doctor.rb#944
  def format_array_value(array); end

  # source://shakapacker//lib/shakapacker/doctor.rb#933
  def format_config_value(value); end

  # source://shakapacker//lib/shakapacker/doctor.rb#952
  def format_hash_value(hash); end

  # source://shakapacker//lib/shakapacker/doctor.rb#1138
  def format_wrapped_output(lines, prefix); end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#1149
  def has_dependency_issues?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#1160
  def missing_dependency?(message); end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#1164
  def not_installed?(message); end

  # source://shakapacker//lib/shakapacker/doctor.rb#1180
  def package_manager_install_command(manager); end

  # source://shakapacker//lib/shakapacker/doctor.rb#1012
  def print_binstub_status; end

  # source://shakapacker//lib/shakapacker/doctor.rb#970
  def print_bundler_status; end

  # source://shakapacker//lib/shakapacker/doctor.rb#857
  def print_checks; end

  # source://shakapacker//lib/shakapacker/doctor.rb#926
  def print_config_data(config_data); end

  # source://shakapacker//lib/shakapacker/doctor.rb#913
  def print_config_values; end

  # source://shakapacker//lib/shakapacker/doctor.rb#982
  def print_css_status; end

  # source://shakapacker//lib/shakapacker/doctor.rb#888
  def print_environment_info; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1168
  def print_fix_instructions; end

  # source://shakapacker//lib/shakapacker/doctor.rb#847
  def print_header; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1030
  def print_info_messages; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1052
  def print_issues; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1090
  def print_main_item(item_number, warning); end

  # source://shakapacker//lib/shakapacker/doctor.rb#994
  def print_node_status; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1005
  def print_package_manager_status; end

  # source://shakapacker//lib/shakapacker/doctor.rb#988
  def print_package_status(package_name, description); end

  # source://shakapacker//lib/shakapacker/doctor.rb#905
  def print_path_info; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1082
  def print_subitem(message); end

  # source://shakapacker//lib/shakapacker/doctor.rb#1039
  def print_summary; end

  # source://shakapacker//lib/shakapacker/doctor.rb#960
  def print_transpiler_status; end

  # source://shakapacker//lib/shakapacker/doctor.rb#880
  def print_verbose_checks; end

  # source://shakapacker//lib/shakapacker/doctor.rb#895
  def print_version_info; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1060
  def print_warnings; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#1078
  def subitem?(message); end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/doctor.rb#843
  def verbose?; end

  # source://shakapacker//lib/shakapacker/doctor.rb#1105
  def wrap_text(text, max_width, prefix); end
end

# source://shakapacker//lib/shakapacker/railtie.rb#8
class Shakapacker::Engine < ::Rails::Engine; end

# source://shakapacker//lib/shakapacker/env.rb#1
class Shakapacker::Env
  # @return [Env] a new instance of Env
  #
  # source://shakapacker//lib/shakapacker/env.rb#8
  def initialize(instance); end

  # source://shakapacker//lib/shakapacker/env.rb#2
  def config_path(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/env.rb#12
  def inquire; end

  # source://shakapacker//lib/shakapacker/env.rb#2
  def logger(*_arg0, **_arg1, &_arg2); end

  private

  # source://shakapacker//lib/shakapacker/env.rb#26
  def available_environments; end

  # source://shakapacker//lib/shakapacker/env.rb#18
  def current; end

  # source://shakapacker//lib/shakapacker/env.rb#22
  def fallback_env_warning; end

  class << self
    # source://shakapacker//lib/shakapacker/env.rb#4
    def inquire(instance); end
  end
end

# source://shakapacker//lib/shakapacker/helper.rb#1
module Shakapacker::Helper
  # source://shakapacker//lib/shakapacker/helper.rb#343
  def append_javascript_pack_tag(*names, defer: T.unsafe(nil), async: T.unsafe(nil)); end

  # source://shakapacker//lib/shakapacker/helper.rb#330
  def append_stylesheet_pack_tag(*names); end

  # Computes the relative path for a given Shakapacker asset.
  # Returns the relative path using manifest.json and passes it to path_to_asset helper.
  # This will use path_to_asset internally, so most of their behaviors will be the same.
  #
  # Example:
  #
  #   <%= asset_pack_path 'calendar.css' %> # => "/packs/calendar-1016838bab065ae1e122.css"
  #
  # source://shakapacker//lib/shakapacker/helper.rb#16
  def asset_pack_path(name, **options); end

  # Computes the absolute path for a given Shakapacker asset.
  # Returns the absolute path using manifest.json and passes it to url_to_asset helper.
  # This will use url_to_asset internally, so most of their behaviors will be the same.
  #
  # Example:
  #
  #   <%= asset_pack_url 'calendar.css' %> # => "http://example.com/packs/calendar-1016838bab065ae1e122.css"
  #
  # source://shakapacker//lib/shakapacker/helper.rb#27
  def asset_pack_url(name, **options); end

  # Returns the current Shakapacker instance.
  # Could be overridden to use multiple Shakapacker
  # configurations within the same app (e.g. with engines).
  #
  # source://shakapacker//lib/shakapacker/helper.rb#5
  def current_shakapacker_instance; end

  # Creates a link tag for a favicon that references the named pack file.
  #
  # Example:
  #
  #  <%= favicon_pack_tag 'mb-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  #  <link href="/packs/mb-icon-k344a6d59eef8632c9d1.png" rel="apple-touch-icon" type="image/png" />
  #
  # source://shakapacker//lib/shakapacker/helper.rb#71
  def favicon_pack_tag(name, **options); end

  # Computes the relative path for a given Shakapacker image with the same automated processing as image_pack_tag.
  # Returns the relative path using manifest.json and passes it to path_to_asset helper.
  # This will use path_to_asset internally, so most of their behaviors will be the same.
  #
  # source://shakapacker//lib/shakapacker/helper.rb#34
  def image_pack_path(name, **options); end

  # Creates an image tag that references the named pack file.
  #
  # Example:
  #
  #  <%= image_pack_tag 'application.png', size: '16x10', alt: 'Edit Entry' %>
  #  <img alt='Edit Entry' src='/packs/application-k344a6d59eef8632c9d1.png' width='16' height='10' />
  #
  #  <%= image_pack_tag 'picture.png', srcset: { 'picture-2x.png' => '2x' } %>
  #  <img srcset= "/packs/picture-2x-7cca48e6cae66ec07b8e.png 2x" src="/packs/picture-c38deda30895059837cf.png" >
  #
  # source://shakapacker//lib/shakapacker/helper.rb#55
  def image_pack_tag(name, **options); end

  # Computes the absolute path for a given Shakapacker image with the same automated
  # processing as image_pack_tag. Returns the relative path using manifest.json
  # and passes it to path_to_asset helper. This will use path_to_asset internally,
  # so most of their behaviors will be the same.
  #
  # source://shakapacker//lib/shakapacker/helper.rb#42
  def image_pack_url(name, **options); end

  # Creates script tags that reference the js chunks from entrypoints when using split chunks API,
  # as compiled by webpack per the entries list in package/environments/base.js.
  # By default, this list is auto-generated to match everything in
  # app/javascript/entrypoints/*.js and all the dependent chunks. In production mode, the digested reference is automatically looked up.
  # See: https://webpack.js.org/plugins/split-chunks-plugin/
  #
  # Example:
  #
  #   <%= javascript_pack_tag 'calendar', 'map', 'data-turbolinks-track': 'reload' %> # =>
  #   <script src="/packs/vendor-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload" defer="true"></script>
  #   <script src="/packs/calendar~runtime-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload" defer="true"></script>
  #   <script src="/packs/calendar-1016838bab065ae1e314.chunk.js" data-turbolinks-track="reload" defer="true"></script>
  #   <script src="/packs/map~runtime-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload" defer="true"></script>
  #   <script src="/packs/map-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload" defer="true"></script>
  #
  # DO:
  #
  #   <%= javascript_pack_tag 'calendar', 'map' %>
  #
  # DON'T:
  #
  #   <%= javascript_pack_tag 'calendar' %>
  #   <%= javascript_pack_tag 'map' %>
  #
  # Early Hints:
  #   By default, HTTP 103 Early Hints are sent automatically when this helper is called,
  #   allowing browsers to preload JavaScript assets in parallel with Rails rendering.
  #
  #   <%= javascript_pack_tag 'application' %>
  #   # Automatically sends early hints for 'application' pack
  #
  #   # Customize handling per pack:
  #   <%= javascript_pack_tag 'application', 'vendor',
  #         early_hints: { 'application' => 'preload', 'vendor' => 'prefetch' } %>
  #
  #   # Disable early hints:
  #   <%= javascript_pack_tag 'application', early_hints: false %>
  #
  # source://shakapacker//lib/shakapacker/helper.rb#112
  def javascript_pack_tag(*names, defer: T.unsafe(nil), async: T.unsafe(nil), early_hints: T.unsafe(nil), **options); end

  # Creates a link tag, for preloading, that references a given Shakapacker asset.
  # In production mode, the digested reference is automatically looked up.
  # See: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content
  #
  # Example:
  #
  #   <%= preload_pack_asset 'fonts/fa-regular-400.woff2' %> # =>
  #   <link rel="preload" href="/packs/fonts/fa-regular-400-944fb546bd7018b07190a32244f67dc9.woff2" as="font" type="font/woff2" crossorigin="anonymous">
  #
  # source://shakapacker//lib/shakapacker/helper.rb#169
  def preload_pack_asset(name, **options); end

  # source://shakapacker//lib/shakapacker/helper.rb#349
  def prepend_javascript_pack_tag(*names, defer: T.unsafe(nil), async: T.unsafe(nil)); end

  # Sends HTTP 103 Early Hints for specified packs with fine-grained control over
  # JavaScript and CSS handling. This is the "raw" method for maximum flexibility.
  #
  # Use this in controller actions BEFORE expensive work (database queries, API calls)
  # to maximize parallelism - the browser downloads assets while Rails processes the request.
  #
  # For simpler cases, use javascript_pack_tag and stylesheet_pack_tag which automatically
  # send hints when called (combining queued + direct pack names).
  #
  # HTTP 103 Early Hints allows the server to send preliminary responses with Link headers
  # before the final HTTP 200 response, enabling browsers to start downloading critical
  # assets during the server's "think time".
  #
  # Timeline:
  #   1. Browser requests page
  #   2. Controller calls send_pack_early_hints (this method)
  #   3. Server sends HTTP 103 with Link: headers
  #   4. Browser starts downloading assets IN PARALLEL with step 5
  #   5. Rails continues expensive work (queries, rendering)
  #   6. Server sends HTTP 200 with full HTML
  #   7. Assets already downloaded = faster page load
  #
  # Requires Rails 5.2+, HTTP/2, and server support (Puma 5+, nginx 1.13+).
  # Gracefully degrades if not supported.
  #
  # References:
  # - Rails API: https://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-send_early_hints
  # - HTTP 103 Spec: https://datatracker.ietf.org/doc/html/rfc8297
  #
  # Examples:
  #
  #   # Controller pattern: send hints BEFORE expensive work
  #   def show
  #     send_pack_early_hints({
  #       "application" => { js: "preload", css: "preload" },
  #       "vendor" => { js: "prefetch", css: "none" }
  #     })
  #
  #     # Browser now downloading assets while we do expensive work
  #     @posts = Post.includes(:comments, :author).where(complex_conditions)
  #     # ... more expensive work ...
  #   end
  #
  #   # Supported handling values:
  #   # - "preload": High-priority, browser downloads immediately
  #   # - "prefetch": Low-priority, browser may download when idle
  #   # - "none" or false: Skip this asset type for this pack
  #
  # source://shakapacker//lib/shakapacker/helper.rb#224
  def send_pack_early_hints(config); end

  # Creates link tags that reference the css chunks from entrypoints when using split chunks API,
  # as compiled by webpack per the entries list in package/environments/base.js.
  # By default, this list is auto-generated to match everything in
  # app/javascript/entrypoints/*.js and all the dependent chunks. In production mode, the digested reference is automatically looked up.
  # See: https://webpack.js.org/plugins/split-chunks-plugin/
  #
  # Examples:
  #
  #   <%= stylesheet_pack_tag 'calendar', 'map' %> # =>
  #   <link rel="stylesheet" media="screen" href="/packs/3-8c7ce31a.chunk.css" />
  #   <link rel="stylesheet" media="screen" href="/packs/calendar-8c7ce31a.chunk.css" />
  #   <link rel="stylesheet" media="screen" href="/packs/map-8c7ce31a.chunk.css" />
  #
  #   When using the webpack-dev-server, CSS is inlined so HMR can be turned on for CSS,
  #   including CSS modules
  #   <%= stylesheet_pack_tag 'calendar', 'map' %> # => nil
  #
  # DO:
  #
  #   <%= stylesheet_pack_tag 'calendar', 'map' %>
  #
  # DON'T:
  #
  #   <%= stylesheet_pack_tag 'calendar' %>
  #   <%= stylesheet_pack_tag 'map' %>
  #
  # Early Hints:
  #   By default, HTTP 103 Early Hints are sent automatically when this helper is called,
  #   allowing browsers to preload CSS assets in parallel with Rails rendering.
  #
  #   <%= stylesheet_pack_tag 'application' %>
  #   # Automatically sends early hints for 'application' pack
  #
  #   # Customize handling per pack:
  #   <%= stylesheet_pack_tag 'application', 'vendor',
  #         early_hints: { 'application' => 'preload', 'vendor' => 'prefetch' } %>
  #
  #   # Disable early hints:
  #   <%= stylesheet_pack_tag 'application', early_hints: false %>
  #
  # source://shakapacker//lib/shakapacker/helper.rb#290
  def stylesheet_pack_tag(*names, early_hints: T.unsafe(nil), **options); end

  private

  # source://shakapacker//lib/shakapacker/helper.rb#389
  def available_sources_from_manifest_entrypoints(names, type:); end

  # Build a Link header value for early hints
  # Takes the already-resolved source_path to avoid duplicate lookup_source calls
  #
  # source://shakapacker//lib/shakapacker/helper.rb#543
  def build_link_header(source_path, source, as:, rel: T.unsafe(nil)); end

  # Check if early hints debug mode is enabled
  #
  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/helper.rb#467
  def early_hints_debug_enabled?; end

  # Check if early hints are enabled in configuration
  #
  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/helper.rb#458
  def early_hints_enabled?; end

  # Generate reason why early hints were skipped
  #
  # source://shakapacker//lib/shakapacker/helper.rb#531
  def early_hints_skip_reason; end

  # Returns the shared early hints storage from request.env
  # This ensures state is shared across controller/view contexts
  #
  # source://shakapacker//lib/shakapacker/helper.rb#565
  def early_hints_store; end

  # Check if early hints are supported by Rails and the request object
  #
  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/helper.rb#453
  def early_hints_supported?; end

  # Send accumulated early hints as a SINGLE 103 response
  # Browsers only process the first 103, so we send everything at once
  #
  # source://shakapacker//lib/shakapacker/helper.rb#624
  def flush_early_hints; end

  # source://shakapacker//lib/shakapacker/helper.rb#377
  def javascript_pack_tag_queue; end

  # source://shakapacker//lib/shakapacker/helper.rb#400
  def lookup_integrity(source); end

  # source://shakapacker//lib/shakapacker/helper.rb#404
  def lookup_source(source); end

  # Normalize and validate a single hint value
  # Converts false/nil to "none", downcases strings, validates against allowed values
  #
  # source://shakapacker//lib/shakapacker/helper.rb#517
  def normalize_hint_value(value); end

  # Normalize pack hints into a hash mapping pack names to validated hint values
  # Converts booleans, validates strings, and ensures only valid values are used
  #
  # source://shakapacker//lib/shakapacker/helper.rb#498
  def normalize_pack_hints(packs, early_hints); end

  # Handles rendering javascript and stylesheet tags with integrity, if that's enabled.
  #
  # source://shakapacker//lib/shakapacker/helper.rb#409
  def render_tags(sources, type, options); end

  # Resolve the effective early hints value
  # If nil or true, read from config; otherwise use the provided value
  #
  # source://shakapacker//lib/shakapacker/helper.rb#477
  def resolve_early_hints_value(early_hints, asset_type); end

  # source://shakapacker//lib/shakapacker/helper.rb#393
  def resolve_path_to_image(name, **options); end

  # Internal method to accumulate and send early hints
  # Sends only ONE 103 response (browsers ignore subsequent ones)
  # config: { "application" => "preload", "vendor" => "prefetch" }
  # type: :javascript or :stylesheet
  #
  # source://shakapacker//lib/shakapacker/helper.rb#573
  def send_early_hints_internal(config, type:); end

  # Wrapper for JavaScript early hints
  #
  # source://shakapacker//lib/shakapacker/helper.rb#664
  def send_javascript_early_hints_internal(config); end

  # Wrapper for stylesheet early hints
  #
  # source://shakapacker//lib/shakapacker/helper.rb#669
  def send_stylesheet_early_hints_internal(config); end

  # source://shakapacker//lib/shakapacker/helper.rb#385
  def sources_from_manifest_entrypoints(names, type:); end

  # @yield [hash_key]
  #
  # source://shakapacker//lib/shakapacker/helper.rb#357
  def update_javascript_pack_tag_queue(defer:, async:); end
end

# Represents a single instance of Shakapacker configuration and state
#
# An instance encapsulates all the configuration, compilation, and manifest
# lookup functionality for a specific Rails application. Most applications
# will use the shared instance accessible via {Shakapacker.instance}, but
# multiple instances can be created for testing or advanced scenarios.
#
# @example Creating an instance with custom paths
#   instance = Shakapacker::Instance.new(
#   root_path: "/path/to/app",
#   config_path: "/custom/config.yml"
#   )
# @example Using the default instance
#   instance = Shakapacker::Instance.new
#   instance.config.source_path
#   instance.manifest.lookup("application.js")
#
# source://shakapacker//lib/shakapacker/instance.rb#20
class Shakapacker::Instance
  # Creates a new Shakapacker instance
  #
  # @param config_path [String, Pathname, nil] the path to shakapacker.yml.
  #   Can also be set via SHAKAPACKER_CONFIG environment variable.
  #   Defaults to +config/shakapacker.yml+ within the root_path
  # @param root_path [String, Pathname, nil] the application root path.
  #   Defaults to Rails.root if Rails is defined, otherwise uses current directory
  # @return [Shakapacker::Instance] the new instance
  #
  # source://shakapacker//lib/shakapacker/instance.rb#41
  def initialize(root_path: T.unsafe(nil), config_path: T.unsafe(nil)); end

  # Returns the commands instance for build operations
  #
  # The commands object provides methods for bootstrapping, cleaning,
  # clobbering, and compiling assets.
  #
  # @return [Shakapacker::Commands] the commands
  #
  # source://shakapacker//lib/shakapacker/instance.rb#122
  def commands; end

  # Returns the compiler for this instance
  #
  # The compiler is responsible for executing webpack/rspack to compile assets.
  #
  # @return [Shakapacker::Compiler] the compiler
  #
  # source://shakapacker//lib/shakapacker/instance.rb#92
  def compiler; end

  # Returns the configuration object for this instance
  #
  # The configuration is loaded from the shakapacker.yml file and provides
  # access to all settings like source paths, output paths, and compilation options.
  #
  # @return [Shakapacker::Configuration] the configuration
  #
  # source://shakapacker//lib/shakapacker/instance.rb#68
  def config; end

  # The path to the Shakapacker configuration file
  #
  # @return [Pathname] the config file path
  #
  # source://shakapacker//lib/shakapacker/instance.rb#31
  def config_path; end

  # Returns the development server instance
  #
  # The dev server instance can query the status of the webpack-dev-server,
  # including whether it's running, its host/port, and configuration.
  #
  # @return [Shakapacker::DevServer] the dev server
  #
  # source://shakapacker//lib/shakapacker/instance.rb#102
  def dev_server; end

  # Returns the current Rails environment as a StringInquirer
  #
  # This allows for convenient environment checking:
  #   env.development? # => true/false
  #   env.production?  # => true/false
  #
  # @return [ActiveSupport::StringInquirer] the environment
  #
  # source://shakapacker//lib/shakapacker/instance.rb#58
  def env; end

  # Returns whether CSS should be inlined by the dev server
  #
  # CSS inlining is enabled when:
  # - The dev server has inline_css enabled
  # - Hot Module Replacement (HMR) is enabled
  # - The dev server is currently running
  #
  # @return [Boolean] true if CSS should be inlined
  #
  # source://shakapacker//lib/shakapacker/instance.rb#134
  def inlining_css?; end

  # The shared logger used by all Shakapacker instances
  #
  # @return [ActiveSupport::TaggedLogging] the logger
  #
  # source://shakapacker//lib/shakapacker/instance.rb#23
  def logger; end

  # source://shakapacker//lib/shakapacker/instance.rb#23
  def logger=(val); end

  # Returns the manifest for looking up compiled assets
  #
  # The manifest reads the manifest.json file produced by webpack/rspack
  # and provides methods to look up the compiled paths for source files.
  #
  # @return [Shakapacker::Manifest] the manifest
  #
  # source://shakapacker//lib/shakapacker/instance.rb#112
  def manifest; end

  # The root path of the application
  #
  # @return [Pathname] the application root path
  #
  # source://shakapacker//lib/shakapacker/instance.rb#27
  def root_path; end

  # Returns the compiler strategy for determining staleness
  #
  # The strategy (mtime or digest) determines how Shakapacker decides whether
  # assets need recompilation.
  #
  # @api private
  # @return [Shakapacker::CompilerStrategy] the compiler strategy
  #
  # source://shakapacker//lib/shakapacker/instance.rb#83
  def strategy; end

  class << self
    # source://shakapacker//lib/shakapacker/instance.rb#23
    def logger; end

    # source://shakapacker//lib/shakapacker/instance.rb#23
    def logger=(val); end
  end
end

# Manifest for looking up compiled asset paths
#
# The manifest reads the +manifest.json+ file produced by webpack/rspack during
# compilation and provides methods to look up the compiled (digested) paths for
# source files.
#
# This allows view helpers like +javascript_pack_tag+, +stylesheet_pack_tag+, and
# +asset_pack_path+ to take a reference to a source file (e.g., "calendar.js")
# and turn it into the compiled path with digest (e.g., "/packs/calendar-1016838bab065ae1e314.js").
#
# == Automatic Compilation
#
# When the configuration has +compile: true+ in shakapacker.yml, any lookups will
# automatically trigger compilation if the assets are stale. This is typically
# enabled in development and disabled in production.
#
# == Caching
#
# The manifest can cache the loaded data in memory when +cache_manifest: true+ is
# set in the configuration. This improves performance in production by avoiding
# repeated file reads.
#
# @example Looking up assets
#   manifest = Shakapacker.manifest
#   manifest.lookup("application.js")
#   #=> "/packs/application-abc123.js"
#
#   manifest.lookup!("missing.js")
#   #=> raises Shakapacker::Manifest::MissingEntryError
# @see Shakapacker::Helper
#
# source://shakapacker//lib/shakapacker/manifest.rb#32
class Shakapacker::Manifest
  # Creates a new manifest instance
  #
  # @param instance [Shakapacker::Instance] the Shakapacker instance
  # @return [Shakapacker::Manifest] the new manifest
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#42
  def initialize(instance); end

  # source://shakapacker//lib/shakapacker/manifest.rb#36
  def compiler(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/manifest.rb#36
  def config(*_arg0, **_arg1, &_arg2); end

  # source://shakapacker//lib/shakapacker/manifest.rb#36
  def dev_server(*_arg0, **_arg1, &_arg2); end

  # Looks up the compiled path for a given asset
  #
  # Computes the relative path for a Shakapacker asset using the manifest.json file.
  # If automatic compilation is enabled and the assets are stale, triggers a
  # compilation before looking up the path.
  #
  # @example
  #   Shakapacker.manifest.lookup('calendar.js')
  #   #=> "/packs/calendar-1016838bab065ae1e122.js"
  #
  #   Shakapacker.manifest.lookup('calendar', type: :javascript)
  #   #=> "/packs/calendar-1016838bab065ae1e122.js"
  # @param name [String] the source file name (e.g., "calendar.js" or "calendar")
  # @param pack_type [Hash] options hash with :type key (:javascript, :stylesheet, etc.).
  #   If not specified, the extension from the name is used.
  # @return [String, nil] the compiled asset path, or nil if not found
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#104
  def lookup(name, pack_type = T.unsafe(nil)); end

  # Like {#lookup}, but raises an error if the asset is not found
  #
  # @example
  #   Shakapacker.manifest.lookup!('calendar.js')
  #   #=> "/packs/calendar-1016838bab065ae1e122.js"
  #
  #   Shakapacker.manifest.lookup!('missing.js')
  #   #=> raises MissingEntryError
  # @param name [String] the source file name
  # @param pack_type [Hash] options hash with :type key
  # @raise [MissingEntryError] if the asset is not found in the manifest
  # @return [String] the compiled asset path
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#122
  def lookup!(name, pack_type = T.unsafe(nil)); end

  # Looks up an entry point with all its chunks (split code)
  #
  # This method is used when you need to load all chunks for a pack that has
  # been split via code splitting. It returns an array of asset paths for the
  # main entry and all its dynamic imports.
  #
  # @example
  #   manifest.lookup_pack_with_chunks("application", type: :javascript)
  #   #=> ["/packs/runtime-abc123.js", "/packs/application-def456.js"]
  # @param name [String] the entry point name (e.g., "application")
  # @param pack_type [Hash] options hash with :type key (:javascript, :stylesheet, etc.)
  # @return [Array<String>, nil] array of asset paths, or nil if not found
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#68
  def lookup_pack_with_chunks(name, pack_type = T.unsafe(nil)); end

  # Like {#lookup_pack_with_chunks}, but raises an error if not found
  #
  # @param name [String] the entry point name
  # @param pack_type [Hash] options hash with :type key
  # @raise [MissingEntryError] if the entry point is not found in the manifest
  # @return [Array<String>] array of asset paths
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#84
  def lookup_pack_with_chunks!(name, pack_type = T.unsafe(nil)); end

  # Reloads the manifest data from disk
  #
  # Forces a fresh read of the manifest.json file, bypassing any cache.
  # This is useful when you know the manifest has been updated.
  #
  # @return [Hash] the loaded manifest data
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#52
  def refresh; end

  private

  # source://shakapacker//lib/shakapacker/manifest.rb#131
  def compile; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#127
  def compiling?; end

  # source://shakapacker//lib/shakapacker/manifest.rb#135
  def data; end

  # source://shakapacker//lib/shakapacker/manifest.rb#143
  def find(name); end

  # source://shakapacker//lib/shakapacker/manifest.rb#152
  def full_pack_name(name, pack_type); end

  # @raise [Shakapacker::Manifest::MissingEntryError]
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#157
  def handle_missing_entry(name, pack_type); end

  # source://shakapacker//lib/shakapacker/manifest.rb#161
  def load; end

  # The `manifest_name` method strips of the file extension of the name, because in the
  # manifest hash the entrypoints are defined by their pack name without the extension.
  # When the user provides a name with a file extension, we want to try to strip it off.
  #
  # source://shakapacker//lib/shakapacker/manifest.rb#172
  def manifest_name(name, pack_type); end

  # source://shakapacker//lib/shakapacker/manifest.rb#176
  def manifest_type(pack_type); end

  # source://shakapacker//lib/shakapacker/manifest.rb#184
  def missing_file_from_manifest_error(bundle_name); end
end

# Raised when an asset cannot be found in the manifest
#
# source://shakapacker//lib/shakapacker/manifest.rb#34
class Shakapacker::Manifest::MissingEntryError < ::StandardError; end

# source://shakapacker//lib/shakapacker/mtime_strategy.rb#4
class Shakapacker::MtimeStrategy < ::Shakapacker::BaseStrategy
  # Returns true if manifest file mtime is newer than the timestamp of the last modified watched file
  #
  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/mtime_strategy.rb#6
  def fresh?; end

  # Returns true if manifest file mtime is older than the timestamp of the last modified watched file
  #
  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/mtime_strategy.rb#11
  def stale?; end

  private

  # source://shakapacker//lib/shakapacker/mtime_strategy.rb#21
  def latest_modified_timestamp; end

  # source://shakapacker//lib/shakapacker/mtime_strategy.rb#17
  def manifest_mtime; end
end

# source://shakapacker//lib/shakapacker/deprecation_helper.rb#4
Shakapacker::SHELL = T.let(T.unsafe(nil), Thor::Shell::Color)

# source://shakapacker//lib/shakapacker/utils/manager.rb#6
module Shakapacker::Utils; end

# source://shakapacker//lib/shakapacker/utils/manager.rb#7
class Shakapacker::Utils::Manager
  class << self
    # Emits a warning if it's not obvious what package manager to use
    #
    # @raise [Error]
    #
    # source://shakapacker//lib/shakapacker/utils/manager.rb#18
    def error_unless_package_manager_is_obvious!; end

    # Guesses the binary of the package manager to use based on what lockfiles exist
    #
    # @return [String]
    #
    # source://shakapacker//lib/shakapacker/utils/manager.rb#37
    def guess_binary; end

    # Guesses the version of the package manager to use by calling `<manager> --version`
    #
    # @return [String]
    #
    # source://shakapacker//lib/shakapacker/utils/manager.rb#44
    def guess_version; end

    # source://shakapacker//lib/shakapacker/utils/manager.rb#58
    def rails_root; end
  end
end

# source://shakapacker//lib/shakapacker/utils/manager.rb#8
class Shakapacker::Utils::Manager::Error < ::StandardError; end

# source://shakapacker//lib/shakapacker/utils/manager.rb#10
Shakapacker::Utils::Manager::MANAGER_LOCKS = T.let(T.unsafe(nil), Hash)

# Change the version in package.json too, please!
#
# source://shakapacker//lib/shakapacker/version.rb#3
Shakapacker::VERSION = T.let(T.unsafe(nil), String)

# source://shakapacker//lib/shakapacker/version_checker.rb#5
class Shakapacker::VersionChecker
  # @return [VersionChecker] a new instance of VersionChecker
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#14
  def initialize(node_package_version); end

  # Returns the value of attribute node_package_version.
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#6
  def node_package_version; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#18
  def raise_if_gem_and_node_package_versions_differ; end

  private

  # source://shakapacker//lib/shakapacker/version_checker.rb#37
  def common_error_msg; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#63
  def gem_major_minor_patch_version; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#59
  def gem_version; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#48
  def raise_differing_versions_warning; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#53
  def raise_node_semver_version_warning; end

  class << self
    # source://shakapacker//lib/shakapacker/version_checker.rb#10
    def build; end
  end
end

# source://shakapacker//lib/shakapacker/version_checker.rb#8
Shakapacker::VersionChecker::MAJOR_MINOR_PATCH_VERSION_REGEX = T.let(T.unsafe(nil), Regexp)

# TODO: this might as well use package_json
#
# source://shakapacker//lib/shakapacker/version_checker.rb#69
class Shakapacker::VersionChecker::NodePackageVersion
  # @return [NodePackageVersion] a new instance of NodePackageVersion
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#92
  def initialize(package_json, yarn_lock, package_lock, pnpm_lock); end

  # source://shakapacker//lib/shakapacker/version_checker.rb#111
  def major_minor_patch; end

  # Returns the value of attribute package_json.
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#70
  def package_json; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#99
  def raw; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#103
  def semver_wildcard?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#107
  def skip_processing?; end

  private

  # source://shakapacker//lib/shakapacker/version_checker.rb#144
  def find_version; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#167
  def from_package_lock; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#204
  def from_pnpm_lock; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#177
  def from_yarn_lock; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#132
  def git_url?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#136
  def github_url?; end

  # source://shakapacker//lib/shakapacker/version_checker.rb#140
  def package_json_contents; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#124
  def package_specified?; end

  # @return [Boolean]
  #
  # source://shakapacker//lib/shakapacker/version_checker.rb#128
  def relative_path?; end

  class << self
    # source://shakapacker//lib/shakapacker/version_checker.rb#72
    def build; end

    # source://shakapacker//lib/shakapacker/version_checker.rb#76
    def package_json_path; end

    # source://shakapacker//lib/shakapacker/version_checker.rb#84
    def package_lock_path; end

    # source://shakapacker//lib/shakapacker/version_checker.rb#88
    def pnpm_lock_path; end

    # source://shakapacker//lib/shakapacker/version_checker.rb#80
    def yarn_lock_path; end
  end
end
