inherit_mode:
  merge:
    - Exclude

plugins: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'sorbet/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'app/graphql/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - 'app/graphql/types/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/development.rb'

Rails/Output:
  Exclude:
    - 'lib/spooler.rb'
    - 'lib/spooler/**/*'

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/graphql/mutations/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
