# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ActionMailer::Base::Mail::Message; end
module ActionMailer::Collector; end
module Sidekiq::Process; end
module Sidekiq::SortedEntry; end
module Sidekiq::Web; end
