# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Base::Mutation`.
# Please instead update this file by running `bin/tapioca dsl Base::Mutation`.


class Base::Mutation
  sig { params(args: T.untyped).returns(T.untyped) }
  def resolve(**args); end
end
