on:
  schedule:
    # Every Day Midnight
    - cron: '0 0 * * *'
  workflow_dispatch: {}

name: "Daily"

jobs:
  checkAsdfUpdatesRuby:
    name: "ASDF Update Ruby"

    uses: ./.github/workflows/asdf-upgrade.yml
    with:
      plugin: "ruby"

  checkAsdfUpdatesNodeJs:
    name: "ASDF Update Node.js"

    uses: ./.github/workflows/asdf-upgrade.yml
    with:
      plugin: "nodejs"
